### DISCUSSION TITLE
Issue with symfony/panther on lambda

### DISCUSSION THREAD

**Discussion by cjobeili** [brefphp/bref#1012] [Support]
Hi everyone !

I am trying to build a serverless function to scrap a website with panther (it need js support).
In local no issue but when i put it in a lambda i get this message:

`Could not start chrome. Exit code: 126 (Invoked command cannot execute). Error output: sh: /var/task/drivers/chromedriver: cannot execute binary file\nsh: /var/task/drivers/chromedriver: Success\`

Here is my serverless.yml

```
service: panther-test-lambda

provider:
    name: aws
    region: us-east-1
    runtime: provided.al2

plugins:
    - ./vendor/bref/bref

functions:
    panther:
        handler: index.php
        description: ''
        layers:
            - ${bref:layer.php-80}

# Exclude files from deployment
package:
    patterns:
        - '!tests/**'
```

I know is not really a bref issue but does anyone know how to handle this ?

Thank you very much !

Edit:

So i was trying with the default binaries from the detect method of panther. I've tried with the linux binaries and now:

`error while loading shared libraries: libglib-2.0.so.0: cannot open shared object file: No such file or directory`

I'm assuming we are missing some libraries for the chromium to launch.

Do you think it's a good idea to create a brefextra addons to handle the panther case ?

Thank you !

Edit 2:

I've tried to build a docker image with the console runtime and download the chromedriver from the website and i get this error:

 ```
sh-4.2# ./chromedriver
./chromedriver: error while loading shared libraries: libxcb.so.1: cannot open shared object file: No such file or directory
```
