### DISCUSSION TITLE
Monolog formatter not being applied with bref

### DISCUSSION THREAD

**Discussion by allan-simon** [brefphp/bref#1025] [Support]
**Description:**

As I want my log to be forwarded to elasticsearch after being sent to cloudwatch , i'm using the monolog json formatter

so I have the following configuration 

```
monolog:
    handlers:
        main:
            type: stream
            path: "%kernel.logs_dir%/%kernel.environment%.log"
            level: debug
            channels: ["!event"]                          
            formatter: 'monolog.formatter.json'

```

It works perfectly:

   * locally
   * in my EC2  "classic" deployement 

However with bref on lambda I see some channels not being formatted :

```
[2021-04-16T09:29:18.039534+00:00] security.DEBUG: User was reloaded from a user provider. {
    "provider": "App\\Provider\\EndUserProvider",
    "username": "user@example.com"
} {
    "request_id": "21b36d09-8cc0-466c-b835-1bc8fb05bf47"
}
```

while others are formatted correctly 

```
{
    "message": "Matched route \"end_users_dashboard\".",
    "context": {
        "route": "end_users_dashboard",
        "route_parameters": {
            "_route": "end_users_dashboard",
            "subdomain": "app-demo.rosaly.info",
            "_controller": "App\\Controller\\EndUser\\EndUserController::dashboard"
        },
        "request_uri": "https:/xxxxx/dashboard",
        "method": "GET"
    },
    "level": 200,
    "level_name": "INFO",
    "channel": "request",
    "datetime": "2021-04-16T09:29:17.939215+00:00",
    "extra": {
        "request_id": "21b36d09-8cc0-466c-b835-1bc8fb05bf47"
    }
}

```

**How to reproduce:**

   * symfony 5.2
   * layer : arn:aws:lambda:eu-west-3:209497400698:layer:php-80-fpm:7 
   
nothing special , a simple  "PingController"  with a /ping return a blank answer trigger the issue
