### DISCUSSION TITLE
Bref Error on Laravel Endpoint

### DISCUSSION THREAD

**Discussion by nickrupert7** [brefphp/bref#1062] [Support] [answered]
Hi there 👋

This was originally posted as a comment on another issue (https://github.com/brefphp/bref/issues/385) but I've split it out here into its own issue because of moderator feedback that even though the error message is the same, the issue is likely unrelated.

I'm running a Laravel app and receiving an error one particular endpoint. All of my other endpoints work, it's just this one that's failing. At first I thought it might have been a memory overload, but my site is currently deployed on a dedicated server with 1/2 the memory of my lambda functions (500 MB vs 1024 MB). I also thought it might have been a timeout issue, but the endpoint errors out after about 8 seconds, which isn't even close to the 28 second limit on my function (see my serverless config below).

This is the error response in my browser:

```
{"message":"Internal Server Error"}
```

Super helpful right?
Couldn't find anything useful on Google either - just that original GitHub Issue.

It seems like my endpoint code is all running successfully. I sent Log messages to Papertrail all the way up to the return statement in my Controller, and all the logs go in successfully. Plus, no exceptions seem to be thrown in Laravel.

Watching the invocation and response in my dev tools, I see the following response header: `x-cache: Error from cloudfront`. Not sure if that's useful, but i suppose it helps to determine where the error is NOT. It did at least spark my memory, and I decided to check my Cloudwatch logs for the Lambda function, and I found this (which shows up every single time I hit the failing endpoint).

```
{
    "errorType": "Exception",
    "errorMessage": "Error while calling the Lambda runtime API: The requested URL returned error: 413",
    "stack": [
        "#0 /var/task/vendor/bref/bref/src/Runtime/LambdaRuntime.php(187): Bref\\Runtime\\LambdaRuntime->postJson()",
        "#1 /var/task/vendor/bref/bref/src/Runtime/LambdaRuntime.php(104): Bref\\Runtime\\LambdaRuntime->sendResponse()",
        "#2 /opt/bootstrap(43): Bref\\Runtime\\LambdaRuntime->processNextEvent()",
        "#3 {main}"
    ]
}
```
and
```
Fatal error: Uncaught Exception: Error while calling the Lambda runtime API: The requested URL returned error: 403 in /var/task/vendor/bref/bref/src/Runtime/LambdaRuntime.php:295
```

Here's the functions snippet of my serverless configuration file:

```
functions:
  # This function runs the Laravel website/API
  web:
    name: myapp-${opt:stage, 'dev'}-web
    handler: public/index.php
    timeout: 28 # in seconds (API Gateway has a timeout of 29 seconds)
    layers:
      - ${bref:layer.php-74-fpm}
    events:
      - httpApi: '*'

  # This function lets us run artisan commands in Lambda
  artisan:
    name: myapp-${opt:stage, 'dev'}-artisan
    handler: artisan
    timeout: 120 # in seconds
    layers:
      - ${bref:layer.php-74} # PHP
      - ${bref:layer.console} # The "console" layer
    events:
      - schedule:
          description: Running the Laravel Scheduler (schedule:run) every minute
          rate: rate(1 minute)
          input:
            cli: schedule:run

  worker:
    handler: worker.php
    timeout: 900 # in seconds
    layers:
      - ${bref:layer.php-74}
    events:
      - sqs:
          arn:
            Fn::GetAtt: [ Queue, Arn ]
          # Only 1 item at a time to simplify error handling
          batchSize: 1
```

One last final tidbit that makes this all particularly weird. When I return a hard-coded response in my endpoint like `return 'abc';` It works, and the correct result is rendered in my browser. When I return my view without any of the data it needs, it also succeeds in loading the page. But when I try to load the page with all of the data, it goes back to failing. This is why I originally thought it might be a memory or timeout issue, but I just can't get past the fact that it currently works on a server with 1/2 the memory as my lambda, and it fails after only ~8 seconds which is way less than the timeout on my function... Plus I don't see how that would result in the 403 error from bref.

Help would be much appreciated :)
