### DISCUSSION TITLE
Error in /tmp folder

### DISCUSSION THREAD

**Discussion by tmurtazin** [brefphp/bref#1128] [Support]
Hi!
I am trying to run the following instructions:
https://bref.sh/docs/frameworks/symfony.html

so right before deploy I'm running this:
```
APP_ENV=prod composer install --prefer-dist --optimize-autoloader --no-dev
php bin/console cache:warmup --env=prod
```

After I've deployed my project, I get the following error:

```
{
    "message": "Uncaught PHP Exception Symfony\\Component\\Filesystem\\Exception\\IOException: \"Cannot rename \"/tmp/catalogue.ru_RU.+y9xJ48.phpzRrGnb\" to \"/tmp/cache/prod/translations/catalogue.ru_RU.+y9xJ48.php\": rename(/tmp/catalogue.ru_RU.+y9xJ48.phpzRrGnb,/tmp/cache/prod/translations/catalogue.ru_RU.+y9xJ48.php): Read-only file system\" at /var/task/vendor/symfony/filesystem/Filesystem.php line 305",
    "context": {
        "exception": {
            "class": "Symfony\\Component\\Filesystem\\Exception\\IOException",
            "message": "Cannot rename \"/tmp/catalogue.ru_RU.+y9xJ48.phpzRrGnb\" to \"/tmp/cache/prod/translations/catalogue.ru_RU.+y9xJ48.php\": rename(/tmp/catalogue.ru_RU.+y9xJ48.phpzRrGnb,/tmp/cache/prod/translations/catalogue.ru_RU.+y9xJ48.php): Read-only file system",
            "code": 0,
            "file": "/var/task/vendor/symfony/filesystem/Filesystem.php:305"
        }
    },
    "level": 500,
    "level_name": "CRITICAL",
    "channel": "request",
    "datetime": "2021-12-16T18:08:22.801534+00:00",
    "extra": {}
}
```

Shouldn't the /tmp folder always be writable?
this is my serverless.yml

```

# Read the documentation at https://www.serverless.com/framework/docs/providers/aws/guide/serverless.yml/
service: symfony

provider:
    name: aws
    # The AWS region in which to deploy (us-east-1 is the default)
    region: us-east-2
    # The stage of the application, e.g. dev, production, staging… ('dev' is the default)
    stage: dev
    runtime: provided.al2
    environment:
        # Symfony environment variables
        APP_ENV: prod

plugins:
    - ./vendor/bref/bref

functions:
    # This function runs the Symfony website/API
    web:
        handler: public/index.php
        timeout: 28 # in seconds (API Gateway has a timeout of 29 seconds)
        layers:
            - ${bref:layer.php-80-fpm}
        events:
            - httpApi: '*'
    # This function let us run console commands in Lambda
    console:
        handler: bin/console
        timeout: 120 # in seconds
        layers:
            - ${bref:layer.php-80} # PHP
            - ${bref:layer.console} # The "console" layer

package:
    patterns:
        # Excluded files and folders for deployment
        - '!assets/**'
        - '!node_modules/**'
        - '!public/build/**'
        - '!tests/**'
        - '!var/**'
        # If you want to include files and folders that are part of excluded folders,
        # add them at the end
        - 'var/cache/prod/**'
        - 'public/build/entrypoints.json'
        - 'public/build/manifest.json'

```
