### DISCUSSION TITLE
Error when deploying docker image on lambda using SAM instead of serverless

### DISCUSSION THREAD

**Discussion by hafsalmetvr** [brefphp/bref#1136] [Support] [answered]
Hi @mnapoli 

I am running a Laravel application using docker and tried to deploy it in lambda using bref and SAM

Dockerfile
```
FROM bref/php-81-fpm
RUN curl -s https://getcomposer.org/installer | php
RUN php composer.phar require bref/bref
COPY . /var/task
CMD _HANDLER=index.php /opt/bootstrap
```
and i did sam build and sam deploy -g

but it shows error like "`entrypoint requires the handler name to be the first argument`
when i change Dockerfile like 

```
FROM bref/php-81-fpm
RUN curl -s https://getcomposer.org/installer | php
RUN php composer.phar require bref/bref
COPY . /var/task
CMD ["public/index.php"]
```
it returns error like `Fatal error: Uncaught Error: Class "Bref\Runtime\LambdaRuntime" not found in /var/runtime/bootstrap:28`

and my template.yaml is like

```
AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  ociphp2
  Sample SAM Template for php oci

Globals:
  Function:
    Timeout: 3

Resources:
  LaravelTest:
    Type: AWS::Serverless::Function
    Properties:
      PackageType: Image
      Events:
        DynamicRequestsRoot:
          Type: HttpApi
          Properties:
            Path: /
            Method: ANY
        DynamicRequestsProxy:
          Type: HttpApi
          Properties:
            Path: /{proxy+}
            Method: ANY
    Metadata:
      DockerTag: laratest
      DockerContext: ./
      Dockerfile: Dockerfile

Outputs:
  LaravelTest:
    Description: "API Gateway endpoint URL for Prod stage for LaravelAPI"
    Value: !Sub "https://${ServerlessHttpApi}.execute-api.${AWS::Region}.amazonaws.com/"
```

Actually i was successfully deploy and run application in lambda using serverless  framework (serverless.yml), but now i am facing issue while i tried same with AWS SAM

Any help would be appreciated. Thanks
