### DISCUSSION TITLE
Php fpm 7.4 lambda docker with gd extension

### DISCUSSION THREAD

**Discussion by onlinesid** [brefphp/bref#1171] [Support] [answered]
I can deploy this using `serverless deploy` and the php fpm part is working on AWS but `gd` extension is not loaded, please help, what did I miss to add `gd` extension?

Dockerfile:
```
FROM bref/php-74-fpm

# add gd extension
COPY --from=bref/extra-gd-php-74 /opt/bref-extra /opt/bref-extra
RUN echo 'extension=/opt/bref-extra/gd.so' >> /opt/bref/etc/php/php.ini

COPY . /var/task

CMD ["index.php"]
```

serverless.yml:
```
service: lambda-docker-test

provider:
    ecr:
        images:
            docker-php-74-fpm-gd-test:
                path: ./

plugins:
    - ./vendor/bref/bref
    - ./vendor/bref/extra-php-extensions

functions:
    test-docker:
        image:
            name: docker-php-74-fpm-gd-test
        events:
            - httpApi: '*'    
```

UPDATE: I re-read [bref doc for docker](https://bref.sh/docs/web-apps/docker.html) and changed the Dockerfile to this but `gd` is still not loaded

```
FROM bref/php-74-fpm

COPY --from=bref/extra-gd-php-74:latest /opt/bref-extra /opt/bref-extra

COPY . /var/task

CMD ["index.php"]
```
