### DISCUSSION TITLE
How are you do access your application container from a custom Lambda handler?

### DISCUSSION THREAD

**Discussion by robmellett** [brefphp/bref#1191] [General]
Hey guys!

I was just playing around with the lambda event handlers.
https://bref.sh/docs/function/handlers.html

I was wondering how you access your application container from the custom handlers though?

When uploading a file to S3, I'd like to trigger a specific artisan command but I'm a little stuck getting the artisan command to run with the s3 event payload.

I feel like I might be missing a step somewhere. Any suggestions would be much appreciated! 

```yml
functions:
  event:
    handler: serverless-handler.php
    timeout: 10 # in seconds
    events:
      - s3: ${self:custom.bucket}
    layers:
      - ${bref:layer.php-80}

custom:
  bucket: serverless-gifmaker
```

With a handler like this.

```php
// serverless-handler.php

<?php

namespace App\Lambda;

use App\Console\Kernel;
use Bref\Context\Context;

class S3Handler implements \Bref\Event\Handler
{
    public function handle($event, Context $context)
    {
       // I was trying to do something like this, but I've come to realise
       // I'd need to bootstrap the app, similar to the `artisan` command. 
        app()->make(Kernel::class)->call('generate:gif');

        return 'Hello ' . $event['name'];
    }
}

return new S3Handler();
```
