### DISCUSSION TITLE
Disable retries of SQS processing

### DISCUSSION THREAD

**Discussion by mikevang** [brefphp/bref#1197] [Support] [answered]
Hi all, it's me again.

I have a process that handles errors internally by sending emails on failure. As such I don't want the queue running multiple times on the same request. The default with serverless seems to be set 3 retries, and I can't find any information about how to disable that, aside from going into AWS console and manually editing it, which gets overwritten the next time I deploy. 

Setting maxRetries for the worker in serverless.yml doesn't seem to do anything, it still shows 3 in AWS console after a deploy.
```
constructs:
  jobs:
    type: queue
    worker:
      handler: worker.php
      maxRetries: 1
      timeout: 28
      layers:
        - ${bref:layer.php-80}
```

How can I make it so when the execution fails it goes straight into the dead letter queue?

**Comment by t-richard** [comment, marked as answer]
I think the config should be this (maxRetries outside of the worker key) 

```
constructs:
  jobs:
    type: queue
    maxRetries: 1
    worker:
      handler: worker.php
      timeout: 28
      layers:
        - ${bref:layer.php-80}
```
