### DISCUSSION TITLE
Cannot access assets

### DISCUSSION THREAD

**Discussion by 0x346e3730** [brefphp/bref#1243] [Support] [answered]
Hey, I've setup a new Symfony project with bref, everything's fine until the assets :

Here is my serverless.yml :
```yml
constructs:
  assets:
    type: server-side-website
    domain: assets.invoice.clauzier.dev
    certificate: arn:aws:acm:us-east-1:918492818297:certificate/b9b3d656-c4a5-44ab-aee9-47eb7e4571cf
    assets:
      '/': public/build/
```

I see my files in my S3 Bucket :
<img width="1339" alt="image" src="https://user-images.githubusercontent.com/28731165/178101403-8d4c2015-b7d1-4be5-a863-3d4da890390b.png">

However the files are not accessible :
<img width="729" alt="image" src="https://user-images.githubusercontent.com/28731165/178101425-dd496640-e999-48e7-9e68-31c58729684b.png">

`sls info`gives the following output :
```
Running "serverless" from node_modules
service: invoice-clauzierdotdev
stage: dev
region: eu-west-3
stack: invoice-clauzierdotdev-dev
endpoint: ANY - https://7ewhd5qnl0.execute-api.eu-west-3.amazonaws.com
functions:
  website: invoice-clauzierdotdev-dev-website
  console: invoice-clauzierdotdev-dev-console
assets:
  url: https://assets.invoice.clauzier.dev
  cname: difo5dfswdmxg.cloudfront.net
```

And I do have a CNAME record on `assets.invoice.clauzier.dev` that points to `difo5dfswdmxg.cloudfront.net`

What am I missing ?

**Comment by mnapoli** [comment, marked as answer]
Oh you seem to have missed 2 things:

- assets directories must end with `/*` -> this is pointed out in the docs, I think this is a simple oversight: https://github.com/getlift/lift/blob/master/docs/server-side-website.md#assets
- you cannot set `/` or `/*` for assets, because this is where the PHP application already is -> this isn't clear enough in the Lift documentation, I've opened https://github.com/getlift/lift/pull/239 to show a clear error message instead

You should try something like this instead:

```yaml
constructs:
  assets:
    type: server-side-website
    domain: assets.invoice.clauzier.dev
    certificate: arn:aws:acm:us-east-1:918492818297:certificate/b9b3d656-c4a5-44ab-aee9-47eb7e4571cf
    assets:
      '/build/*': public/build
```

and move the assets in a sub-directory (e.g. `assets` in my example above). https://bref.sh/docs/frameworks/symfony.html#assets might also help with other examples.

**Reply by 0x346e3730** [reply]
I didn't understood that even on that other domain `/` was hitting the Lambda, now I understand why I had Symfony's 404 ! I'm now having a CORS Issue because of the integrity check of the assets, I have `crossorigin="anonymous"` in my links but I need to add the `Access-Control-Allow-Origin` header on CloudFront/S3, how can I do so with serverless ?

**Reply by mnapoli** [reply]
I don't understand why you would have CORS issues, the point of the `server-side-website` is to serve the App + assets on the same domain.

I see that your domain is `assets.xxx`, how about this:

```yaml
constructs:
  assets:
    type: server-side-website
    domain: invoice.clauzier.dev
    certificate: arn:aws:acm:us-east-1:918492818297:certificate/b9b3d656-c4a5-44ab-aee9-47eb7e4571cf
    assets:
      '/build/*': public/build
```

I.e. put everything on the same domain.

Please read this documentation again: https://bref.sh/docs/websites.html

**Reply by 0x346e3730** [reply]
I went with another domain because it was the way to do in the old documentation but also because the Lambda is in a region and needs a same region issued certificate but Cloudfront/S3 is in "edge" and it needs a edge certificate. I've changed to
```yaml
constructs:
  assets:
    type: server-side-website
    domain: assets.invoice.clauzier.dev
    certificate: arn:aws:acm:us-east-1:918492818297:certificate/b9b3d656-c4a5-44ab-aee9-47eb7e4571cf
    cors: true
    assets:
      '/build/*': public/build/
```
And now everything is working fine. Thank's for your help !

EDIT : I actually removed the integrity check so I'm not longer affected by CORS but `cors: true` has no effect, so I don't know if I understood something wrong about the domains and the certificates regarding region or edge and I'm complicating my life for no reason or not, will give the same domain a try when I'll have time
