### DISCUSSION TITLE
Why am I not seeing PHP errors show up in CloudWatch?

### DISCUSSION THREAD

**Discussion by ctessmer** [brefphp/bref#1371] [Support]
I'm new to serverless and bref. So excited about the possibilities! 

But so far, I'm running blind: **I'm not seeing PHP errors/warnings in CloudWatch.**

The [bref documentation](https://bref.sh/docs/environment/logs.html#php-errors-and-warnings) says:

> By default, all PHP errors, warnings and notices emitted by PHP will be forwarded into CloudWatch.

But this isn't working for me—or I'm not looking in the right place.

## PHP Code

I intentionally put this error in my `public/index.php` file:

```php
<?php
// force error by referencing undefined expression
xxx_require '../db/connect-to-db.php';
```
## Expected CloudWatch output

Output of an error to an undefined expression `xxx_require`.

## Actual CloudWatch output

Instead, I'm just seeing "stats" of the invocation…

```
LOGS	Name: dev-mode-extension	State: Subscribed	Types: [platform,function]
[03-Jan-2023 07:28:16] NOTICE: [pool default] 'user' directive is ignored when FPM is not running as root
[03-Jan-2023 07:28:16] NOTICE: fpm is running, pid 20
EXTENSION	Name: dev-mode-extension	State: Ready	Events: [INVOKE,SHUTDOWN]
START RequestId: 54d57917-a607-4ca2-b6c1-e990d3e5e900 Version: $LATEST
[03-Jan-2023 07:28:16] NOTICE: ready to handle connections
[03-Jan-2023 07:28:16] NOTICE: systemd monitor interval set to 10000ms
END RequestId: 54d57917-a607-4ca2-b6c1-e990d3e5e900
REPORT RequestId: 54d57917-a607-4ca2-b6c1-e990d3e5e900	Duration: 78.60 ms	Billed Duration: 679 ms	Memory Size: 1024 MB	Max Memory Used: 92 MB	Init Duration: 600.37 ms	
```

Again: I'm expecting to see a PHP error lodged in the lines of logs above… somewhere… anywhere.

**Am I looking in the wrong place? Doing something wrong? Expecting something wrong?**

## The Bref logger

I also tried invoking the [bref logger](https://github.com/brefphp/logger) [after a composer install] of it via this code in my `public/index.php` file:

```php
// Invoke and test the bref logger
$logger = new \Bref\Logger\StderrLogger();
$logger->error('This is an error');
```

But I still don't see `This is an error` in the logs. 

Thanks for reading and any insight you might have. 😊

**Comment by afu-dev** [comment]
Hello Christian,

I tested the last version of Bref (FPM), and I guessed this is what you used if you are new to Bref.

Here are my files and the output I got in the logs:

```yaml
# serverless.yml
service: bref-discussions-1371

provider:
  name: aws
  region: eu-west-3 # Paris, France. You might want to change it.
  profile: perso # Note: optional, I handle multiple accounts
  runtime: provided.al2
  timeout: 10
  layers:
    - ${bref:layer.php-82-fpm}


plugins:
  - ./vendor/bref/bref

functions:
  hello:
    handler: hello.php
    events:
      - httpApi: 'GET /hello'
  error:
    handler: error.php
    events:
      - httpApi: 'GET /error'

# Exclude files from deployment
package:
  patterns:
    - '!node_modules/**'
    - '!tests/**'
```

```php
# hello.php
<?php

use Bref\Logger\StderrLogger;

require "vendor/autoload.php";

$logger = new StderrLogger();

$logger->error("This is an error");
$logger->notice("And a notice"); // won't be written in CloudWatch, default log level = "warning"
```

```php
# error.php
<?php

require "vendor/autoload.php";

$error =;
```

```json
{
    "require": {
        "bref/bref": "^1.7",
        "bref/logger": "^1.0"
    }
}
```

And here's the console output for the logs:

```console
$ sls logs --function hello
[03-Jan-2023 10:18:12] NOTICE: fpm is running, pid 9
[03-Jan-2023 10:18:12] NOTICE: ready to handle connections
START
[ERROR] This is an error
END Duration: 23.17 ms (init: 306.18 ms) Memory Used: 67 MB

$ sls logs --function error
START
[03-Jan-2023 10:18:17] NOTICE: ready to handle connections
NOTICE: PHP message: PHP Parse error:  syntax error, unexpected token ";" in /var/task/error.php on line 5
END Duration: 10.71 ms (init: 295.62 ms) Memory Used: 66 MB
```

Did you try to look for the logs directly from your CLI? Or did you use the AWS Console? For the latter, you can find the logs in the Log Groups section of CloudWatch:

![image](https://user-images.githubusercontent.com/15209405/210339059-480535f4-98af-47bc-9a92-a379f07d9645.png)

Or directly inside the Lambda function you deployed:

![image](https://user-images.githubusercontent.com/15209405/210339296-9f6295c3-5383-4de6-89b2-919a4fadf919.png)

I hope this can help. If it doesn't, can you share a bit more code with us? Your serverless.yml file, the version of Bref you used, the version of the Serverless Framework you are running, etc. The more, the better :wink:

_Edit: added two comments in the `serverless.yml` file._
