### DISCUSSION TITLE
Unable to create the cache directory (/tmp/cache/prod/twig/88)

### DISCUSSION THREAD

**Discussion by iceyu07** [brefphp/bref#1401] [Support]
i'm using symfony 6.1 and bref 1.7, when i deploy the project to aws lambda,
if i visit a twig template page i got error: **Unable to create the cache directory (/tmp/cache/prod/twig/88),**
when visit a api url it works fine.
how can i resolve the issue.
thank you very much

```<!--StartFragment-->

2023-02-06T12:39:04.444+08:00
{
  "message": "Uncaught PHP Exception RuntimeException: \"Unable to create the cache directory (/tmp/cache/prod/twig/88).\" at /var/task/vendor/twig/twig/src/Cache/FilesystemCache.php line 53",
  "context": {
    "exception": {
      "class": "RuntimeException",
      "message": "Unable to create the cache directory (/tmp/cache/prod/twig/88).",
      "code": 0,
      "file": "/var/task/vendor/twig/twig/src/Cache/FilesystemCache.php:53"
    }
  },
  "level": 500,
  "level_name": "CRITICAL",
  "channel": "request",
  "datetime": "2023-02-06T04:39:04.403355+00:00",
  "extra": {}
} 

{
  "message": "Uncaught PHP Exception RuntimeException: \"Unable to create the cache directory (/tmp/cache/prod/twig/88).\" at /var/task/vendor/twig/twig/src/Cache/FilesystemCache.php line 53",
  "context": {
    "exception": {
      "class": "RuntimeException",
      "message": "Unable to create the cache directory (/tmp/cache/prod/twig/88).",
      "code": 0,
      "file": "/var/task/vendor/twig/twig/src/Cache/FilesystemCache.php:53"
    }
  },
  "level": 500,
  "level_name": "CRITICAL",
  "channel": "request",
  "datetime": "2023-02-06T04:39:04.403355+00:00",
  "extra": {}
}


<!--EndFragment-->```

**Comment by mnapoli** [comment]
Hi, are you using the Symfony bridge for Bref?

**Reply by iceyu07** [reply]
```
use Bref\SymfonyBridge\BrefKernel;

class Kernel extends BrefKernel
{
    use MicroKernelTrait;
}
```
thank you for your help.
i using BrefKernel to replaced BaseKernel

**Comment by iceyu07** [comment]
here is my serverless.yml
```
service: symfony

provider:
    name: aws
    # The AWS region in which to deploy (us-east-1 is the default)
    region: us-east-1
    # The stage of the application, e.g. dev, production, staging… ('dev' is the default)
    stage: dev
    runtime: provided.al2
    environment:
        # Symfony environment variables
        APP_ENV: prod

plugins:
    - ./vendor/bref/bref

functions:
    # This function runs the Symfony website/API
    web:
        handler: public/index.php
        timeout: 28 # in seconds (API Gateway has a timeout of 29 seconds)
        layers:
            - ${bref:layer.php-81-fpm}
        events:
            - httpApi: '*'
    # This function let us run console commands in Lambda
    console:
        handler: bin/console
        timeout: 120 # in seconds
        layers:
            - ${bref:layer.php-81} # PHP
            - ${bref:layer.console} # The "console" layer

package:
    patterns:
        # Excluded files and folders for deployment
        - '!assets/**'
        - '!node_modules/**'
        - '!public/build/**'
        - '!public/uploads/**'
        - '!tests/**'
        - '!var/**'
        - '!docker/**'
        - '!.idea/**'
        # If you want to include files and folders that are part of excluded folders,
        # add them at the end
        - 'var/cache/prod/**'
        - 'public/build/entrypoints.json'
        - 'public/build/manifest.json'
```
