### DISCUSSION TITLE
Laravel/Livewire File Upload Stopped Working

### DISCUSSION THREAD

**Discussion by selfsimilar** [brefphp/bref#1435] [Support] [answered]
This isn't a Bref issue, per se, but the issue only occurs when deployed on Bref, and it is most likely a misconfiguration in my `serverless.yml` file, or possibly a new issue that will require a code change in Laravel to make it compatible with Bref.

I recently updated to Laravel 10, and everything is working locally, but one page is broken when deployed via Bref. I think the issue is that Laravel's [`storage_path()` helper](https://github.com/laravel/framework/blob/10.x/src/Illuminate/Foundation/Application.php#L532) is returning the application directory (`/var/task/storage`) instead of the temp directory (`/tmp/storage`). 

<details>
<summary>Relevant portion of the stack trace is:</summary>

```
[2023-03-01 09:56:01] dev.ERROR: file_put_contents(/var/task/storage/framework/cache/facade-c2f53e2d655810ac111b48d42b34b209861bb985.php): Failed to open stream: No such file or directory {"userId":1,"exception":"[object] (ErrorException(code: 0): file_put_contents(/var/task/storage/framework/cache/facade-c2f53e2d655810ac111b48d42b34b209861bb985.php): Failed to open stream: No such file or directory at /var/task/vendor/laravel/framework/src/Illuminate/Foundation/AliasLoader.php:108)
[stacktrace]
#0 /var/task/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(250): Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleError()
#1 [internal function]: Illuminate\\Foundation\\Bootstrap\\HandleExceptions->Illuminate\\Foundation\\Bootstrap\\{closure}()
#2 /var/task/vendor/laravel/framework/src/Illuminate/Foundation/AliasLoader.php(108): file_put_contents()
#3 /var/task/vendor/laravel/framework/src/Illuminate/Foundation/AliasLoader.php(92): Illuminate\\Foundation\\AliasLoader->ensureFacadeExists()
#4 /var/task/vendor/laravel/framework/src/Illuminate/Foundation/AliasLoader.php(74): Illuminate\\Foundation\\AliasLoader->loadFacade()
#5 /var/task/vendor/livewire/livewire/src/WithFileUploads.php(19): Illuminate\\Foundation\\AliasLoader->load()
#6 /var/task/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(36): App\\Http\\Livewire\\MobileUploaderPage->startUpload()
#7 /var/task/vendor/laravel/framework/src/Illuminate/Container/Util.php(41): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#8 /var/task/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(93): Illuminate\\Container\\Util::unwrapIfClosure()
#9 /var/task/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(37): Illuminate\\Container\\BoundMethod::callBoundMethod()
#10 /var/task/vendor/livewire/livewire/src/ComponentConcerns/HandlesActions.php(149): Illuminate\\Container\\BoundMethod::call()
#11 /var/task/vendor/livewire/livewire/src/HydrationMiddleware/PerformActionCalls.php(38): Livewire\\Component->callMethod()
#12 /var/task/vendor/livewire/livewire/src/LifecycleManager.php(89): Livewire\\HydrationMiddleware\\PerformActionCalls::hydrate()
#13 /var/task/vendor/livewire/livewire/src/Connection/ConnectionHandler.php(13): Livewire\\LifecycleManager->hydrate()
#14 /var/task/vendor/livewire/livewire/src/Controllers/HttpConnectionHandler.php(21): Livewire\\Connection\\ConnectionHandler->handle()
#15 /var/task/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(46): Livewire\\Controllers\\HttpConnectionHandler->__invoke()
```

</details>

Clearly Livewire is trying to write to `/var/task/storage/framework/cache/facade-{$hash}.php` and failing. I have many Livewire pages that work fine, but this one implements the [`WithFileUploads` trait](https://github.com/livewire/livewire/blob/master/src/WithFileUploads.php#L19), which tries to call a Livewire facade that apparently doesn't exist yet. So `Illuminate\Foundation\AliasLoader` tries to fix that, but fails 'cause it's writing to the wrong place, I _believe_ because Laravel's [`EnsureFacadeExists()`](https://github.com/laravel/framework/blob/10.x/src/Illuminate/Foundation/AliasLoader.php#L103) is checking existence based on the results of `storage_path()`, and I've confirmed that `storage_path()` currently returns `/var/task/storage`, which is wrong, but after digging through the Laravel Docs I'm struggling to find out how to set that value.

The helper [`storage_path()`](https://github.com/laravel/framework/blob/10.x/src/Illuminate/Foundation/helpers.php#L865) is an alias for [`app()->storagePath()`](https://github.com/laravel/framework/blob/10.x/src/Illuminate/Foundation/Application.php#L532), but as far as I can tell, `path.storage` is not an alias for a particular Filesystem entry from `config/filesystem.php` but rather looks like it defaults to `__DIR__` or something like that.

Again, this was all working before upgrading from Laravel 9 to 10 (which required many dependencies to also be upgraded), which makes me think that some dependency code changed, but it's also possible this is a configuration change error. I'm pretty sure I could fix this by setting `storage_path()` properly but I've struck out so far.

Based off of light searching, it seems like the only way to do this is [via code, (e.g. editing `App\Providers\AppServiceProvider::register()`](https://www.amezmo.com/blog/how-to-change-the-default-storage-path-in-laravel/) - there doesn't appear to be an exposed configuration/environment variable. But it's also very possible that I have misconfigured something.

Any advice is welcome.

<details>
<summary>Here's my `serverless.yml` file. Lighted edited for clarity</summary>

```yml
service: laravel

params:
  default:
    app_debug: true
    app_env: dev
    app_key: ${ssm:/laravel/app_key}
    app_name: APP
    app_storage: /tmp
    aws_access_key_id: ${ssm:/laravel/aws_access_key_id}
    aws_endpoint: https://s3.us-east-2.amazonaws.com
    aws_public_endpoint: https://s3.amazonaws.com
    aws_secret_access_key: ${ssm:/laravel/aws_secret_access_key}
    broadcast_driver: log
    certificate_arn: ${ssm:/laravel/certificate_arn}
    db_connection: mysql
    db_database: app
    db_host: ${ssm:/laravel/db_host}
    db_password: ${ssm:/laravel/db_pwd}
    db_port: ${ssm:/laravel/db_port}
    db_username: app
    livewire_manifest_path: /tmp/storage/livewire-compoonents.php
    view_compiled_path: /tmp/storage/framework/views
    log_channel: stderr
    log_level: debug
    mail_from_name: ${param:app_name}
    mail_host: mailhog
    mail_mailer: smtp
    mail_port: 1025
    private_route_table_1a_id: ${ssm:/laravel/private_route_table_1a_id}
    private_subnet_1a_id: ${ssm:/laravel/private_subnet_1a_id}
    private_subnet_1b_id: ${ssm:/laravel/private_subnet_1b_id}
    public_route_table_id: ${ssm:/laravel/public_route_table_id}
    public_subnet_1a_id: ${ssm:/laravel/public_subnet_1a_id}
    queue_connection: sync
    session_cookie: my_app_session
    session_lifetime: 120
    session_secure_cookies: true
    vpc_id: ${ssm:/laravel/vpc_id}
  dev:
    asset_bucket_name: dev.assets.app.net
    app_debug: false
    domain: dev.my.app.net
    profile: terraform-dev
    aws_public_bucket: app-dev-public-my
    aws_public_url: https://12345asdf.cloudfront.net
  prod:
    app_env: production
    asset_bucket_name: assets.app.net
    cache_instance_size: cache.t3.small
    domain: my.app.net
    app_debug: false
    profile: terraform-prod
    aws_public_bucket: app-prod-my-public
    aws_public_url: https://cdn.app.net
  stage:
    app_env: stage
    asset_bucket_name: stage.assets.app.net
    domain: stage.my.app.net
    profile: terraform-stage

provider:
  name: aws
  profile: ${param:profile}
  region: us-east-2
  stage: ${opt:stage, 'stage'}
  runtime: provided.al2
  apiGateway:
    shouldStartNameWithService: true
  environment:
    APP_DEBUG: ${param:app_debug}
    APP_ENV: ${param:app_env}
    APP_KEY: ${param:app_key}
    APP_NAME: ${param:app_name}
    APP_STORAGE: ${param:app_storage}
    APP_URL: https://${param:domain}
    ASSET_URL: https://${param:domain}
    LIVEWIRE_ASSET_URL: https://${param:domain}
    LOG_CHANNEL: ${param:log_channel}
    LOG_LEVEL: ${param:log_level}
    QUEUE_CONNECTION: ${param:queue_connection}
    SERVER_SOFTWARE: bref
    TELESCOPE_ENABLED: false

    # DB
    DB_CONNECTION: ${param:db_connection}
    DB_DATABASE: ${param:db_database}
    DB_HOST: ${param:db_host}
    DB_PASSWORD: ${param:db_password}
    DB_PORT: ${param:db_port}
    DB_USERNAME: ${param:db_username}

    # Drivers
    BROADCAST_DRIVER: ${param:broadcast_driver}
    CACHE_DRIVER: ${param:cache_driver}
    SCOUT_DRIVER: ${param:scout_driver}

    # Filesystem paths
    FILESYSTEM_DISK: public
    LIVEWIRE_MANIFEST_PATH: ${param:livewire_manifest_path}
    VIEW_COMPILED_PATH: ${param:view_compiled_path}

    # Third-party Integration keys and settings:

    # AWS S3
    # AWS_DEFAULT_REGION: ${param:aws_default_region}
    AWS_ENDPOINT: ${param:aws_endpoint}
    # Public AWS S3
    AWS_PUBLIC_ACCESS_KEY_ID: ${param:aws_access_key_id}
    AWS_PUBLIC_BUCKET: ${param:aws_public_bucket}
    AWS_PUBLIC_ENDPOINT: ${param:aws_public_endpoint}
    AWS_PUBLIC_SECRET_ACCESS_KEY: ${param:aws_secret_access_key}
    AWS_PUBLIC_URL: ${param:aws_public_url}

package:
  # Directories to exclude from deployment
  patterns:
    - '!.env'
    - '!node_modules/**'
    - '!public/storage'
    - '!resources/assets/**'
    - '!storage/**'
    - '!tests/**'
    - '!vendor/laravel/dusk/bin/**'
    - '!vendor/**/docs/**'
    - '!vendor/**/tests/**'

functions:
  web:
    handler: public/index.php
    timeout: 28 # in seconds (API Gateway has a timeout of 29 seconds)
    layers:
      - ${bref:layer.php-81-fpm}
      - ${bref-extra:redis-php-81}
    events:
      - httpApi: '*'
    vpc:
      securityGroupIds:
        - !GetAtt ServerlessSecurityGroup.GroupId
        - ${ssm:/laravel/mysql_security_group_id}
      subnetIds:
        - ${param:private_subnet_1a_id}
        - ${param:private_subnet_1b_id}

  artisan:
    handler: artisan
    timeout: 120 # in seconds
    layers:
      - ${bref:layer.php-81} # PHP
      - ${bref-extra:redis-php-81}
      - ${bref:layer.console} # The "console" layer
    vpc:
      securityGroupIds:
        - !GetAtt ServerlessSecurityGroup.GroupId
        - ${ssm:/laravel/mysql_security_group_id}
      subnetIds:
        - ${param:private_subnet_1a_id}
        - ${param:private_subnet_1b_id}

  cron:
    handler: artisan
    layers:
      - ${bref:layer.php-81} # PHP
      - ${bref-extra:redis-php-81}
      - ${bref:layer.console} # The "console" layer
    vpc:
      securityGroupIds:
        - !GetAtt ServerlessSecurityGroup.GroupId
        - ${ssm:/laravel/mysql_security_group_id}
      subnetIds:
        - ${param:private_subnet_1a_id}
        - ${param:private_subnet_1b_id}

plugins:
  - ./vendor/bref/bref
  - ./vendor/bref/extra-php-extensions
  - serverless-lift

resources:
  Resources:
    SubnetRouteTableAssociationLambdaPrivateA:
      Type: AWS::EC2::SubnetRouteTableAssociation
      Properties:
        SubnetId: ${param:private_subnet_1a_id}
        RouteTableId: ${param:private_route_table_1a_id}

    SubnetRouteTableAssociationLambdaPublicA:
      Type: AWS::EC2::SubnetRouteTableAssociation
      Properties:
        SubnetId: ${param:public_subnet_1a_id}
        RouteTableId: ${param:public_route_table_id}

    ServerlessSecurityGroup:
      Type: AWS::EC2::SecurityGroup
      Properties:
        GroupDescription: SecurityGroup for Serverless Functions
        VpcId: ${param:vpc_id}

constructs:
  website:
    type: server-side-website
    assets:
      '/css/*': public/css
      '/img/*': public/img
      '/js/*': public/js
      '/vendor/*': public/vendor
      '/favicon.ico': public/favicon.ico
      '/mix-manifest.json': public/mix-manifest.json
      '/robots.txt': public/favicon.ico
    certificate: ${param:certificate_arn}
    domain: ${param:domain}
    forwardedHeaders:
      - Accept
      - Accept-Language
      - Content-Type
      - Origin
      - Referer
      - User-Agent
      - X-Forwarded-Host
      - X-Requested-With
      - X-Csrf-Token
      - X-Livewire
```

</details>
