### DISCUSSION TITLE
Unable to load intl extension

### DISCUSSION THREAD

**Discussion by nicodemuz** [brefphp/bref#1525] [Support]
I have an issue where I'm getting the following warning:
```Warning: PHP Startup: Unable to load dynamic library 'intl' (tried: /opt/lib/php/extensions/no-debug-non-zts-20210902/intl (/opt/lib/php/extensions/no-debug-non-zts-20210902/intl: cannot open shared object file: No such file or directory), /opt/lib/php/extensions/no-debug-non-zts-20210902/intl.so (/opt/lib/php/extensions/no-debug-non-zts-20210902/intl.so: cannot open shared object file: No such file or directory)) in Unknown on line 0```

Any idea where I'm going wrong? I'm using docker images with the following Dockerfile:
```
FROM bref/php-81-fpm

# Install PHP Imagick
COPY --from=bref/extra-imagick-php-81:0.12.1 /opt /opt

# Install fonts and font building tools
RUN yum -y install stix-fonts fontconfig wget tar xz make fontforge

# Build Thai fonts
RUN wget https://linux.thai.net/pub/thailinux/software/fonts-tlwg/fonts-tlwg-0.6.1.tar.xz -O /tmp/fonts-tlwg-0.6.1.tar.xz; \
    cd /tmp; \
    tar -xf fonts-tlwg-0.6.1.tar.xz; \
    cd fonts-tlwg-0.6.1; \
    ./configure; \
    make; \
    make install; \
    cd ..; \
    mkdir thai; \
    find . -name '*.ttf' | cpio -pdm ./thai; \
    cd thai; \
    cp -R fonts-tlwg-0.6.1/ /usr/share/fonts/; \
    fc-cache -frv /usr/share/fonts/

# Install wkhtmltopdf
RUN yum -y install openssl-devel bzip2-devel libffi-devel wget tar gzip make gcc-c++
RUN wget https://github.com/wkhtmltopdf/packaging/releases/download/0.12.6-1/wkhtmltox-0.12.6-1.amazonlinux2.x86_64.rpm
RUN yum -y install wkhtmltox-0.12.6-1.amazonlinux2.x86_64.rpm

# Copy Symfony codebase
COPY . /var/task

# Configure the handler file (the entrypoint that receives all HTTP requests)
CMD ["public/index.php"]
```

Below is my serverless.yml file:
```
# Read the documentation at https://www.serverless.com/framework/docs/providers/aws/guide/serverless.yml/
service: symfony-docker

provider:
    name: aws
    # The AWS region in which to deploy (us-east-1 is the default)
    region: ap-southeast-1
    runtime: provided.al2
    environment:
        # Symfony environment variables
        APP_ENV: ${opt:stage}
        BREF_BINARY_RESPONSES: '1'
        FONTCONFIG_PATH: /usr/share/fonts/
        PHP_INI_SCAN_DIR: /var/task/config/packages/lambda/

    # See https://bref.sh/docs/runtimes/http.html#binary-requests-and-responses
    apiGateway:
        binaryMediaTypes:
            - '*/*'

    ecr:
        images:
            lms-image:
                path: ./
                file: Dockerfile

plugins:
    - ./vendor/bref/bref
    - ./vendor/bref/extra-php-extensions

functions:
    # This function runs the Symfony website/API
    web:
        image:
            name: lms-image
        timeout: 28 # in seconds (API Gateway has a timeout of 29 seconds)
        events:
            - httpApi: '*'

package:
    patterns:
        # Excluded files and folders for deployment
        - '!assets/**'
        - '!node_modules/**'
        - '!public/**'
        - '!tests/**'
        - '!var/**'
        - '!src/DataFixtures/data/**'
        # Exclude large directories
        - '!vendor/symfony/intl/Resources/**'
        # If you want to include files and folders that are part of excluded folders,
        # add them at the end
        - 'public/build/entrypoints.json'
        - 'public/build/manifest.json'
        - 'public/index.php'

```
