### DISCUSSION TITLE
serverlss AWS temporary credentials are not working

### DISCUSSION THREAD

**Discussion by kareemashraf** [brefphp/bref#1561] [Support]
im trying to upload an image to S3 from my Laravel project using Bref and serverless, 
but im getting an error message that says “_The AWS Access Key Id you provided does not exist in our records._” 
This means that the credentials that im using to access S3 are not valid or recognized by AWS
after few researches i found this on the serverless website:
_

> "How it works: Serverless Dashboard uses an AWS Access Role to access your AWS account. Then, it creates temporary AWS access keys to authenticate the serverless CLI on every command."

_ 

ideally i dont need to include the credentials in serverless.yml or even .env files (already tried)
so how to get this temporary credentials _(that starts with ASIA)_ to work or how to force it to use the long-term credentials _(that starts with AKIA)_

the serverless.yml file is 
```
service: test-Demo

provider:
  name: aws
  profile: default
  # The AWS region in which to deploy (us-east-1 is the default)
  region: us-east-1
  # The stage of the application, e.g. dev, production, staging… ('dev' is the default)
  stage: dev
  runtime: provided.al2
  apiGateway:
    binaryMediaTypes:
      - '*/*'
  environment:
    BREF_BINARY_RESPONSES: '1'
    # environment variable for Laravel
    FILESYSTEM_DISK: s3
    FILESYSTEM_DRIVER: s3
    AWS_BUCKET: !Ref Storage
    APP_ENV: 'dev'
    DB_HOST: 'xxxx'
    DB_HOST_2: 'xxxx'

  iam:
    role:
      statements:
        # Allow Lambda to read and write files in the S3 buckets
        - Effect: Allow
          Action: s3:*
          Resource:
            - !Sub '${Storage.Arn}' # the storage bucket
            - !Sub '${Storage.Arn}/*' # and everything inside

package:
  # Directories to exclude from deployment
  patterns:
    - '!node_modules/**'
    - '!public/storage'
    - '!resources/assets/**'
    - '!tests/**'

custom:
  lift:
    assets:
      path: public
      url: /

functions:
  # This function runs the Laravel website/API
  web:
    handler: public/index.php
    timeout: 28 # in seconds (API Gateway has a timeout of 29 seconds)
    layers:
      - ${bref:layer.php-80-fpm}
      - ${bref-extra:gd-php-80} #add
    events:
      - httpApi: '*'
  # This function lets us run artisan commands in Lambda
  artisan:
    handler: artisan
    timeout: 120 # in seconds
    layers:
      - ${bref:layer.php-80} # PHP
      - ${bref:layer.console} # The "console" layer
    events:
      - schedule:
          description: Running the Laravel Scheduler (schedule:run) each minute
          rate: rate(1 minute)
          input:
            cli: schedule:run

plugins:
  # We need to include the Bref plugin
  - ./vendor/bref/bref
  - serverless-lift
  - ./vendor/bref/extra-php-extensions  #https://github.com/brefphp/extra-php-extensions

constructs:
  website:
    type: server-side-website
    assets:
      '/css/*': public/css
      '/js/*': public/js
      '/images/*': public/images
      '/audio/*': public/audio
      '/fonts/*': public/fonts
      '/import/*': public/import
      # add here any file or directory that needs to be served from S3

resources:
  Resources:
    # Create our S3 storage bucket using CloudFormation
    Storage:
      Type: AWS::S3::Bucket

    BucketPolicy:
      Type: AWS::S3::BucketPolicy
      Properties:
        Bucket: !Ref Storage
        PolicyDocument:
          Statement:
            - Sid: PublicReadGetObject
              Effect: Allow
              Principal: '*'
              Action: s3:GetObject
              Resource: !Join ['', [!GetAtt Storage.Arn, '/*']]


```
