### DISCUSSION TITLE
Running tests `php artisan test`

### DISCUSSION THREAD

**Discussion by aadityamundhalia** [brefphp/bref#1566] [Support]
Can any one please help me with running tests I have deployed my application but unable to run tests keep getting below:
```
Running "serverless" from node_modules
{
    "errorType": "Exception",
    "errorMessage": "The command exited with a non-zero status code: 2",
    "stackTrace": [
        "#0 /var/task/vendor/bref/bref/src/Runtime/Invoker.php(29): Bref\\ConsoleRuntime\\Main::Bref\\ConsoleRuntime\\{closure}('test', Object(Bref\\Context\\Context))",
        "#1 /var/task/vendor/bref/bref/src/Runtime/LambdaRuntime.php(89): Bref\\Runtime\\Invoker->invoke(Object(Closure), 'test', Object(Bref\\Context\\Context))",
        "#2 /var/task/vendor/bref/bref/src/ConsoleRuntime/Main.php(63): Bref\\Runtime\\LambdaRuntime->processNextEvent(Object(Closure))",
        "#3 /opt/bref/bootstrap.php(17): Bref\\ConsoleRuntime\\Main::run()",
        "#4 {main}"
    ]
}
--------------------------------------------------------------------
START
PHPUnit 10.2.1 by Sebastian Bergmann and contributors.
Test directory "/var/task/./tests/Unit" not found
421c11bc-384d-490d-a449-a67b328bd398    Invoke Error    {"errorType":"Exception","errorMessage":"The command exited with a non-zero status code: 2","stack":["#0 \/var\/task\/vendor\/bref\/bref\/src\/Runtime\/Invoker.php(29): Bref\\ConsoleRuntime\\Main::Bref\\ConsoleRuntime\\{closure}('test', Object(Bref\\Context\\Context))","#1 \/var\/task\/vendor\/bref\/bref\/src\/Runtime\/LambdaRuntime.php(89): Bref\\Runtime\\Invoker->invoke(Object(Closure), 'test', Object(Bref\\Context\\Context))","#2 \/var\/task\/vendor\/bref\/bref\/src\/ConsoleRuntime\/Main.php(63): Bref\\Runtime\\LambdaRuntime->processNextEvent(Object(Closure))","#3 \/opt\/bref\/bootstrap.php(17): Bref\\ConsoleRuntime\\Main::run()","#4 {main}"]}
END Duration: 282.93 ms Memory Used: 140 MB

Environment: linux, node 19.4.0, framework 3.30.1 (local) 3.29.0v (global), plugin 6.2.3, SDK 4.3.2
Credentials: Local, "default" profile
Docs:        docs.serverless.com
Support:     forum.serverless.com
Bugs:        github.com/serverless/serverless/issues
```

My serverless is as below:
```
service: laravel

provider:
    name: aws
    # The AWS region in which to deploy (us-east-1 is the default)
    region: ap-southeast-2
    # Environment variables
    environment:
        APP_ENV: stage # Or use ${sls:stage} if you want the environment to match the stage

package:
    # Files and directories to exclude from deployment
    patterns:
        - '!node_modules/**'
        - '!public/storage'
        - '!resources/assets/**'
        - '!storage/**'
        - '!tests/**'

functions:

    # This function runs the Laravel website/API
    web:
        handler: public/index.php
        runtime: php-81-fpm
        timeout: 28 # in seconds (API Gateway has a timeout of 29 seconds)
        events:
            - httpApi: '*'

    # This function lets us run artisan commands in Lambda
    artisan:
        handler: artisan
        runtime: php-81-console
        timeout: 720 # in seconds
        # Uncomment to also run the scheduler every minute
        #events:
        #    - schedule:
        #          rate: rate(1 minute)
        #          input: '"schedule:run"'

plugins:
  - ./vendor/bref/bref
  - serverless-lift
```
I tried running `serverless bref:cli --args="test"`
