### DISCUSSION TITLE
Unable to invoke console command via "aws lambda invoke"

### DISCUSSION THREAD

**Discussion by fbuchlak** [brefphp/bref#1580] [Support] [answered]
**Description:**

I'm trying to run symfony "bin/console" command like described in [documentation](https://bref.sh/docs/runtimes/console.html#usage-without-serverless-framework).

**How to reproduce:**
Running command
```sh
aws lambda invoke \
    --function-name PhpCliLambdaName \
    --region us-east-1 \
    --cli-binary-format raw-in-base64-out \
    --payload '"d:s:u --dump-sql"' \
    response.json
```
returns
```json
{
    "StatusCode": 200,
    "FunctionError": "Unhandled",
    "ExecutedVersion": "$LATEST"
}
```
and logs this
```
{
    "errorType": "TypeError",
    "errorMessage": "Bref\\Runtime\\FileHandlerLocator::{closure}(): Argument #1 ($context) must be of type array, string given, called in /var/task/vendor/bref/bref/src/Runtime/Invoker.php on line 29",
    "stack": [
        "#0 /var/task/vendor/bref/bref/src/Runtime/Invoker.php(29): Bref\\Runtime\\FileHandlerLocator->{closure}('d:s:u --dump-sq...', Object(Bref\\Context\\Context))",
        "#1 /var/task/vendor/bref/bref/src/Runtime/LambdaRuntime.php(89): Bref\\Runtime\\Invoker->invoke(Object(Closure), 'd:s:u --dump-sq...', Object(Bref\\Context\\Context))",
        "#2 /var/task/vendor/bref/bref/src/FunctionRuntime/Main.php(37): Bref\\Runtime\\LambdaRuntime->processNextEvent(Object(Closure))",
        "#3 /opt/bref/bootstrap.php(17): Bref\\FunctionRuntime\\Main::run()",
        "#4 {main}"
    ]
}
```

*CDK*

package.json
```json
"@bref.sh/constructs": "^1.0.0",
```
brefStack.ts
```ts
this.fpm = new PhpFpmFunction(this, 'PhpFpm', {
  code,
  handler: 'public/index.php',
  timeout: Duration.seconds(20),
  ...lambdaProps,
});

this.cli = new ConsoleFunction(this, 'PhpCli', {
  code,
  handler: 'bin/console',
  timeout: Duration.seconds(120),
  ...lambdaProps, // contains architecture, environment, role, securityGroups, vpc and vpcSubnets
});
```

*Symfony - code*

composer.json (symfony 6.3)
```json
"bref/bref": "^2.0",
"bref/symfony-bridge": "0.2.1",
"symfony/runtime": "6.3.*"
```
bin/console
```php
#!/usr/bin/env php
<?php

use App\Kernel;
use Symfony\Bundle\FrameworkBundle\Console\Application;

if (!is_file(dirname(__DIR__).'/vendor/autoload_runtime.php')) {
    throw new LogicException('Symfony Runtime is missing. Try running "composer require symfony/runtime".');
}

require_once dirname(__DIR__).'/vendor/autoload_runtime.php';

return function (array $context) {
    $kernel = new Kernel($context['APP_ENV'], (bool) $context['APP_DEBUG']);

    return new Application($kernel);
};
```

I've already tried to send payload as json object with APP_ENV, APP_DEBUG, but in this case I'm not able to figure out how should I provide command. 
Changing $context to string and creating Kernel with $_SERVER doesn't help either.

I was able to execute command with modified `bin/console` and payload `{"command":"d:s:u", "--force": true}`, but this time lambda could not return response and timed out (but schema did update).
```php
#!/usr/bin/env php
<?php

use App\Kernel;
use Symfony\Bundle\FrameworkBundle\Console\Application;

if (!is_file(dirname(__DIR__).'/vendor/autoload_runtime.php')) {
    throw new LogicException('Symfony Runtime is missing. Try running "composer require symfony/runtime".');
}

require_once dirname(__DIR__).'/vendor/autoload_runtime.php';

return function (array $context) {
    $kernel = new Kernel($_SERVER['APP_ENV'], (bool) $_SERVER['APP_DEBUG']);

    $application = new Application($kernel);

    $input = new Symfony\Component\Console\Input\ArrayInput($context);
    $output = new Symfony\Component\Console\Output\BufferedOutput();

    $application->run($input, $output);

    return new Symfony\Component\HttpFoundation\Response($output->fetch());
};
```

Looking at [ConsoleRuntime](https://github.com/brefphp/bref/blob/master/src/ConsoleRuntime/Main.php) I'm clearly missing "event". But how can I provide it?

**Comment by mnapoli** [comment]
It seems like you have modified `bin/console`: you shouldn't. You don't need to adapt this file for Lambda/Bref.

You should leave this file like on any standard Symfony installation, the "console" runtime takes care of executing it.

**Reply by fbuchlak** [reply]
Thank you for your reply, but actually the first provided snippet for `bin/console` is original source code (since symfony version 5.3). See [https://github.com/symfony/demo/blob/main/bin/console](https://github.com/symfony/demo/blob/main/bin/console)

Error occurs with clean installation of symfony skeleton application (6.3) and cdk construct `ConsoleFunction` from `@bref.sh/constructs`.

However looking at the stack trace now I don't see previously mentioned `ConsoleRuntime/Main.php` as it directly falls into `FunctionRuntime/Main.php` from main. Seems like there is problem with running correct runtime.

**Comment by fbuchlak** [comment]
Figured it out. The problem is that `ConsoleFunction` constructs creates 2 layers. Specifically function layer for php and console layer. As stated in `PhpFpmFunction` the php layer should be first, so console layer can override it. 
However lambda created by aws cdk had console layer created as first.

**Reply by mnapoli** [reply, marked as answer]
Ohhh thanks for investigating further! It seems related to https://github.com/brefphp/constructs/pull/4, which I can't reproduce for some reason! I need to figure this out 🤔

**Reply by matyo91** [reply]
Seem's that i'm having the same output when trying to run [https://bref.sh/docs/runtimes/function](https://bref.sh/docs/runtimes/function) sample in PHP with Symfony

Running command

```
./node_modules/.bin/serverless bref:local -f hello
```

serverless.yml

```
# Read the documentation at https://www.serverless.com/framework/docs/providers/aws/guide/serverless.yml/
service: symfony

provider:
    name: aws
    # The AWS region in which to deploy (us-east-1 is the default)
    region: us-east-1
    # The stage of the application, e.g. dev, production, staging… ('dev' is the default)
    stage: dev
    runtime: provided.al2
    environment:
        # Symfony environment variables
        APP_ENV: prod

plugins:
    - ./vendor/bref/bref

functions:
    hello:
        handler: my-function.php
        runtime: php-81-fpm
        events:
            - httpApi: '*'

    # This function runs the Symfony website/API
    web:
        handler: public/index.php
        timeout: 28 # in seconds (API Gateway has a timeout of 29 seconds)
        layers:
            - ${bref:layer.php-81-fpm}
        events:
            - httpApi: '*'
    # This function let us run console commands in Lambda
    console:
        handler: bin/console
        timeout: 120 # in seconds
        layers:
            - ${bref:layer.php-81} # PHP
            - ${bref:layer.console} # The "console" layer

package:
    patterns:
        # Excluded files and folders for deployment
        - '!assets/**'
        - '!node_modules/**'
        - '!public/build/**'
        - '!tests/**'
        - '!var/**'
        # If you want to include files and folders that are part of excluded folders,
        # add them at the end
        - 'var/cache/prod/**'
        - 'public/build/entrypoints.json'
        - 'public/build/manifest.json'
```

composer.json
```
"bref/bref": "2.1.4",
"bref/symfony-bridge": "0.2.2",
```

Return

```
START
TypeError: Bref\Runtime\FileHandlerLocator::{closure}(): Argument #1 ($event) must be of type array, null given, called in /var/www/darkwood.fr/darkwood.fr/vendor/bref/bref/src/Runtime/Invoker.php on line 29
Stack trace:
#0 /var/www/darkwood.fr/darkwood.fr/vendor/bref/bref/src/Runtime/Invoker.php(29): Bref\Runtime\FileHandlerLocator->{closure}(NULL, Object(Bref\Context\Context))
#1 /var/www/darkwood.fr/darkwood.fr/vendor/bref/bref/src/bref-local(52): Bref\Runtime\Invoker->invoke(Object(Closure), NULL, Object(Bref\Context\Context))
#2 {main}
```

This seem's to be related to this discussion.

Thanks for the discussion and hope this can bring more informations to make it reproductible.

**Reply by mnapoli** [reply]
@matyo91 this isn't related to the AWS CDK constructs. In your case you are invoking the following function:

```yaml
    hello:
        handler: my-function.php
        runtime: php-81-fpm
        events:
            - httpApi: '*'
```

like it's an event-driven function. But it's using the `php-81-fpm` runtime (it even has HTTP events), it's an HTTP Lambda, not a "function" Lambda. (this is why it expects an HTTP event, and it's causing an error)

If you want to invoke it locally you should look at this guide instead: https://bref.sh/docs/local-development

Or if you absolutely want to use `bref:local`, this section of the "bref:local" docs should help: https://bref.sh/docs/local-development/event-driven-functions#api-gateway-local-development (but it's advanced, I wouldn't do that).
