### DISCUSSION TITLE
Laravel on Lambda cannot access to S3

### DISCUSSION THREAD

**Discussion by gazzoy** [brefphp/bref#1591] [Support]
Hi, I'm a relatively new to bref, and having a problem on running a s3-event-driven Laravel app on AWS Lambda.

Basically, I want to achieve following things:
  1) Deploy Laravel on Lambda (by using bref, ofcourse)
  2) Invoke Lambda function by S3-ObjectCreated event, with environment variables.

Here's a snippet of what I'm trying to do. 

## serverless.yml
```
provider:
...
  runtime: php-81
...
  iam:
    role:
      statements:
        # Allow Lambda to read and write files in the S3 buckets
        - Effect: Allow
          Action: s3:*
          Resource:
            - !Sub '${MyBucket.Arn}'
            - !Sub '${MyBucket.Arn}/*'
...
functions: 
  my_functionl:
    handler: path/to/handler/app.php
    timeout: 30
    ephemeralStorageSize: 2048
    vpc:
      securityGroupIds:
        - !Ref LambdaSecurityGroup
      subnetIds:
        - !Ref PrivateSubnetA
        - !Ref PrivateSubnetC
    events:
      - s3:
          bucket: !Ref MyBucket
          event: s3:ObjectCreated:*
          rules:
            - suffix: my_invoker.txt
          existing: true
...
```

### path/to/handler.app.php
```
<?php
require '/path/to/vendor/autoload.php';

$app = '/path/to/bootstrap/app.php';

$kernel = $app->make(\Illuminate\Contracts\Console\Kernel::class);
$kernel->bootstrap();

return $app->make(\App\MyHandlers\Handler::class);
```

### App\MyHandlers\Handler.php
```
<?php
...
class MyHandler extends S3Handler
{
    public function handleS3(S3Event $event, Context $context): void
    {
        $s3Key = $event->getRecords()[0]->getObject()->getKey();
       $fileContent = Storage::disk('s3')->get($s3Key);
       \Log::debug('fileContent:' . $fileContent);
    }
}
```

I could deployed my code, and my code invoked by S3-ObjectCreated event successfully. But the problem is, when `App\MyHandlers\Handler.php` call `Storage::disk('s3')->get($s3Key);`, it throws an error like `Unable to read file from location... The AWS Access Key Id you provided does not exist in our records....`.

What do I miss?

Please let me know if you have any questions.
