### DISCUSSION TITLE
Dynamic bref-ssm

### DISCUSSION THREAD

**Discussion by cirolosapio** [brefphp/bref#1666] [Support] [answered]
as per doc https://bref.sh/docs/environment/variables#at-runtime 
we can use `bref-ssm:path` instead of `${ssm:path}` to fetch the secret values at runtime:

```yml
provider:
    environment:
        MY_PARAMETER: bref-ssm:/my-app/my-parameter
```

is it possbile to mix bref-ssm and other serverless variables?

Example:

```yml
service: badgeapp

provider:
    environment:
        APP_KEY: bref-ssm:/${self:service}/APP_KEY
```
