### DISCUSSION TITLE
have a problem with type static-website

### DISCUSSION THREAD

**Discussion by stloc** [brefphp/bref#1719] [Support]
Hello,

firts symfony (website) deploy OK
but after adding "landing" key for testing this option I have the access denied ?

```
constructs:
    landing:
        type: static-website
        path: static

    website:
        type: server-side-website
        assets:
            '/static/*': public/static
```

![image](https://github.com/brefphp/bref/assets/4832070/ba2ee30c-bdf9-4592-a0d2-dfcc701f4df4)

CREATE_FAILED: landingBucketPolicy0F0F1F6B (AWS::S3::BucketPolicy)
Resource handler returned message: "Access Denied (Service: S3, Status Code: 403, Request ID: Y2ADT52K86MVXE8M, Extended Request ID: wBAuzmL4WXguurBRxbJDMv5ybVP+PG2doHmVkB/OMbgxgh11vB807iFvg4y5eWiw/jUw1Th8eeU=)" (RequestToken: 416b0147-3904-a830-f5f4-738a979c74b9, HandlerErrorCode: AccessDenied)
