### DISCUSSION TITLE
Docker image for console command

### DISCUSSION THREAD

**Discussion by lektura0bandyta** [brefphp/bref#1807] [Support]
Hi, I've created custom docker image for CLI function like this.

Dockerfile
```
FROM bref/php-81-console:2

# Copy the source code in the image
COPY . /var/task

ENV APP_ENV=prod

# Configure the handler file (the entrypoint that receives all HTTP requests)
CMD ["bin/console"]
```

And set function in `serverless.yml`
```
provider:
    .....
    ecr:
        images:
            hello-world:
                path: ./                
functions:
    # This function let us run console commands in Lambda
    console:
        image:
            name: hello-world
        timeout: 120 # in seconds
```

But when I try to execute command using cli get message
`This command invokes the Lambda "console" function, but no function was found with the "console" layer`.

Can anyone help me set it correctly to use docker image when execute console command?
