### DISCUSSION TITLE
symfony 7 Unable to create the Doctrine Proxy directory "/tmp/cache/prod/doctrine/orm/Proxies".

### DISCUSSION THREAD

**Discussion by stloc** [brefphp/bref#1808] [Support]
Symfony 7.0.3
as soon as I deploy on the first call I get the error, on the second call it works! why ?

![image](https://github.com/brefphp/bref/assets/4832070/bc2dd65a-6908-477f-be49-8e07be3e86af)

**Comment by mnapoli** [comment]
Interesting 🤔 I have no idea why it would fail, the `/tmp` directory is made for this, first time I see this.

Is this a new app, or following an upgrade? Can you share more details?

**Reply by stloc** [reply]
new Symfony app

```
# Read the documentation at https://www.serverless.com/framework/docs/providers/aws/guide/serverless.yml/
service: messenger

provider:
    name: aws
    # The AWS region in which to deploy (us-east-1 is the default)
    region: eu-west-3
    # The stage of the application, e.g. dev, production, staging… ('dev' is the default)
    stage: dev
    runtime: provided.al2
    environment:
        # Symfony environment variables
        APP_ENV: prod
        APP_DEBUG: 1

plugins:
    - ./vendor/bref/bref
#    - ./vendor/bref/extra-php-extensions

functions:
    # This function runs the Symfony website/API
    web:
        handler: public/index.php
        timeout: 28 # in seconds (API Gateway has a timeout of 29 seconds)
        layers:
            - ${bref:layer.php-83-fpm}
#            - ${bref-extra:amqp-php-83} # <----- Example for AMQP layer
        events:
            - httpApi: '*'
    # This function let us run console commands in Lambda
    console:
        handler: bin/console
        timeout: 120 # in seconds
        layers:
            - ${bref:layer.php-83} # PHP
            - ${bref:layer.console} # The "console" layer

package:
    patterns:
        # Excluded files and folders for deployment
        - '!tests/**'
        - '!var/**'
        # If you want to include files and folders that are part of excluded folders,
        # add them at the end
        - 'var/cache/prod/**'
```

![image](https://github.com/brefphp/bref/assets/4832070/100e5e75-74f3-4347-9960-81e2d6744e43)


only second call OK : 
![image](https://github.com/brefphp/bref/assets/4832070/33ab3ead-3e51-4e09-9816-41c09aff18e3)

even disabling this in doctrine.yaml (I have not database) :
```
when@prod:
    doctrine:
        orm:
            auto_generate_proxy_classes: false
            proxy_dir: '%kernel.build_dir%/doctrine/orm/Proxies'
            query_cache_driver:
                type: pool
                pool: doctrine.system_cache_pool
            result_cache_driver:
                type: pool
                pool: doctrine.result_cache_pool
```
