### DISCUSSION TITLE
Laravel Bref - Scheduler Lambda not using Environment Variables

### DISCUSSION THREAD

**Discussion by CloudMarshall** [brefphp/bref#1818] [Support] [answered]
Hi, 

I have a laravel scheduler lambda and it does not seem to be picking up the environment variables that have been set. I can clearly see them in the AWS Console, and also if i make an artisan command to print all the environment variables, i can also see these outputted in the logs so i know they are set correctly

When the artisan scheduler runs it does not use the environment variables set. I have a artisan cmd to dump the database to S3, but it is not using the environment variables i have set for DB_HOST etc (again i can see these set in the console, and also get the lambda to print them out with my custom artisan cmd)

I have this exact same setup for another laravel project and it works absolutely fine - can anyone advise?

**Comment by semsphy** [comment]
can you drop your `serverless.yml` ? Normally, If you just follow this https://bref.sh/docs/use-cases/cron, it will work just fine.

**Reply by CloudMarshall** [reply]
```
service: ${self:custom.SERVICE_NAME.${opt:stage}}
provider:
  name: aws
  stackName: ${self:custom.NAME.${opt:stage}}-scheduler
  region: eu-west-1
  deploymentBucket:
    name: REDACTED
    serverSideEncryption: AES256
  stackTags:
    REDACTED:managedby: serverless
    REDACTED:environment: ${opt:stage}
    REDACTED:git: ${self:custom.GIT}
  tags:
    REDACTED:managedby: serverless
    REDACTED:environment: ${opt:stage}
    REDACTED:git: ${self:custom.GIT}
  iam:
    role:
      name: ${self:custom.NAME.${opt:stage}}-role
      statements:
        - Effect: Allow
          Resource:
            - >-
              arn:aws:s3:::REDACTED-${opt:stage}-${self:custom.NAME_PREFIX}-REDACTED
            - >-
              arn:aws:s3:::REDACTED-${opt:stage}-${self:custom.NAME_PREFIX}-REDACTED/*
          Action:
            - s3:GetObject
            - s3:ListObject
            - s3:PutObject
            - S3:ListBucket
  environment:
    APP_DEBUG: 'false'
    APP_ENV: local
    APP_LOG_LEVEL: debug
    APP_MULTI_TENANT: 'false'
    APP_NAME: dev REDACTED
    APP_TAG: dev
    APP_URL: REDACTED
    ASSET_URL: REDACTED
    AWS_BUCKET: REDACTED
    DB_DATABASE: REDACTED
    DB_HOST: REDACTED
    DB_PORT: '3306'
    DB_USERNAME: REDATED
    LOG_CHANNEL: stack
    MAIL_DRIVER: smtp
    MAIL_ENCRYPTION: 'null'
    MAIL_HOST: smtp.mailtrap.io
    MAIL_PORT: '2525'
    MAIL_TO_ADDRESS: REDACTED
    MAIL_USERNAME: REDACTED
    SESSION_DRIVER: database
    TASK_SCREENING_THRESHOLD_HIGH: '9'
    TASK_SCREENING_THRESHOLD_MEDIUM: '4'
    TEXT_MAH: MAH
    APP_KEY: ${self:custom.APP_KEY.APP_KEY}
    DB_PASSWORD: ${self:custom.DB_PASSWORD.password}
    LOG_SLACK_WEBHOOK_URL: ${self:custom.LOG_SLACK_WEBHOOK_URL.LOG_SLACK_WEBHOOK_URL}
    MAIL_PASSWORD: ${self:custom.MAIL_PASSWORD.MAIL_PASSWORD}
package:
  patterns:
    - '!node_modules/**'
    - '!public/storage'
    - '!resources/assets/**'
    - '!storage/**'
    - '!tests/**'
    - '!.env'
    - '!.github'
    - '!public'
    - '!docker'
functions:
  scheduler:
    name: ${self:custom.NAME.${opt:stage}}-scheduler
    vpc:
      securityGroupIds:
        - ${self:custom.SG_ID}
      subnetIds: ${self:custom.SUBNET_IDS.${opt:stage}}
    handler: artisan
    layers:
      - arn:aws:lambda:eu-west-1:337241785228:layer:mysqldump:1
    runtime: php-83-console
    timeout: 720
    events:
      - schedule:
          rate: ${self:custom.CRON.${opt:stage}}
          input: '"schedule:run"'
plugins:
  - ./vendor/bref/bref
custom:
  ORG: REDACTED
  ENV: ${opt:stage}
  NAME_PREFIX: REDACTED
  GIT: REDACTED
  SG_ID: >-
    ${ssm:/${self:custom.ORG}-${opt:stage}-${self:custom.NAME_PREFIX}/${param:client}/lambda-scheduler-sg-id}
  SERVICE_NAME:
    dev: ${self:custom.ORG}-${opt:stage}-${self:custom.NAME_PREFIX}
    stg: ${self:custom.ORG}-${opt:stage}-${self:custom.NAME_PREFIX}-${env:CLIENT}
    prod: ${self:custom.ORG}-${opt:stage}-${self:custom.NAME_PREFIX}-${env:CLIENT}
  NAME:
    dev: ${self:custom.ORG}-${opt:stage}-${self:custom.NAME_PREFIX}
    stg: ${self:custom.ORG}-${opt:stage}-${self:custom.NAME_PREFIX}-${param:client}
    prod: ${self:custom.ORG}-${opt:stage}-${self:custom.NAME_PREFIX}-${param:client}
  CRON:
    dev: cron(0 7-19 ? * MON-FRI *)
    stg: cron(0 7-19 ? * MON-FRI *)
    prod: cron(0 * ? * * *)
  VPC_ID:
    dev: REDACTED
    stg: REDACTED
    prod: REDACTED
  SUBNET_IDS:
    dev:
      - REDACTED
      - REDACTED
      - REDACTED
    stg:
      - REDACTED
      - REDACTED
      - REDACTED
    prod:
      - REDACTED
      - REDACTED
      - REDACTED
  APP_KEY: ${ssm:/aws/reference/secretsmanager/REDACTED}
  DB_PASSWORD: >-
    ${ssm:/aws/reference/secretsmanager/REDACTED}
  LOG_SLACK_WEBHOOK_URL: ${ssm:/aws/reference/secretsmanager/REDACTED}
  MAIL_PASSWORD: ${ssm:/aws/reference/secretsmanager/REDACTED}
```

**Comment by CloudMarshall** [comment]
```
service: ${self:custom.SERVICE_NAME.${opt:stage}}
provider:
  name: aws
  stackName: ${self:custom.NAME.${opt:stage}}-scheduler
  region: eu-west-1
  deploymentBucket:
    name: REDACTED
    serverSideEncryption: AES256
  stackTags:
    REDACTED:managedby: serverless
    REDACTED:environment: ${opt:stage}
    REDACTED:git: ${self:custom.GIT}
  tags:
    REDACTED:managedby: serverless
    REDACTED:environment: ${opt:stage}
    REDACTED:git: ${self:custom.GIT}
  iam:
    role:
      name: ${self:custom.NAME.${opt:stage}}-role
      statements:
        - Effect: Allow
          Resource:
            - >-
              arn:aws:s3:::REDACTED-${opt:stage}-${self:custom.NAME_PREFIX}-REDACTED
            - >-
              arn:aws:s3:::REDACTED-${opt:stage}-${self:custom.NAME_PREFIX}-REDACTED/*
          Action:
            - s3:GetObject
            - s3:ListObject
            - s3:PutObject
            - S3:ListBucket
  environment:
    APP_DEBUG: 'false'
    APP_ENV: local
    APP_LOG_LEVEL: debug
    APP_MULTI_TENANT: 'false'
    APP_NAME: dev REDACTED
    APP_TAG: dev
    APP_URL: REDACTED
    ASSET_URL: REDACTED
    AWS_BUCKET: REDACTED
    DB_DATABASE: REDACTED
    DB_HOST: REDACTED
    DB_PORT: '3306'
    DB_USERNAME: REDATED
    LOG_CHANNEL: stack
    MAIL_DRIVER: smtp
    MAIL_ENCRYPTION: 'null'
    MAIL_HOST: smtp.mailtrap.io
    MAIL_PORT: '2525'
    MAIL_TO_ADDRESS: REDACTED
    MAIL_USERNAME: REDACTED
    SESSION_DRIVER: database
    TASK_SCREENING_THRESHOLD_HIGH: '9'
    TASK_SCREENING_THRESHOLD_MEDIUM: '4'
    TEXT_MAH: MAH
    APP_KEY: ${self:custom.APP_KEY.APP_KEY}
    DB_PASSWORD: ${self:custom.DB_PASSWORD.password}
    LOG_SLACK_WEBHOOK_URL: ${self:custom.LOG_SLACK_WEBHOOK_URL.LOG_SLACK_WEBHOOK_URL}
    MAIL_PASSWORD: ${self:custom.MAIL_PASSWORD.MAIL_PASSWORD}
package:
  patterns:
    - '!node_modules/**'
    - '!public/storage'
    - '!resources/assets/**'
    - '!storage/**'
    - '!tests/**'
    - '!.env'
    - '!.github'
    - '!public'
    - '!docker'
functions:
  scheduler:
    name: ${self:custom.NAME.${opt:stage}}-scheduler
    vpc:
      securityGroupIds:
        - ${self:custom.SG_ID}
      subnetIds: ${self:custom.SUBNET_IDS.${opt:stage}}
    handler: artisan
    layers:
      - arn:aws:lambda:eu-west-1:337241785228:layer:mysqldump:1
    runtime: php-83-console
    timeout: 720
    events:
      - schedule:
          rate: ${self:custom.CRON.${opt:stage}}
          input: '"schedule:run"'
plugins:
  - ./vendor/bref/bref
custom:
  ORG: REDACTED
  ENV: ${opt:stage}
  NAME_PREFIX: REDACTED
  GIT: REDACTED
  SG_ID: >-
    ${ssm:/${self:custom.ORG}-${opt:stage}-${self:custom.NAME_PREFIX}/${param:client}/lambda-scheduler-sg-id}
  SERVICE_NAME:
    dev: ${self:custom.ORG}-${opt:stage}-${self:custom.NAME_PREFIX}
    stg: ${self:custom.ORG}-${opt:stage}-${self:custom.NAME_PREFIX}-${env:CLIENT}
    prod: ${self:custom.ORG}-${opt:stage}-${self:custom.NAME_PREFIX}-${env:CLIENT}
  NAME:
    dev: ${self:custom.ORG}-${opt:stage}-${self:custom.NAME_PREFIX}
    stg: ${self:custom.ORG}-${opt:stage}-${self:custom.NAME_PREFIX}-${param:client}
    prod: ${self:custom.ORG}-${opt:stage}-${self:custom.NAME_PREFIX}-${param:client}
  CRON:
    dev: cron(0 7-19 ? * MON-FRI *)
    stg: cron(0 7-19 ? * MON-FRI *)
    prod: cron(0 * ? * * *)
  VPC_ID:
    dev: REDACTED
    stg: REDACTED
    prod: REDACTED
  SUBNET_IDS:
    dev:
      - REDACTED
      - REDACTED
      - REDACTED
    stg:
      - REDACTED
      - REDACTED
      - REDACTED
    prod:
      - REDACTED
      - REDACTED
      - REDACTED
  APP_KEY: ${ssm:/aws/reference/secretsmanager/REDACTED}
  DB_PASSWORD: >-
    ${ssm:/aws/reference/secretsmanager/REDACTED}
  LOG_SLACK_WEBHOOK_URL: ${ssm:/aws/reference/secretsmanager/REDACTED}
  MAIL_PASSWORD: ${ssm:/aws/reference/secretsmanager/REDACTED}
```

**Comment by emaadali** [comment]
Do you see the environment variables in the "scheduler" Lambda configuration in the AWS console?

**Reply by CloudMarshall** [reply]
Yes see the environment variables present, and I can generate a custom artisan CMD to print all env variables, and when I run this CMD in the lambda console via the test mechanism, in the logs it prints all the env vars correctly (same as the ones in the lambda console under environment variables)

**Reply by emaadali** [reply]
Can you send the command you’re using to dump the database into S3?

**Reply by CloudMarshall** [reply]
If i use the cmd to dump the databse to s3 (backup:run), it reverts to the default values in the laravel config, instead of picking up the preferred environment variables. 

```
        'mysql' => [
            'driver' => 'mysql',
            'host' => env('DB_HOST', '127.0.0.1'),
            'port' => env('DB_PORT', '3306'),
            'database' => env('DB_DATABASE', 'forge'),
            'username' => env('DB_USERNAME', 'forge'),
            'password' => env('DB_PASSWORD', ''),
            'unix_socket' => env('DB_SOCKET', ''),
            'charset' => 'utf8mb4',
            'collation' => 'utf8mb4_unicode_ci',
            'prefix' => 'hf_',
            'strict' => false,
            'engine' => null,
        ],

```

**Reply by emaadali** [reply]
You're using the Spatie backup package with Laravel, right?

How do you know that the `backup:run` command uses Laravel's default env values instead of the correct ones? Are you just assuming that because the backup doesn't succeed?

Because you can log the correct environment variables via a custom command, I don't see any reason why the `schedule` event wouldn't use the correct environment variables either. The Lambda trigger does not set the environment variables (i.e., environment variables are not handled differently if the event in `serverless.yml` is `schedule` vs. `http` vs. `sqs`, etc). Also, bref isn't responsible for reading environment variables from the Lambda container. AWS adds the environment variables to the Lambda container in the same way you can add environment variables to a server or your computer - bref has no role in that process. Your Laravel configuration files read the environment variables from the Lambda container using the `env` function (for example, 'host' => **env(**'DB_HOST'**)**).

Bref caches your Laravel configuration. But, it doesn't handle the caching process differently for a `schedule` event than for any other event such as `http` or `sqs`.

My guess is that Lambda is using the correct environment variables. I think there are three potential issues:

1. The Lambda cannot connect to the database due to incorrect variables (wrong user/pass/host).
2. The Lambda cannot connect to the database due to a security group misconfiguration.
3. The Lambda does not have IAM permission to write to S3.

Here is what I would do:

### 1. Disable the Bref config cache

I would add `BREF_LARAVEL_CACHE_CONFIG: 0` to `provider.environment` in your `serverless.yml` to prevent Bref from caching the Laravel configuration. I don't think Bref's caching is causing any issues, but just to be safe, you should disable it.

### 2. Add a test command

Create the following command at `app/Console/Commands/TestBackup.php`.

This command will log the relevant environment variables and test the connection to your database and S3.

```php
<?php

namespace App\Console\Commands;

use Illuminate\Console\Command;
use Illuminate\Support\Facades\Storage;

class TestBackup extends Command
{
    /**
     * The name and signature of the console command.
     *
     * @var string
     */
    protected $signature = 'backup:test';

    /**
     * The console command description.
     *
     * @var string
     */
    protected $description = 'Test connection to the database and S3 bucket';

    /**
     * Execute the console command.
     */
    public function handle()
    {
        $this->showEnvironmentVariables();
        $this->testDatabaseConnection();
        $this->testS3BucketAccess();
    }

    private function showEnvironmentVariables(): void
    {
        $envs = [
            'DB_CONNECTION' => env('DB_CONNECTION'),
            'DB_HOST' => env('DB_HOST'),
            'DB_PORT' => env('DB_PORT'),
            'DB_DATABASE' => env('DB_DATABASE'),
            'DB_USERNAME' => env('DB_USERNAME'),
            'DB_PASSWORD_LENGTH' => strlen(env('DB_PASSWORD')),
            'AWS_BUCKET' => env('AWS_BUCKET'),
            'AWS_DEFAULT_REGION' => env('AWS_DEFAULT_REGION'),
        ];

        $this->table(['Key', 'Value'], array_map(function ($key, $value) {
            return [$key, $value];
        }, array_keys($envs), $envs));
    }

    private function testDatabaseConnection(): void
    {
        try {
            \DB::connection()->getPdo();
            $this->info('Database connection is established successfully.');
        } catch (\Exception $e) {
            $this->error('Failed to connect to the database. Error: '.$e->getMessage());
        }
    }

    private function testS3BucketAccess(): void
    {
        $bucket = env('AWS_BUCKET');
        $file = 'test-file-'.time().'.txt';
        $content = 'This is a test file for checking write permissions.';

        try {
            Storage::disk('s3')->put($file, $content);
            $this->info('Successfully wrote to the S3 bucket: '.$bucket);

            // Check if file can be read
            if (Storage::disk('s3')->exists($file)) {
                $this->info('Successfully read from the S3 bucket.');
                Storage::disk('s3')->delete($file); // Cleanup
            } else {
                $this->error('Failed to read the test file from the S3 bucket.');
            }
        } catch (\Exception $e) {
            $this->error('S3 bucket access failed. Error: '.$e->getMessage());
        }
    }
}
```

### 3. Make three changes to your `serverless.yml`:

a. Fix your `schedule` event rate.

You should run `schedule:run` every minute. Instead of defining the schedule frequency via cron in `serverless.yml`, use the built-in Laravel task scheduler (see step 4 for an example).

```yaml
# serverless.yml
events:
- schedule:
    description: Running the Laravel Scheduler (schedule:run) each minute
    # rate: ${self:custom.CRON.${opt:stage}}
    rate: rate(1 minute)
    input: '"schedule:run"'
```

b. Remove `custom.CRON` from `serverless.yml` because it is no longer needed.

c. Change `provider.environment.APP_ENV` from `APP_ENV: local` to `APP_ENV: ${opt:stage}`. This is needed for your schedule frequency with the Laravel task scheduler.

### 4. Add the `backup:test` command to your schedule:

**Laravel 11**
```php
// routes/console.php

use Illuminate\Support\Facades\Schedule;

Schedule::command('backup:test')->everyMinute();

// Configure Spatie's backup package to your needs
Schedule::command('backup:clean')->daily()->at('01:00');
Schedule::command('backup:run')->daily()->at('01:30');

// Other scheduled commands...
// Since we are running the schedule every minute now, you need to add schedule frequency constraints to your existing commands:
Schedule::command('existing-command-1')
    ->hourlyAt(0)->between('7:00', '19:00')->weekdays()
    ->environment(['dev', 'stg']);

Schedule::command('existing-command-1')
    ->hourlyAt(30)
    ->environment('prod');
```

**Laravel 10**
```php
// app/Console/Kernel.php

use Illuminate\Console\Scheduling\Schedule;

protected function schedule(Schedule $schedule)
{
    $schedule->command('backup:test')->everyMinute();

    // Configure Spatie's backup package to your needs
    $schedule->command('backup:clean')->daily()->at('01:00');
    $schedule->command('backup:run')->daily()->at('01:30');

    // Other scheduled commands...
    // Since we are running the schedule every minute now, you need to add schedule frequency constraints to your existing commands:
    $schedule->command('existing-command-1')
        ->hourlyAt(0)->between('7:00', '19:00')->weekdays()
        ->environment(['dev', 'stg']);

    $schedule->command('existing-command-1')
        ->hourlyAt(30)
        ->environment('prod');
}
```

### 5. Check CloudWatch logs for the command output

The `backup:test` command will print out a table that looks something like this:

```
+--------------------+---------------------+
| Key                | Value               |
+--------------------+---------------------+
| DB_CONNECTION      | mysql               |
| DB_HOST            | xxxxxxxxx           |
| DB_PORT            | xxxx                |
| DB_DATABASE        | xxxxxxxx            |
| DB_USERNAME        | xxxx                |
| DB_PASSWORD_LENGTH | x                   |
| AWS_BUCKET         | xxxxxxxxxxxxxxxxxxx |
| AWS_DEFAULT_REGION | xxxxxxxxx           |
+--------------------+---------------------+
Database connection is established successfully.
Successfully wrote to the S3 bucket: xxxxxxxxxxxxxxxxxxx
Successfully read from the S3 bucket.
```

a. Make sure the environment variables in the table are all correct. This is how we will know whether the schedule uses Laravel's default env values or the correct ones.

b. If the command fails due to a timeout, Lambda cannot connect to the database, likely due to a security group issue.

c. If the command fails with the error message "Failed to connect to the database," you should ensure that the DB env variables are correct. Your username, password, or host may be incorrect.

d. If the command fails with this error message "S3 bucket access failed. Error: xxx", check your IAM permissions and bucket policy to ensure the Lambda can write to the bucket.
