### DISCUSSION TITLE
TypeError: Cannot read properties of undefined when running 'serverless bref -f hello' command

### DISCUSSION THREAD

**Discussion by ZhuoWei93** [brefphp/bref#1823] [Support] [answered]
Hey, hello, I'm a beginner. I'm trying to set up a serverless service locally using Laravel + Bref, but I'm encountering an issue:

When I execute `serverless bref:local -f hello`, I get the following error:

```
Environment: linux, node 18.20.3, framework 3.39.0, plugin 7.2.3, SDK 4.5.1
Docs:        docs.serverless.com
Support:     forum.serverless.com
Bugs:        github.com/serverless/serverless/issues

Error:
TypeError: Cannot read properties of undefined (reading 'enum')
    at new ServerlessPlugin (/mnt/d/laragon/www/ds_serviceless/vendor/bref/bref/index.js:54:76)
    at PluginManager.addPlugin (/usr/local/lib/node_modules/serverless/lib/classes/plugin-manager.js:91:28)
    at /usr/local/lib/node_modules/serverless/lib/classes/plugin-manager.js:137:69
    at Array.forEach (<anonymous>)
    at PluginManager.loadAllPlugins (/usr/local/lib/node_modules/serverless/lib/classes/plugin-manager.js:137:44)
    at async Serverless.init (/usr/local/lib/node_modules/serverless/lib/serverless.js:146:5)
    at async /usr/local/lib/node_modules/serverless/scripts/serverless.js:601:7
```

serverless.yml：

```
service: serviceless-test

provider:
  name: test
  # The AWS region in which to deploy (us-east-1 is the default)
  region: ap-southeast-1
  environment:
    APP_ENV: production
    APP_DEBUG: true # set to false when moving to production
    APP_KEY: 'base64:/EStlF5sExBpWdQ3eB/h+F2zzKGDc5bvDzwe0KD8ZPg='

package:
  # Directories to exclude from deployment
  patterns:
    - '!node_modules/**'
    - '!public/storage'
    - '!resources/assets/**'
    - '!storage/**'
    - '!tests/**'
    - '!.env'

functions:
  hello:
    handler: Test\handler

plugins:
  # We need to include the Bref plugin
  - ./vendor/bref/bref
```

**Comment by mnapoli** [comment]
Hi! That is very weird, I cannot reproduce this locally. I also upgraded to the latest version (same as you) but things work fine 🤔

The only difference I can see is that I use Node 21 instead of Node 18, but that shouldn't be a problem here.

How did you install `serverless`? Via NPM?

**Reply by ZhuoWei93** [reply, marked as answer]
Thank you for your reply, I made a stupid mistake

```
provider:
  name: test

provider:
  name: aws
```
