### DISCUSSION TITLE
Debug the docker container? Figure out where to put files?

### DISCUSSION THREAD

**Discussion by RulerOf** [brefphp/bref#1871] [Support] [answered]
I'm trying to determine if I can use Bref for a codeigniter 3 app I have.

I wanted to get things up and running quickly, so I looked up the [local dev](https://bref.sh/docs/local-development) instructions and set up the docker container:
```yaml
services:
  app:
    image: bref/arm-php-80-fpm-dev:2
    volumes:
      - ./app:/var/task
    ports:
      - 8000:8080
    environment:
      HANDLER: index.php
      # Assets will be served from this directory
      DOCUMENT_ROOT: resources
```
As implied by the volume mount, the root of the codeigniter project is in the `app` subfolder, which is laid out like this:
```
╰─❯ tree --dirsfirst -L 1 app
app
├── application
├── captcha
├── login
├── resources
├── shared
├── system
├── testcxml
├── vendor
├── composer.json
├── composer.lock
├── index.php
├── phpinfo.php
└── serverless.yml
```

I `docker compose up --build` and the container comes up. I can exec into the container and see my `index.php` located at `/var/task/index.php`, but `localhost:8000` only returns `404 page not found`.

There's no logs of any kind in the app container after the thing comes up, either:
```
app-1       | 16 Oct 2024 05:25:32,060 [INFO] (rapid) exec '/var/runtime/bootstrap' (cwd=/var/task, handler=)
mysql-1     | 2024-10-16 05:25:32+00:00 [Note] [Entrypoint]: Entrypoint script for MySQL Server 8.4.1-1.el9 started.
<snip>
app-1       | ⚡️ Server is running at http://localhost:8000
```

I deployed the app to AWS with `serverless` and it does seem to work. Am I doing something wrong with the docker container?
