### DISCUSSION TITLE
Timeout when dispatching a job to SQS queue using Bref.sh with Laravel 11

### DISCUSSION THREAD

**Discussion by lepresk** [brefphp/bref#1876] [Support] [answered]
I'm currently deploying my Laravel application using Bref. All the resources are deployed successfully, including my SQS queue, but when I dispatch a job, I encounter a timeout error. 

Here’s my setup and configuration:

### Serverless Configuration

```yaml
service: epayment

provider:
    name: aws
    region: us-east-1
    environment:
        APP_ENV: local
        APP_DEBUG: true
        APP_KEY: ***

        QUEUE_CONNECTION: sqs
        SQS_QUEUE: ${construct:jobs.queueUrl}

package:
    patterns:
        - '!node_modules/**'
        - '!public/storage'
        - '!resources/assets/**'
        - '!storage/**'
        - '!tests/**'

functions:
    web:
        handler: public/index.php
        runtime: php-83-fpm
        timeout: 28
        events:
            - httpApi: '*'
        vpc:
            securityGroupIds:
                - sg-xxxxxxx
            subnetIds:
                - subnet-xxxxxxx
                - subnet-xxxxxxx

    artisan:
        handler: artisan
        runtime: php-83-console
        timeout: 720
        vpc:
            securityGroupIds:
                - sg-xxxxxxx
            subnetIds:
                - subnet-xxxxxxx
                - subnet-xxxxxxx

constructs:
    jobs:
        type: queue
        worker:
            handler: Bref\LaravelBridge\Queue\QueueHandler
            runtime: php-83
            timeout: 60

plugins:
  - ./vendor/bref/bref
  - serverless-lift
```

### Route for Testing

```php
Route::get('/', function() {
    dispatch(function() {
        info('This is in the queue');
    });

    return view('welcome');
});
```

### Environment Details

- **PHP version:** 8.3
- **Laravel version:** 11.x
- **Bref:** 2.3
- **Bref laravel bridge:** 2.4

**Problem:**  
When hitting the route, the job is not dispatched. It results in a timeout, and the job isn't executed.

Any insights or guidance would be greatly appreciated! 😊
