### DISCUSSION TITLE
Multiple SQS queues with different instance configuration

### DISCUSSION THREAD

**Discussion by hackel** [brefphp/bref#1970] [Support]
I would like to setup multiple Laravel queues, one for regular jobs, and one "highmem" queue for jobs that require a lot of memory.  e.g. `ProcessPodcast::dispatch()->onConnection('sqs')->onQueue('highmem');`  How would I go about setting this up?  Do I just create a separate construct, and how do I specify which queue it handles?
Something like:
```yaml
constructs:
  default:
    type: queue
    worker:
      handler: Bref\LaravelBridge\Queue\QueueHandler
      runtime: php-83
      timeout: 60 # seconds
      memorySize: 512 # MB
      queue: default
  highmem:
    type: queue
    worker:
      handler: Bref\LaravelBridge\Queue\QueueHandler
      runtime: php-83
      timeout: 600 # seconds
      memorySize: 8192 # MB
      queue: highmem
```
Thank you!

Edit: FYI I'm deploying a Laravel app, maybe I should have posted in the other repo.
