### DISCUSSION TITLE
Fatal Error - Failed opening required `/var/task/vendor/composer/../symfony/polyfill-php80/bootstrap.php`

### DISCUSSION THREAD

**Discussion by bradleyess** [brefphp/bref#864] [Support]
I have been able to "successfully" deploy a Symfony application of ours using Serverless x Bref. The application shows this error when accessing via web:

```json
{"message":"Internal Server Error"}
```

Looking into Cloudwatch Logs it appears this would be the cause:

```sh
Fatal error: require(): Failed opening required '/var/task/vendor/composer/../symfony/polyfill-php80/bootstrap.php' (include_path='.:/opt/bref/lib/php') in /var/task/vendor/composer/autoload_real.php on line 71
```

I have looked into the deployment artifact and can confirm the file it is looking for exists...

Here is the `serverless.yml` file:

```yml

service: bref-demo-symfony
plugins:
    - ./app/vendor/bref/bref

provider:
    name: aws
    region: ap-southeast-2
    runtime: provided.al2
    lambdaHashingVersion: 20201221
    environment:
        # todo - set via SM/SSM
        APP_ENV: prod
        LOG_LEVEL: info
        ENV_HOSTNAME: monolith.linktree.test
        SYMFONY_ENV: dev
        STAGE: local
        RELEASE: local

functions:
    # todo - Provide working example of message consumer.
    # todo - Provide working example of standalone PHP Lambda function.

    monolith:
        handler: app/public/index.php
        timeout: 28 # in seconds (API Gateway has a timeout of 29 seconds)
        layers:
            - ${bref:layer.php-74-fpm}
        events:
            - httpApi: '*'

    console:
        handler: app/bin/console
        timeout: 120 # in seconds
        layers:
            - ${bref:layer.php-74} # PHP
            - ${bref:layer.console} # The "console" layer

package:
    individually: true
    excludeDevDependencies: false
    exclude:
        - 'node_modules/**'
        - 'app/node_modules/**'
        - 'app/var/**'
        - 'app/public/assets/**'
        - 'server/**'
        - 'scripts/**'
        - 'docker/**'
        - 'codedeploy/**'
        # Include doesn't work nicely.
        - '!app/public/config.php'
        - '!app/public/index.php'
        - '!app/bin/**'
        - '!app/src/**'
        - '!app/templates/**'
        - '!app/translations/**'
        - '!app/vendor/**'

```
