### DISCUSSION TITLE
artisan migrate gives error "sh: mysql: command not found"

### DISCUSSION THREAD

**Discussion by eAvio** [brefphp/bref#879] [Support]
Hi,

We are trying to deploy or laravel nova app with bref. 
Deployment goes well, but when trying to run artisan migrate we get strange error:
`sh: mysql: command not found`

We run migration with:
` vendor/bin/bref cli --region eu-central-1 radioPool-dev-artisan -- migrate --force`

We are using Laravel v8.27.0 (PHP v8.0.1).

Any help would be appreciated. 

serverless.yml
```
service: radiopoll

provider:
    name: aws
    # The AWS region in which to deploy (us-east-1 is the default)
    region: eu-central-1
    # The stage of the application, e.g. dev, production, staging… ('dev' is the default)
    stage: dev
    runtime: provided.al2

package:
    # Directories to exclude from deployment
    exclude:
        - node_modules/**
        - public/storage
        - resources/assets/**
        - storage/**
        - tests/**

functions:
    # This function runs the Laravel website/API
    web:
        handler: public/index.php
        timeout: 28 # in seconds (API Gateway has a timeout of 29 seconds)
        layers:
            - ${bref:layer.php-80-fpm}
        events:
            -   httpApi: '*'
        vpc:
          securityGroupIds:
            - sg-xxxx
          subnetIds:
            - subnet-xxxx
            - subnet-xxxx
            - subnet-xxxx
    # This function lets us run artisan commands in Lambda
    artisan:
        handler: artisan
        timeout: 120 # in seconds
        layers:
            - ${bref:layer.php-80} # PHP
            - ${bref:layer.console} # The "console" layer
        vpc:
          securityGroupIds:
            - sg-xxxx
          subnetIds:
            - subnet-xxxx
            - subnet-xxxx
            - subnet-xxxx

plugins:
    # We need to include the Bref plugin
    - ./vendor/bref/bref
```
