### DISCUSSION TITLE
First Steps: Internal Server Error 500

### DISCUSSION THREAD

**Discussion by kavatari** [brefphp/bref#933] [Support] [answered]
**Description:**

Following this guide: https://bref.sh/docs/first-steps.html 
I want to run the simple "Hello World" example. After deploying the app to AWS Lambda and calling the url, I receive the error 500 with the message:  `{"message":"Internal Server Error"}`

**How to reproduce:**
Installed bref version (using composer): 1.2.6
```
composer require bref/bref
vendor/bin/bref init
serverless deploy
``` 
**serverless.yml**
```
service: app
provider:
  name: aws
  region: us-east-1
  runtime: provided.al2
plugins:
  - ./vendor/bref/bref
functions:
  api:
    handler: index.php
    description: ''
    timeout: 28 # in seconds (API Gateway has a timeout of 29 seconds)
    layers:
      - ${bref:layer.php-74-fpm}
    events:
      - httpApi: '*'
# Exclude files from deployment
package:
  exclude:
    - 'node_modules/**'
    - 'tests/**'
 ```
Saw this closed issue: https://github.com/brefphp/bref/issues/390 but it doesn't help.

**Comment by t-richard** [comment, marked as answer]
@kavatari this is most likely because you use php 8.0 locally and the serverless.yml is using the 7.4 layer `${bref:layer.php-74-fpm}`. Replace it by the 8.0 layer `${bref:layer.php-80-fpm}`

When using Bref (and Lambda in general), you can see the logs in Cloudwatch > Log groups and you should see the error.

Note that if you need support, you can use the Github discussion or join the Slack (see https://bref.sh/docs/community.html)

**Comment by mnapoli** [comment]
Hey, really sorry about the poor experience here.

To find where the error is coming from, please run:

```
serverless logs -f api
```

That will show the logs of the `api` function. If there are no logs, open up the web page to trigger an "Internal error", and run the command again after a few seconds.

FYI that kind of error is a generic "server error", that means there's an error in the PHP code for some reason.

**Comment by kavatari** [comment]
@mnapoli @t-richard just awesome guys, thanks for the quick response. Both answers were really helpful. I am new to AWS, so the hint using CloudWatch is awesome. Using "serverless logs" command is also a great a fast forward approach to view the logs. 
Fixed the error using the php-80-fpm layer. 
Maybe it would make any sense to put this information also into the documentation for bref? 
Thanks once again!

**Reply by t-richard** [reply]
@kavatari you're welcome! 

I opened a PR to address this issue https://github.com/brefphp/bref/pull/934

**Comment by tonychuuy** [comment]
I having the same issue, unfortunately setting the layer to php-80-fpm did not help.

This is the error I'm getting in cloudwatch:

```
2021-05-17T18:13:37.301Z 255abdd1-257b-48e0-b9b7-cd67ebb2fc2c Task timed out after 28.03 seconds
PHP-FPM seems to be running already. This might be because Lambda stopped the bootstrap process but didn't leave us an opportunity to stop PHP-FPM (did Lambda timeout?). Stopping PHP-FPM now to restart from a blank slate.
Error while starting PHP-FPM
Fatal error: Exception: Timeout while waiting for PHP-FPM to stop in /var/task/vendor/bref/bref/src/Event/Http/FpmHandler.php:273
Stack trace:
#0 /var/task/vendor/bref/bref/src/Event/Http/FpmHandler.php(256): Bref\Event\Http\FpmHandler->waitUntilStopped()
#1 /var/task/vendor/bref/bref/src/Event/Http/FpmHandler.php(66): Bref\Event\Http\FpmHandler->killExistingFpm()
#2 /opt/bootstrap(37): Bref\Event\Http\FpmHandler->start()
#3 {main}

```

serverless.yml

```
service: app

provider:
    name: aws
    region: us-west-2
    runtime: provided.al2
    stackName: ${self:service}

functions:
    # This function runs the Laravel website/API
    web_dev:
        handler: public/index.php
        timeout: 28
        name: ${self:service}-dev-web
        layers:
            - ${bref:layer.php-80-fpm}
        events:
           -   httpApi: '*'
           -   schedule:
                     rate: rate(5 minutes)
                    input:
                         warmer: true
        environment:
            APP_ENV: staging
            APP_KEY: ${env:APP_KEY}
plugins:
    - ./vendor/bref/bref
```
