### DISCUSSION TITLE
How can I setup bref to store data in a bucket or in a ElastiCache/memcache

### DISCUSSION THREAD

**Discussion by mkochstroer** [brefphp/bref#935] [Ideas]
Is there a tutorial how to setup bref so that the app can store data in a ElastiCache? Or in an S3 bucket?

**Comment by t-richard** [comment]
@mkochstroer that is not handled by Bref (nor should be handled by Bref IMHO).

If you need to store data, then your own code should handle it.

Here are some ideas though : 
- to interact with a S3 you could use Flysystem which is an abstraction layer for interacting with "Filesystems" (S3, local filesystem, FTP, etc) https://flysystem.thephpleague.com/v2/docs/adapter/async-aws-s3/ they also have bridges for Symfony and Laravel
- to store in Elasticache you should take a look at either low-level libraries like ext-redis or Predis or use an Abstraction like the Symfony cache component https://symfony.com/doc/current/components/cache/adapters/redis_adapter.html

Also Bref integrates with Serverless Framework so you can write Cloudformation templates to create the S3 buckets or Elasticache clusters. For example

```yaml
service: bref-s3-app

provider:
  name: aws
  runtime: provided.al2
  environment:
    APP_ENV: prod
    S3_UPLOAD_BUCKET_NAME: !Ref UploadBucket

functions:
  website:
        handler: public/index.php
        timeout: 28 # in seconds (API Gateway has a timeout of 29 seconds)
        layers:
            - ${bref:layer.php-80-fpm}
        events:
            - httpApi: '*'
plugins:
    - ./vendor/bref/bref

resources:
  Resources:
    UploadBucket:
      Type: "AWS::S3::Bucket"
      Properties:
        BucketName: ${self:provider.stage}-uploads
        AccessControl: Private

```

Then use the `S3_UPLOAD_BUCKET_NAME` environment variable to interact with your bucket

Without more informations about your needs, it's hard to help you more. Feel free to give more details or ask more precise questions :slightly_smiling_face:
