### DISCUSSION TITLE
laravel require bootstrap/cache to be writable

### DISCUSSION THREAD

**Discussion by tcedge** [brefphp/bref#959] [Support]
Hi I am trying to setup a laravel  for aws lambda using bref.
after following the initital documentation and deploying the application. I get the following error message 
"The /var/task/bootstrap/cache directory must be present and writable." I knowonly /tmp is writable on a lambda but i expected the bref package to move the bootstrap/cache dire the temp.
Am i doing anything wrong? I would appreciate anyone's help on the matter

 
![image](https://user-images.githubusercontent.com/26552977/122953939-01bc6b00-d34d-11eb-9412-fb9ee6c8af8c.png)

**Comment by tcedge** [comment]
Apologies the error was mine. i realized i was not deploying the application properly

**Reply by francoisauclair911** [reply]
How did you fix this ?

**Reply by nethkenn** [reply]
Any updates on this?

**Reply by 0redd** [reply]
Can you explain the problem please?

**Reply by mnapoli** [reply]
Hey everyone, this problem should be solved by using the Bref-Laravel bridge (https://bref.sh/docs/frameworks/laravel.html#caching).

Read this documentation: https://bref.sh/docs/frameworks/laravel.html

**Reply by 0redd** [reply]
Thank you @mnapoli for the reply and for the excellent project you created.

I followed multiple times the documentation (I think I didn't see something)

By cache, you mean the two folders below?
   /bootstrap/cache
   /storage/framework/cache

In the CI, I execute php artisan config:clear (because I have multiple environments) and it clear the /bootstrap/cache folder.
and when the lambda function is executed, It try to generate a file in the /bootstrap/cache folder, and that explain the error below.
`{
    "class": "Exception",
    "message": "The /var/task/bootstrap/cache directory must be present and writable.",
    "code": 0,
    "file": "/var/task/vendor/laravel/framework/src/Illuminate/Foundation/PackageManifest.php:178",
    "trace": [
        "/var/task/vendor/laravel/framework/src/Illuminate/Foundation/PackageManifest.php:137",
        "/var/task/vendor/laravel/framework/src/Illuminate/Foundation/PackageManifest.php:107",
        "/var/task/vendor/laravel/framework/src/Illuminate/Foundation/PackageManifest.php:90",
        "/var/task/vendor/laravel/framework/src/Illuminate/Foundation/PackageManifest.php:79",
        "/var/task/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/RegisterFacades.php:26",
        "/var/task/vendor/laravel/framework/src/Illuminate/Foundation/Application.php:239",
        "/var/task/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php:153",
        "/var/task/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php:137",
        "/var/task/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php:111",
        "/var/task/public/index.php:52"
    ]
}`

Thanks in advance for your help.

Bref, merci :)

**Reply by francoisauclair911** [reply]
For people that may be facing this in a CI/CD pipelines, I had an issue where my build stage did not pass the generated bootstrap files to the deploy stage, notice how I now pass the any php file in boostrap to the next stage 
` - bootstrap/cache/*.php`

Gitlab example
```yaml
composer:
  image: kirschbaumdevelopment/laravel-test-runner:8.1
  stage: build
  cache:
    key: ${CI_COMMIT_REF_SLUG}-composer
    paths:
      - vendor/
  script:
    - composer --version
    - composer install --prefer-dist --no-ansi --no-interaction --no-progress
    - cp .env.example .env
    - php artisan key:generate
    - php artisan config:clear
  artifacts:
    # expire_in: 1 month
    paths:
      - vendor/
      - .env
      - bootstrap/cache/*.php

```
