### DISCUSSION TITLE
require_once(/opt/breftoolbox.php): Failed to open stream: No such file or directory in /opt/bootstrap on line 15

### DISCUSSION THREAD

**Discussion by semsphy** [brefphp/bref#974] [Support]
Hello There,

I configured to use the `separateVendor` and ran below command, I got an error `Failed to open stream: No such file or directory in /opt/bootstrap on line 15`.

`vendor/bin/bref cli function-prod-artisan --profile=xzy --region ap-southeast-1 -- route:list`

Any suggestions, pls.

### serverless.yml
```yml
service: xzy-services
useDotenv: true

custom:
  bref:
    separateVendor: true

provider:
  name: aws
  region: ap-southeast-1
  runtime: provided.al2

  environment:
    BREF_BINARY_RESPONSES: '1'
    BREF_AUTOLOAD_PATH: '/tmp/vendor/autoload.php'

artisan:
    handler: artisan
    timeout: 120 # in seconds
    layers:
      - ${bref:layer.php-80} # PHP
      - ${bref:layer.console} # The "console" layer
```

### public/index.php

```php
//...

if(isset($_SERVER['LAMBDA_TASK_ROOT'])){
    require '/tmp/vendor/autoload.php';
}
else{
    require __DIR__.'/../vendor/autoload.php';
}

//...
```
