### DISCUSSION TITLE
There is no existing directory at "/var/task/storage/logs"

### DISCUSSION THREAD

**Discussion by castelreng** [brefphp/bref#994] [Support]
Hello,

I am actually migrating a project from DigitalOcean to AWS Infrastructure.
The project is composed of : 

- Front : Angular
- Back : Laravel

When deploying the **back** with the help of Serverless on local, everything is working fine.

I have decided to automate it in gitlab CI/CD. 
When deploying the **back** from gitlab CI/CD, I have errors while consuming my api endpoints.

`There is no existing directory at "/var/task/storage/logs"`

This error should not appear as Bref should forward the logs to CloudWatch.

The most strange is that everything works fine when I deploy it from my local machine.

My gitlab CI/CD: 

```
build_dev:
  stage: build
  image: composer
  script:
    - composer install --no-interaction --prefer-dist --optimize-autoloader
    - php artisan config:clear
    - composer dump-autoload
  only: ['dev']

deploy_dev:
  image: node:alpine
  stage: deploy
  before_script:
    - npm install -g serverless
  script:
    - cp .env.dev .env
    - serverless deploy --stage dev
  only: ['dev'] 
```

My serverless.yml 

````
service: laravel

provider:
    name: aws
    region: eu-west-2
    stage: dev
    runtime: provided.al2
    lambdaHashingVersion: 20201221
    environment:
        APP_STORAGE: '/tmp'
        BREF_BINARY_RESPONSES: '1'
    apiGateway:
        binaryMediaTypes:
            - '*/*'
package:
    patterns:
        - '!node_modules/**'
        - '!public/storage'
        - '!resources/assets/**'
        - '!storage/**'
        - 'storage/app/**'
        - '!tests/**'

functions:
    # This function runs the Laravel website/API
    web:
        handler: public/index.php
        timeout: 28 # in seconds (API Gateway has a timeout of 29 seconds)
        layers:
            - ${bref:layer.php-74-fpm}            
            - arn:aws:lambda:eu-west-2:753330063817:layer:php-gd-layer:1
        events:
            - httpApi: '*'
    # This function lets us run artisan commands in Lambda
    artisan:
        handler: artisan
        timeout: 120 # in seconds
        layers:
            - ${bref:layer.php-74-fpm}             
            - ${bref:layer.console} # The "console" layer
            - arn:aws:lambda:eu-west-2:753330063817:layer:php-gd-layer:1
plugins:
    # We need to include the Bref plugin
    - ./vendor/bref/bref
    - ./vendor/bref/extra-php-extensions
````

Stacktrace of the error: 

```
UnexpectedValueException:
There is no existing directory at "/var/task/storage/logs" and it could not be created: Read-only file system

  at /var/task/vendor/monolog/monolog/src/Monolog/Handler/StreamHandler.php:172
  at Monolog\Handler\StreamHandler->createDir()
     (/var/task/vendor/monolog/monolog/src/Monolog/Handler/StreamHandler.php:100)
  at Monolog\Handler\StreamHandler->write()
     (/var/task/vendor/monolog/monolog/src/Monolog/Handler/AbstractProcessingHandler.php:42)
  at Monolog\Handler\AbstractProcessingHandler->handle()
     (/var/task/vendor/monolog/monolog/src/Monolog/Logger.php:317)
  at Monolog\Logger->addRecord()
     (/var/task/vendor/monolog/monolog/src/Monolog/Logger.php:539)
  at Monolog\Logger->error()
     (/var/task/vendor/laravel/framework/src/Illuminate/Log/Logger.php:174)
  at Illuminate\Log\Logger->writeLog()
     (/var/task/vendor/laravel/framework/src/Illuminate/Log/Logger.php:87)
  at Illuminate\Log\Logger->error()
     (/var/task/vendor/laravel/framework/src/Illuminate/Log/LogManager.php:551)
  at Illuminate\Log\LogManager->error()
     (/var/task/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php:241)
  at Illuminate\Foundation\Exceptions\Handler->report()
     (/var/task/app/Exceptions/Handler.php:39)
  at App\Exceptions\Handler->report()
     (/var/task/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php:88)
  at Illuminate\Foundation\Bootstrap\HandleExceptions->handleException()  
```
Hope that you can help, still investigating it.
