### ISSUE TITLE
Not being able to make use of a separate vendor with the option separateVendor

### ISSUE THREAD

**Issue by AliHichem** [brefphp/bref#1124]
Hi Guys,
I really tried not to bother you again but I'm stuck: I'm still not able to use the option "separateVendor" again, I recently faced an issuesthat I ended up fixing myself with a pull request ( #1121 ) and thank you for accepting it btw ! that problem is gone but now I'm getting a different error further in the serverless deploy process and the error is 

```
Serverless: Invoke aws:deploy:deploy
Serverless: Bref: Checking vendor file on bucket...
Serverless: Bref: Vendor file not found. Uploading...
Serverless: Bref: Vendor separation done
Serverless: Uploading CloudFormation file to S3...
Serverless: Uploading artifacts...
Serverless: Uploading service ********.zip file to S3 (1.62 MB)...
Serverless: Validating template...
 
 Error ---------------------------------------------------
 
  Error: The CloudFormation template is invalid: ValidationError: Template format error: Unresolved resource dependencies [ServerlessDeploymentBucket] in the Resources block of the template
```

**How to reproduce:**

* using Bref:dev-master this time as I wanted to get latest code including my pull request
* serverless version 2.44.0, and I'm getting the same error with serverless 2.35 too
* set this config in serverless.yml

```
custom:
    bref:
        separateVendor: true
```

I may be using a plugin that is triggering this error so here is my simplified serverless file having the parts that you guys need I think

```
service: *********

provider:
    name: aws
    region: ******
    runtime: provided.al2
    deploymentBucket:
        name: *********************
        serverSideEncryption: AES256
    environment:
        BREF_AUTOLOAD_PATH: /opt/vendor/autoload.php 

plugins:
    - ./vendor/bref/bref
    - ./vendor/bref/extra-php-extensions
    - serverless-cloudfront-invalidate
    - serverless-plugin-scripts

custom:
    bref:
        separateVendor: true 
```

Not sure why that error is triggered, maybe because **ServerlessDeploymentBucket** is  hardcoded in bref .. I don't know. So far the upload of the zipped separate vendor is succeeding and I can see it in my serverless deployment bucket but for some reason when serverless is updating the cloudformation conf with the s3 arn of the uploaded vendor it crashes throwing the error 

`Error: The CloudFormation template is invalid: ValidationError: Template format error: Unresolved resource dependencies [ServerlessDeploymentBucket] in the Resources block of the template`

I would really like to have any help about issue.
Thank you !

**Comment by mnapoli** [comment]
> maybe because ServerlessDeploymentBucket is hardcoded

Yes it seems that's the problem (you have overridden the bucket). I'm afraid this kind of behavior isn't supported yet, so a pull request to implement that might be needed too unfortunately.

**Comment by AliHichem** [comment]
I did some more investigation before starting on a PR for this and I simply added the missing reference using a serverless plugin  called **serverless-parameters** as below :

```
plugins:
    - ./vendor/bref/bref
    - ./vendor/bref/extra-php-extensions
    - serverless-parameters
 
custom:
    bref:
        separateVendor: true
    parameters:
        ServerlessDeploymentBucket:
            Type: String
            Default: ${self:provider.deploymentBucket.name}
```

Now the deployment succeed well and I can see my parameter  **ServerlessDeploymentBucket** in Cloudformation parameters list in AWS console having the right custom bucket name in it, also the vendors are uploaded as expected but .. the symfony code fails and this time in bref's layer that is supposed to download the vendors zip file and extract it. From Cloud watch : 

```
PHP Deprecated:  ZipArchive::open(): Using empty file as ZipArchive is deprecated in /opt/breftoolbox.php on line 192
Deprecated: ZipArchive::open(): Using empty file as ZipArchive is deprecated in /opt/breftoolbox.php on line 192
PHP Warning:  unlink(/tmp/vendor.zip): No such file or directory in /opt/breftoolbox.php on line 72
```

And basically this means that the remote vendors.zip is either not downloadable or bref toolbox is not getting its path right from CloudFormation.

At this point this I honestly don't know how to debug this as I can't access bref's layer code to analyse breftoolbox.php, yeah sure I can create my forked bref runtime, upload it and inluded my debug statements in it but I don't know this time it's worth it.

I'm giving up on this **separateVendor** feature for now. I wouldn't mind if you guys decide to close this bug.
Anyway, thanks for your time.

**Comment by t-richard** [comment]
Hi @AliHichem 

I think the error you have now is due to a lack of permissions for your Lambda function to download the zip from the bucket.

When using the default serverless deployment bucket, Bref adds permissions to the IAM role statement generated by the serverless framework so that it can download the ZIP file rom it.

You can see it here and maybe try to mimick what is done there. https://github.com/brefphp/bref/blob/master/index.js#L94

Hope this helps

**Comment by AliHichem** [comment]
@t-richard I actually thought about that and made the bucket publicly accessible (temporarily of course ) using this config:
```
provider:
  deploymentBucket:
    blockPublicAccess: true 
```
And not getting any success with it I reverted it back to its default value to **false**. 

After your comment which makes perfect sense btw, I added the necessary execution role policy to my lambda function to get granted access to all the resources under the **serverless/vendors**  key in my S3 deployment bucket: Of course I checked the generated s3 url within CloudFormation updated template and made a test using **IAM Policy Simulator** on the latest generated vendor.zip and the tested Lambda Role and I can see that  my lambda function has granted access to the all of the vendors zip files but still BrefToolbox is unable to get it :
```
PHP Deprecated: ZipArchive::open(): Using empty file as ZipArchive is deprecated in /opt/breftoolbox.php on line 192 
Deprecated: ZipArchive::open(): Using empty file as ZipArchive is deprecated in /opt/breftoolbox.php on line 192 
PHP Warning: unlink(/tmp/vendor.zip): No such file or directory in /opt/breftoolbox.php on line 72 
```
As I said at this point I'm unable to go further in my debug .. Cloud Trail doesn't show anything helpful related the vendors.zip download ( I honestly never was good at using CloudTrail anyway ) so I'm stuck again ^^.

Btw, I'am able to have a separate vendor layer and put all my vendors in it which I think would make a better cold start for the lambda function anyway rather than having the vendors in the temp folder ( correct me if I'm wrong here ) but the separate vendors layer is failing during the autoload of my app Bundles and Function due to composer's weird way of guessing the base dir from the vendors dir : 
```
# composer/autoload_psr4.php
// autoload_psr4.php @generated by Composer

$vendorDir = dirname(dirname(__FILE__));
$baseDir = dirname($vendorDir);
```
I think as a last resort I'll just try to make this separate vendors layer attempt and fix the autloading issue by rewriting the necessary composer autoload statements like what BrefToolbox do at some point right ? 

Damm this is so much easy in my nodejs apps, having a separate layer for node_modules is a no brainer unlike with composer ^^

**Comment by t-richard** [comment]
> I actually thought about that and made the bucket publicly accessible

I think this does not work because Bref doesn't download the file directly but instead generates a presigned url then download from it. This presigned-url is generated with your secret key (the one provided by Lambda thanks to the IAM role statement associated to the function) so if your role doesn't give the proper permissions, I think it will not work.

Have you tried adding this to your serverless.yml file (note I wrote this in Github, the syntax might be slightly incorrect)

```yaml
provider:
    iamRoleStatements:
        - Effect: 'Allow'
          Action:
                - 's3:GetObject'
          Resource:
              'Fn::Join':
                  - ''
                  - - 'arn:aws:s3:::'
                    - !Ref ServerlessDeploymentBucket
                    - '/'
                    - '<your path in the bucket>/vendors/*'
```

> Btw, I'am able to have a separate vendor layer and put all my vendors in it which I think would make a better cold start for the lambda function anyway rather than having the vendors in the temp folder

AFAIK adding a layer would not change anything as layers don't affect cold start in a good or bad way and you have a 250MB max size for your your function code + layers combined so moving vendors in a layer won't change something here.

**Comment by AliHichem** [comment]
> AFAIK adding a layer would not change anything as layers don't affect cold start in a good or bad way and you have a 250MB max size for your your function code + layers combined so moving vendors in a layer won't change something here.

Correct me if I'm wrong again but doesn't the cold start trigger BrefToolBox to download the vendors zip,extract it and tweak the autoload ? This happens on each cold start right ? 

Also working with anything not temporary ( i.e vendors ) in the temp folder, isn't it a bit risky for possible system cleanup of temp folder ? I mean I don't have anything against this approach if it guarantees the vendors existence on each lambda event/request  

Layers may not affect speed of course but for cold start there is nothing to download or prepare, this said I'm assuming here my understanding is right about  the timing of the breftoolbox and its execution on each coldstart.

Also  layers space is still within the total of the lambda 250mb but if we have multiple functions like website and console  they can  share the same layer and hence a shorter time to deploy.

**Comment by t-richard** [comment]
Yes it is downloaded for each coldstart. AFAIK `/tmp` is not supposed to be erased and will only be there for 10 minutes (the lifetime of a Lambda "container" in AWS).

My point here was more that putting the vendor folder in a layer will not have a performance impact compared to deploying it along code. And the separate vendor is specifically designed to help you in case your total function size is above the 250MB limit.

Also for web and console, I think the serverless framework will use the same deployment package by default if they are not different but I never really tried to optimize it that way so not really sure here.

It is not really clear to me what is the original problem you are trying to solve with this?

**Comment by AliHichem** [comment]
( sorry for my late reply )

> Yes it is downloaded for each coldstart. AFAIK `/tmp` is not supposed to be erased and will only be there for 10 minutes (the lifetime of a Lambda "container" in AWS).

I see, I was actually concerned about that and now I can't say that I'm liking this behavior.

> My point here was more that putting the vendor folder in a layer will not have a performance impact compared to deploying it along code. And the separate vendor is specifically designed to help you in case your total function size is above the 250MB limit.

I agree, the cold start is way faster when using a layer though .. anyway.

> Also for web and console, I think the serverless framework will use the same deployment package by default if they are not different but I never really tried to optimize it that way so not really sure here.

I'm also not sure about it but I think that when using layer the code is "shared" so the real benefit behind it would only be a shorter deployment time and a versioning system to your vendors if that may be of interest ..


> It is not really clear to me what is the original problem you are trying to solve with this?

Sorry if I dragged you guys into this issue without making myself clear: I was actually trying the **separateVendor** feature as it sounds having several benefits, my code is quite big and getting bigger because of the vendors and this separateVendor seems to solve it. Also I was very interested to be able to edit my code within lambda for online debugging when I need to ( I know it's risky, I only do that in staging for some specific bugs ).

Btw I did  add the permission using **iamRoleStatements** config but it resulted the same as my updated role policy change which is what I expected. I may still have a config that is preventing me from using **separateVendor** and I'm not sure if this is  coming from one of the serverless plugins I'm using or something else .. My point it this my be only happening in my specific case and since I don't it happening to anybody else I'll just close this bug.

This said, for anyone interested I was able to move my vendors to a different layer and it works like a charm. To do so : 

```
#serverless.yml
functions:
    website:
        handler: public/index.php
        timeout: 28 # in seconds (API Gateway has a timeout of 29 seconds)
        layers:
            - ${bref:layer.php-80-fpm}
            - {Ref: PhpvendorLambdaLayer}
layers:
    phpvendor:
        name: ${self:provider.stage}-phpvendor
        path: layer/phpvendor/export/

```

before your sls deploy run these commands  : 

```
# do not exclude vendors in serverless, reinclude only bref under vendors as it is needed by serverless
- cp -r vendor/ layer/phpvendor/export/ && rm -r vendor/* && cp -r layer/phpvendor/export/vendor/bref/ vendor/ && echo "<?php  require_once '/opt/vendor/autoload.php';" > vendor/autoload.php
# Update composer autoload_static.php file with correct path for Lambda task root
- sed -i "s/__DIR__\ \.\ '\/\.\.\/\.\.'/'\/var\/task'/g" layer/phpvendor/export/vendor/composer/autoload_static.php
```

Thank you all again !
