### ISSUE TITLE
I cant separate my vendor folder from my app folder, i get Unrecognized configuration variable sources: "bref"

### ISSUE THREAD

**Issue by oluwapaso** [brefphp/bref#1231]
```
service: app
  
  provider:
      name: aws
      runtime: provided.al2
      
      environment:
          BREF_AUTOLOAD_PATH: '/tmp/vendor/autoload.php'
  
  functions:
      foo:
          handler: index.php
          layers:
              - ${bref:layer.php-81} # PHP
  custom:
      bref:
          separateVendor: true
```

Hi, please I am having an issue separating my vendor folder from the main app folder. The above serverless.yml settings give Unrecognized configuration variable sources: "bref". But if I add this block     
```
plugins:
  - ./vendor/bref/bref
```

it includes the vendor folder in the app folder which makes it too big and I can't edit my code in lambda in-line editor

**Comment by mnapoli** [comment]
Interesting, normally with `separateVendor: true` the `vendor` directory should be automatically excluded.

Could you confirm your Bref version?

And maybe try excluding the folder manually with this config:

```yaml
package:
    patterns:
        - '!vendor/**'
```
