### ISSUE TITLE
Conflict between separateVendor and serverless-iam-roles-per-function plugin

### ISSUE THREAD

**Issue by NicolasMugnier** [brefphp/bref#1248]
**Description:**

The custom parameter `separateVendor` allow to move the `vendor` directory into an S3 bucket and the bref runtime will copy the content of the directory in `/tmp/vendor` as describe in the [documentation](https://bref.sh/docs/environment/php.html#separate-vendor-folder).

It works well as soon as I have installed the [IAM roles per function serverless plugin](https://www.npmjs.com/package/serverless-iam-roles-per-function). As well described in bref [documentation](https://bref.sh/docs/environment/serverless-yml.html#permissions) this serverless plugin allow to define specific roles at the lambda level, which is a good practice. 

But when using `separateVendor` custom parameter and `serverless-iam-roles-per-function` plugin, I've got the following error when trying to invoke the lambda after deploy : 

```php
PHP Fatal error: Uncaught Exception: Unable to unzip vendor archive. in /opt/bref/breftoolbox.php:69
Stack trace:
#0 /opt/bref/bootstrap.php(15): Bref\ToolBox\BrefToolBox::downloadAndConfigureVendor()
#1 {main}
thrown in /opt/bref/breftoolbox.php on line 69
````
**How to reproduce:**

In order to reproduce this error, in the `serverless.yml` file add the following configuration (I've put the whole file content so you have all the context) : 

```yaml
service: app

provider:
    name: aws
    region: eu-west-1
    runtime: provided.al2

custom:
    bref:
        separateVendor: true # true in order to enable the feature

plugins:
    - serverless-iam-roles-per-function # when disable this plugin the `separateVendor` feature works well
    - ./vendor/bref/bref

functions:
    addBook:
        handler: ./src/Events/create/index.php
        description: 'Add a new book'
        layers:
            - ${bref:layer.php-81}
        iamRoleStatements:
            - Effect: 'Allow'
              Action:
                - dynamodb:PutItem
                - dynamodb:GetItem
              Resource: 'arn:aws:dynamodb:${aws:region}:${aws:accountId}:table/book'

    getBook:
        handler: ./src/Events/read/index.php
        description: 'Get a specific book'
        layers:
            - ${bref:layer.php-81}
        iamRoleStatements:
            - Effect: 'Allow'
              Action:
                - dynamodb:GetItem
              Resource: 'arn:aws:dynamodb:${aws:region}:${aws:accountId}:table/book'

    deleteBook:
        handler: ./src/Events/delete/index.php
        description: 'Delete a book'
        layers:
            - ${bref:layer.php-81}
        iamRoleStatements:
            - Effect: 'Allow'
              Action:
                - dynamodb:DeleteItem
              Resource: 'arn:aws:dynamodb:${aws:region}:${aws:accountId}:table/book'

# Exclude files from deployment
package:
    patterns:
        - '!tests/**'
        - '!node_modules/**'

resources:
  Resources:
    BookTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: 'book'
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST

````
Deploy the app `serverless deploy`
Invoke the function : `serverless invoke --function addBook -d '{"title":"Bref Rocks!", "Author": "Brefphp"}'` and you'll have the error.

Note : when I set the `separateVendor` parameter as `false`, then all works but the `vendor` directory is pushed into each lambda.

If needed, the whole project can be found on this repository : [poc-aws-lambda-custom-runtime-bref](https://github.com/NicolasMugnier/poc-aws-lambda-custom-runtime-bref/blob/main/event-driven-crud/)
