### ISSUE TITLE
Improve the "bref local" documentation for Windows users

### ISSUE THREAD

**Issue by sahilr2050** [brefphp/bref#1270]
It gives an error "invalid JSON."

While playing around with bref.sh. I tried to implement [Local development for functions](https://bref.sh/docs/function/local-development.html)

`index.php`
```
return function (array $event) {
    return 'Hello ' . ($event['name'] ?? 'world');
};
```

`serverless.yml`
```
service: demo-app

provider:
    name: aws
    region: ap-southeast-2
    runtime: provided.al2

plugins:
    - ./vendor/bref/bref

functions:
    hello:
        handler: index.php
        description: 'folder'
        layers:
            - ${bref:layer.php-74}
        events:
            - sqs:
                  arn: arn:aws:sqs:ap-southeast-2:xxx:xxx
                  batchSize: 1

# Exclude files from deployment
package:
    exclude:
        - 'node_modules/**'
        - 'tests/**'
        - '.idea/**'

disabledDeprecations:
    - LAMBDA_HASHING_VERSION_V2
    - NEW_PACKAGE_PATTERNS

variablesResolutionMode: 20210326
```

**How to reproduce:**

- Create a file like above
- run the command `vendor/bin/bref local hello '{"name": "Jane"}'`
