### ISSUE TITLE
Serverless invoke error "Exception - The command exited with a non-zero status code: 7"

### ISSUE THREAD

**Issue by jrholowka** [brefphp/bref#1281]
Hello,

I am getting the following error after upgraded the Serverless framework version from `2.34.0` to `3.22.0`:

```
$ serverless invoke --function console --stage dev --data '{"cli":"doctrine:migrations:migrate --allow-no-migration --no-interaction"}'

For help, see: https://nodejs.org/en/docs/inspector
Debugger attached.
{
    "errorType": "Exception",
    "errorMessage": "The command exited with a non-zero status code: 7",
    "stackTrace": [
        "#0 /var/task/vendor/bref/bref/src/Runtime/Invoker.php(34): {closure}()",
        "#1 /var/task/vendor/bref/bref/src/Runtime/LambdaRuntime.php(91): Bref\\Runtime\\Invoker->invoke()",
        "#2 /opt/bootstrap(65): Bref\\Runtime\\LambdaRuntime->processNextEvent()",
        "#3 {main}"
    ]
}
Environment: linux, node 16.17.1, framework 3.22.0, plugin 6.2.2, SDK 4.3.2
Credentials: Local
Docs:        docs.serverless.com
Support:     forum.serverless.com
Bugs:        github.com/serverless/serverless/issues

Error:
Invoked function failed
```

My serverless.yml

```
service: service-api
frameworkVersion: 3.22.0
useDotenv: true

provider:
  name: aws
  region: eu-central-1
  runtime: provided.al2
  stage: dev

plugins:
  - ./vendor/bref/bref

package:
  patterns:
    - "!node_modules/**"
    - "!tests/**"
    - "!var/**"
    - "var/cache/prod/**" 
    - ".env*"

functions:
  # This function let us run console commands in Lambda
  console:
    handler: bin/console
    timeout: 120 # in seconds
    layers:
      - ${bref:layer.php-80} # PHP
      - ${bref:layer.console} # The "console" layer
...

```

composer.json
```
{
    "type": "project",
    "require": {
        "php": ">=8.0",
        "ext-ctype": "*",
        "ext-iconv": "*",
        "bref/bref": "^1.2",
        "bref/symfony-bridge": "^0.1.3",
        "composer/package-versions-deprecated": "1.11.99.4",
        "doctrine/annotations": "^1.13",
        "doctrine/doctrine-bundle": "^2.4",
        "doctrine/doctrine-migrations-bundle": "^3.1",
        "doctrine/orm": "^2.12",
        "gedmo/doctrine-extensions": "^3.7",
        "league/flysystem-aws-s3-v3": "^2.1",
        "league/flysystem-bundle": "^2.0",
        "symfony/console": "^5",
        "symfony/dotenv": "^5",
        "symfony/flex": "^1.3.1",
        "symfony/framework-bundle": "^5",
        "symfony/monolog-bundle": "^3.7",
        "symfony/property-access": "^5",
        "symfony/proxy-manager-bridge": "^5",
        "symfony/yaml": "^5"
    },
    ...
}
```
I was able to deploy my service using the `serverless deploy ...` command however, executing `serverless invoke --function console ..` seems not to work anymore.  I also ran `serverless doctor` to check for deprecations but there is any. I would appreciate if anyone can give me any idea what is going on.

Thank you.
