### ISSUE TITLE
separateVendor and iam statements conflict

### ISSUE THREAD

**Issue by liepumartins** [brefphp/bref#1311]
**Description:**

Using `separateVendor: true` together with iam roles defined as show here https://bref.sh/docs/environment/storage.html#application-cache breaks separateVendor `PHP Fatal error: Uncaught Exception: Unable to unzip vendor archive. in /opt/bref/breftoolbox.php:69`

**How to reproduce:**

```yml
service: laravel

provider:
    name: aws
    # The AWS region in which to deploy (us-east-1 is the default)
    region: eu-north-1
    # The stage of the application, e.g. dev, production, staging… ('dev' is the default)
    stage: dev
    runtime: provided.al2
    # begin of problematic statements
    iam:
        role:
            statements:
                - Effect: Allow
                  Resource: !GetAtt CacheTable.Arn
                  Action:
                      - dynamodb:DescribeTable
                      - dynamodb:Query
                      - dynamodb:Scan
                      - dynamodb:GetItem
                      - dynamodb:PutItem
                      - dynamodb:UpdateItem
                      - dynamodb:DeleteItem
    # end of problematic statements
    environment:
        # This environment variable will contain the table name
        DYNAMODB_CACHE_TABLE: !Ref CacheTable

package:
    # Directories to exclude from deployment
    patterns:
        - '!database/**'
        - '!node_modules/**'
        - '!public/storage'
        - '!resources/assets/**'
        - '!resources/js/**'
        - '!resources/sass/**'
        - '!storage/**'
        - '!tests/**'

functions:
    # This function runs the Laravel website/API
    web:
        iamRoleStatementsInherit: true
        handler: public/index.php
        timeout: 28 # in seconds (API Gateway has a timeout of 29 seconds)
        memorySize: 1024
        layers:
            - ${bref:layer.php-81-fpm}
        events:
            - httpApi: '*'
    # This function lets us run artisan commands in Lambda
    artisan:
        iamRoleStatementsInherit: true
        handler: artisan
        memorySize: 1024
        timeout: 120 # in seconds
        layers:
            - ${bref:layer.php-81} # PHP
            - ${bref:layer.console} # The "console" layer

plugins:
  - ./vendor/bref/bref
  - serverless-lift
  - serverless-iam-roles-per-function

constructs:
    website:
        type: server-side-website
        assets:
            '/scripts/*': public/scripts
            '/styles/*': public/styles
            '/favicon.ico': public/favicon.ico
            '/robots.txt': public/robots.txt
            # add here any file or directory that needs to be served from S3
        # Laravel uses some headers that are not in CloudFront's default whitelist.
        # To add any, we need to list all accepted headers to pass through.
        # https://github.com/getlift/lift/blob/master/docs/server-side-website.md#forwarded-headers
        forwardedHeaders:
            - Accept
            - Accept-Language
            - Content-Type
            - Origin
            - Referer
            - User-Agent
            - X-Forwarded-Host
            - X-Requested-With
            # Laravel Framework Headers
            - X-Csrf-Token
            # Other Headers (e.g. Livewire, Laravel Nova), uncomment based on your needs
            - X-Livewire
            # - X-Inertia

resources:
    Resources:
        CacheTable:
            Type: AWS::DynamoDB::Table
            Properties:
                AttributeDefinitions: # only keys are defined here, other attributes are dynamic
                    -   AttributeName: id # adds a mandatory id field
                        AttributeType: S # the type of id is a string
                BillingMode: PAY_PER_REQUEST # billed for each request instead of paying for a constant capacity
                TimeToLiveSpecification: # deletes cache keys automatically based on a ttl field which contains a timestamp
                    AttributeName: ttl
                    Enabled: true
                KeySchema:
                    -   AttributeName: id
                        KeyType: HASH # the type of key, HASH means partition key (similar to primary keys in SQL)
custom:
  bref:
    separateVendor: true
  

```

#1248 suggested to include `iamRoleStatementsInherit: true`, but that did not help. Only removing the whole 

```yml
iam:
        role:
            statements:
                - Effect: Allow
                  Resource: !GetAtt CacheTable.Arn
                  Action:
                      - dynamodb:DescribeTable
                      - dynamodb:Query
                      - dynamodb:Scan
                      - dynamodb:GetItem
                      - dynamodb:PutItem
                      - dynamodb:UpdateItem
                      - dynamodb:DeleteItem
```

Feels like the statement overwrites permissions required by separateVendor.

**Comment by liepumartins** [comment]
It appears that conflict arises because of two possible notations.
`iam: role: statements:` vs `iamRoleStatements` latter is used by separateVenor and is about to be deprecated afaik.

Rewriting to older notation fixes the conflict. For now.
```
  iamRoleStatements:
    - Effect: Allow
      Resource: !GetAtt CacheTable.Arn
      Action:
        - dynamodb:DescribeTable
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
  ```
