### ISSUE TITLE
More than one function contains the console layer: cannot automatically run it

### ISSUE THREAD

**Issue by ddeboer** [brefphp/bref#1459]
**Description:**

If you have two or more functions using the `console` layer, for example a [console](https://bref.sh/docs/runtimes/console.html) and a [cron function](https://bref.sh/docs/web-apps/cron.html), Bref 2 throws an error when invoking `bref:cli`:

```
More than one function contains the console layer: cannot automatically run it
```

I didn’t find a way to manually provide the function name, as was used on Bref 1.

**How to reproduce:**

Configure at least two functions using the `console` layer, for example:

```yaml
functions:
  console:
    handler: bin/console
    runtime: php-82-console  
  cron:
    handler: bin/console
    runtime: php-82-console
```

Then run:

```shell
$ serverless bref:cli
Running "serverless" from node_modules
Environment: darwin, node 18.14.1, framework 3.26.0 (local) 3.27.0v (global), plugin 6.2.2, SDK 4.3.2
Credentials: Local
Docs:        docs.serverless.com
Support:     forum.serverless.com
Bugs:        github.com/serverless/serverless/issues

Error:
More than one function contains the console layer: cannot automatically run it
```
