### ISSUE TITLE
Local development has broken binary files.

### ISSUE THREAD

**Issue by sunaoka** [brefphp/bref#1524]
**Description:**

We are doing local development in a Docker environment with `BREF_BINARY_RESPONSES: '1'`.

When we deploy to AWS, we get the binary file without any problem, but in a local environment, the responded binary file is broken.

Is there any way to fix this?

A simple example is provided below.

**compose.yaml**

```yaml
services:

  php:
    image: bref/arm-php-82-fpm-dev:2
    ports:
      - '8000:8000'
    volumes:
      - .:/var/task
    environment:
      HANDLER: index.php
      BREF_BINARY_RESPONSES: 1
```

**index.php**

```php
<?php

header('Content-Type: image/png');
readfile(__DIR__ . '/test.png');
```

**test.png**

![test](https://user-images.githubusercontent.com/105845/235561535-8ab739a2-61c5-4230-a4e7-7ce4f344d647.png)

**Broken PNG file**

![broken](https://user-images.githubusercontent.com/105845/235561811-0c091575-30fc-4758-a14e-027a2e945e92.png)

so, `docker compose up` and access `http://localhost:8000`
