### ISSUE TITLE
Failed to load bref autoload.php

### ISSUE THREAD

**Issue by aftabnaveed** [brefphp/bref#1597]
Hi while trying to run Laravel Application inside a container on LAMBDA I get this error: 

```


2023-07-19T17:57:50.944+05:00 | Warning: require(/var/task/vendor/autoload.php): Failed to open stream: No such file or directory in /opt/bref/bootstrap.php on line 8
-- | --
  | 2023-07-19T17:57:50.944+05:00 | Fatal error: Uncaught Error: Failed opening required '/var/task/vendor/autoload.php' (include_path='.:/opt/lib/php') in /opt/bref/bootstrap.php:8
  | 2023-07-19T17:57:50.944+05:00 | Stack trace:
  | 2023-07-19T17:57:50.944+05:00 | #0 {main}
  | 2023-07-19T17:57:50.944+05:00 | thrown in /opt/bref/bootstrap.php on line 8
  | 2023-07-19T17:57:51.033+05:00 | Warning: require(/var/task/vendor/autoload.php): Failed to open stream: No such file or directory in /opt/bref/bootstrap.php on line 8
  | 2023-07-19T17:57:51.033+05:00 | Fatal error: Uncaught Error: Failed opening required '/var/task/vendor/autoload.php' (include_path='.:/opt/lib/php') in /opt/bref/bootstrap.php:8
  | 2023-07-19T17:57:51.033+05:00 | Stack trace:

```

Here is my `serverless.yaml file
```yml
service: bref-with-docker

provider:
    name: aws
    # The AWS region in which to deploy (us-east-1 is the default)
    region: us-west-1
    ecr:
      images:
        hgs:
          path: ./
    # Environment variables
    environment:
        APP_ENV: local # Or use ${sls:stage} if you want the environment to match the stage
plugins:
    - ./vendor/bref/bref
    
package:
    # Files and directories to exclude from deployment
    patterns:
        - '!node_modules/**'
        - '!public/storage'
        - '!resources/assets/**'
        - '!storage/**'
        - '!tests/**'
        - '!ui/**'

functions:

    # This function runs the Laravel website/API
    hgsfunc:
        image:
          name: hgs
        timeout: 28 # in seconds (API Gateway has a timeout of 29 seconds)
        events:
            - httpApi: '*'

```

My Dockerfile

```docker
FROM bref/php-81-fpm:2

COPY --from=bref/extra-redis-php-81:1 /opt /opt
COPY --from=bref/extra-mongodb-php-81:1 /opt /opt
COPY --from=bref/extra-gd-php-81:1 /opt /opt
COPY ext-intl.ini /opt/bref/etc/php/conf.d/
COPY php.ini /opt/bref/etc/php/conf.d/bref.ini


COPY . /var/task

CMD ["public/index.php"]
```

I have installed the bref packages via composer, but I am not exactly sure what's going on here. Sorry I am new to serverless and therefore `bref`  and don't yet fully know the entire flow. 

Thanks for your help in advance.
