### ISSUE TITLE
Serverless deploy failed with error -  Warning: Invalid configuration encountered

### ISSUE THREAD

**Issue by KalanaPerera** [brefphp/bref#1717]
Serverless deploy fails

Warning: Invalid configuration encountered
  at 'functions.web.runtime': must be equal to one of the allowed values [dotnet6, dotnetcore3.1, go1.x, java11, java8, java8.al2, nodejs12.x, nodejs14.x, nodejs16.x, nodejs18.x, provided, provided.al2, python3.6, python3.7, python3.8, python3.9, ruby2.7]
  at 'functions.artisan.runtime': must be equal to one of the allowed values [dotnet6, dotnetcore3.1, go1.x, java11, java8, java8.al2, nodejs12.x, nodejs14.x, nodejs16.x, nodejs18.x, provided, provided.al2, python3.6, python3.7, python3.8, python3.9, ruby2.7]
  at 'constructs.jobs': unsupported configuration format

Learn more about configuration validation here: http://slss.io/configuration-validation

```
functions:
  web:
    handler: public/index.php
    timeout: 28
    runtime: php-82-fpm
    events:
      - httpApi: "*"
      - schedule:
          rate: rate(5 minutes)
          input:
            warmer: true
  artisan:
    handler: artisan
    timeout: 120
    runtime: php-82-console
```

-------
serverless --version
Framework Core: 3.28.1
Plugin: 6.2.3
SDK: 4.3.2

PHP 8.2.12

---

```
 "require": {
        "php": "^8.0.2",
        "ably/ably-php": "^1.1",
        "bref/bref": "^2.1.9",
        "bref/extra-php-extensions": "^1.0",
        "bref/laravel-bridge": "^2.2",
        "doctrine/dbal": "^3.6",
        "guzzlehttp/guzzle": "^7.2",
        "jenssegers/mongodb": "^3.9",
        "laravel/cashier": "^14.12",
        "laravel/cashier-paddle": "^1.8",
        "laravel/framework": "^9.19",
        "laravel/sanctum": "^3.2",
        "laravel/socialite": "^5.6",
        "laravel/tinker": "^2.7",
        "league/flysystem-aws-s3-v3": "^3.0",
        "predis/predis": "^2.1",
        "sentry/sentry-laravel": "^3.3",
        "spatie/laravel-fractal": "^6.0"
    },
```

**How to reproduce:**

serverless deploy

Serverless Config

Thank you and Any help would be appreciated, This is suddenly happening. :(
