### ISSUE TITLE
CORS Issue for Javascript

### ISSUE THREAD

**Issue by michaelaguiar** [brefphp/bref#1890]
**Description:**

I am deploying a Laravel app and am getting a CORS Issue for .js file, and they won't load. I followed the documentation and included `serverless-lift`, per my example below, and css / images load fine. It's only the .js files that are running into the CORS Issue.

I noticed that the Cloudfront behavior for the `/build/*` route can have a `CORS-S3Origin` Origin Request Policy that fixes the issue, but is there a way to do this automatically in the serverless.yml file, or is there a different solution for why .js files won't load?

**How to reproduce:**

```yaml
constructs:
  website:
    type: server-side-website
    assets:
      "/build/*": public/build
      "/images/*": public/images
      "/favicon.ico": public/favicon.ico
      "/robots.txt": public/robots.txt
```
