### ISSUE TITLE
Serverless invoke error "Runtime.ExitError"

### ISSUE THREAD

**Issue by damoncasale** [brefphp/bref#1893]
This is basically the same error as #409.  When I invoke my Lambda function, finishReport, I'm getting a Runtime.ExitError saying, Couldn't find valid bootstrap(s): [/var/task/bootstrap /opt/bootstrap].  This is when invoking a Lambda that has already been deployed via serverless.

I've tried providing a runtime under "provider."  I've tried providing it under the actual function.  I've tried using the bref runtime, or the provided.al2.  I get the same error every time.

Could version 13 of the php-84-fpm runtime be defective?  I read in another bug report about multiple layer versions for an earlier version of PHP being defective.

Here's my serverless.yml:

```
service: laravel

provider:
    name: aws
    # The AWS region in which to deploy (us-east-1 is the default)
    region: us-east-1
    runtime: provided.al2
    memorySize: 2048 # Default is 1024
    # Environment variables
    environment:
        APP_ENV: production # Or use ${sls:stage} if you want the environment to match the stage
        SESSION_DRIVER: cookie # Change to database if you have set up a database

package:
    # Files and directories to exclude from deployment
    patterns:
        - '!node_modules/**'
        - '!public/storage'
        - '!resources/assets/**'
        - '!storage/**'
        - '!tests/**'
        - '!database/*.sqlite'
        - '!scripts/**'

plugins:
    # We need to include the Bref plugin
    - ./vendor/bref/bref

functions:

    # This function runs the Laravel website/API
    #web:
    #    handler: public/index.php
    #    runtime: php-84-fpm
    #    timeout: 28 # in seconds (API Gateway has a timeout of 29 seconds)
    #    events:
    #        - httpApi: '*'
    finishReport:
        handler: public/index.php
        #runtime: provided.al2
        #runtime: php-84-fpm
        timeout: 28 # in seconds (API Gateway has a timeout of 29 seconds)
        events:
            - httpApi: 'POST /api/finish-report'
        layers:
            - 'arn:aws:lambda:us-east-1:534081306603:layer:php-84-fpm:13'

    # This function lets us run artisan commands in Lambda
    artisan:
        handler: artisan
        runtime: php-84-console
        timeout: 720 # in seconds
        # Uncomment to also run the scheduler every minute
        #events:
        #    - schedule:
        #          rate: rate(1 minute)
        #          input: '"schedule:run"'
```
