### ISSUE TITLE
SAM vs Serverless: switch to Serverless again?

### ISSUE THREAD

**Issue by mnapoli** [brefphp/bref#320]
Yes let's discuss switching back again from SAM to the [serverless framework](https://serverless.com/) ([documentation](https://serverless.com/framework/docs/providers/aws/)) 😄  (see #99)

I open this issue because things have moved forward with the serverless framework. Mainly: it supports layers and it can run things locally with Docker.

But another big reason is that, after trying again serverless, it solves a lot of small pain points with SAM. For example:

- the region is defined in the config, you never have to deal with it in the CLI
- deploy in only one step (instead of 3 with SAM)

and **it is extensible**. That opens very interesting doors, for example to simplify a lot some things like setting layer ARNs:

```yaml
Resources:
    SimpleFunction:
        Type: AWS::Serverless::Function
        Properties:
            FunctionName: 'bref-demo-function'
            Handler: function.php
            Runtime: provided
            Layers:
                - 'arn:aws:lambda:us-east-2:209497400698:layer:php-72:4'
```

After with serverless:

```yaml
functions:
    bref-demo-function:
        handler: function.php
        runtime: provided
        layers:
            - ${bref:layer.php-72}
```

What's great with that as well is that runtime versions could be handled by Bref itself, making upgrading Bref as simple as `composer update`.

In short **serverless could help make things simpler**.

## BC break

If we switch we would direct tooling efforts towards serverless.

**However Bref would still work with SAM**.

But since the documentation would be rewritten to target serverless I think it could be considered a BC break (or a major change).

## Full comparison SAM vs Serverless

Here is a complete comparison of features:

https://docs.google.com/spreadsheets/d/1DP2uVbg6TLfBa56XJ1GwlSSKQM1sM87-S3LQ2Pl9sPI/edit?usp=sharing

Please have a look and comment (here or in Google Docs) what is missing and what should be added to the list.

As you will see Serverless has a lot of advantages, the only big question left is local development.

WDYT?

**Comment by atrope** [comment]
Hey @mnapoli,

I will always favor Serverless Framework because it's one less vendor lock we have.
I also think SLS framework is better and more documented than SAM.


I will have a look in local dev with custom layer the next few days and will let you know if I get anywhere.  With python I know it works great.

**Comment by atrope** [comment]
Ok, some updates.

Definitely Possible to run bref locally with SLS.

The test:

the YML:
```

service: localTest
plugins:
  - serverless-offline
provider:
  name: aws
  runtime: provided
functions:
  hello:
    handler: index.php
    layers:
      - arn:aws:lambda:us-east-1:209497400698:layer:php-72-fpm:6
    events:
      - http: ANY /
      - http: 'ANY {proxy+}'

```
 
Install serverless-offline (npm install serverless-offline --save-dev).

In Serverless offline need to edit 2 files, 

**index.js**
Lines 367 to 381:  (need to add --docker if it is provided) need to remove the error they put for provided and allow it.

 ```
   // if (serviceRuntime === 'provided') {
    //   if (this.options.providedRuntime) {
    //     serviceRuntime = this.options.providedRuntime;
    //   }
    //   else {
    //     throw new Error('Runtime "provided" is unsupported. Please add a --providedRuntime CLI option.');
    //   }
    // }

    if (!( serviceRuntime.startsWith('provided') || serviceRuntime.startsWith('nodejs') || serviceRuntime.startsWith('python') || serviceRuntime.startsWith('ruby'))) {
      this.printBlankLine();
      this.serverlessLog(`Warning: found unsupported runtime '${serviceRuntime}'`);

      return;
    }

```

**functionHelper.js** - (need to add --docker if it is provided)

line 16:
`    const args = funOptions.runtime.startsWith("provided") ? ['invoke', 'local', '-f', funOptions.funName, '--docker'] : ['invoke', 'local', '-f', funOptions.funName];
`




That's it. on console, execute 
`sls offline`

it will start a Webserver in port 3000. Every call he builds the layer and execute.
Everything is working with a test php file.

Of course we need to Edit some things in serverless-offline and make a PR, but we can Definitely run it.

You can edit in the Google Sheets :)
