### ISSUE TITLE
Update path for with-config-file-scan-dir

### ISSUE THREAD

**Issue by Nyholm** [brefphp/bref#355]
We currently write: 
```   
--with-config-file-scan-dir=${INSTALL_DIR}/etc/php/conf.d:/var/task/php/conf.d 
```

This creates a folder in my docker image as `/opt/bref/etc/php/conf.d:/var/task/php/conf.d`. That is clearly not what we want. I **think** the correct solution is to write: 

```   
--with-config-file-scan-dir=${INSTALL_DIR}/etc/php/conf.d
--with-config-file-scan-dir=/var/task/php/conf.d 
```

But Im not sure how I would verify that.

**Comment by mnapoli** [comment]
To be clear:

> This creates a folder in my docker image

Can you confirm that there is no problem at runtime, and that the problem is that there is a broken directory created in the docker image?

I'm not against changing the line so that the directory isn't created. But I don't know if the alternative works as expected. Is the random directory a problem? Since it's just in the Docker image is there any negative impact?

**Comment by Nyholm** [comment]
> Can you confirm that there is no problem at runtime, and that the problem is that there is a broken directory created in the docker image?

Correct. 

>  Is the random directory a problem? Since it's just in the Docker image is there any negative impact?

I now think one can only have one directory as `with-config-file-scan-dir`. (I've done some testing).

Since the current implementation is broken, nobody relies on this feature. We also have no files created in `/opt/bref/etc/php/conf.d`. I suggest we change it to `/var/task/php/conf.d`. 

That means that I, as a user, can put ini files in `my-project/php/conf.d`.

**Comment by deleugpn** [comment]
I dont understand the issue. I already have ini files in `./php/conf.d/` and it works fine.

**Comment by Nyholm** [comment]
Hm, are you sure @deleugpn? And you have not specified a `PHP_INI_SCAN_DIR` parameter?

**Comment by deleugpn** [comment]
Where would I have PHP_INI_SCAN_DIR? Anybody using pdo_mysql or redis on Lambda is probably forced to have a ini file with the following content:

```
extension=pdo_mysql
extension=redis
```

The lambda doesn't work without it otherwise

**Comment by Nyholm** [comment]
You can define your sam template like: 

```yaml
AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Globals:
    Function:
        Environment:
            Variables:
                APP_ENV: prod
                APP_SECRET: 'foobar'
                PHP_INI_SCAN_DIR: /var/task/custom-php-folder-in-project-dir
               
Resources:
    Website:
        Type: AWS::Serverless::Function
        Code: ..
        Properties:
            FunctionName: 'my app'
       # ...
```

Then you can add your `php.ini` file in `/Users/tobias/project-dir/custom-php-folder-in-project-dir`. 

Do you mean that you never defined `PHP_INI_SCAN_DIR` and you are using whatever default value?
