### ISSUE TITLE
ApiGateway and Cognito Authorizer

### ISSUE THREAD

**Issue by starred-gijs** [brefphp/bref#382]
Hi all, I was experimenting with this package, and have a question. 

If I use Cognito user pool as Authorizer , eg 
```yaml
# partial:
    DemoApiGateway:
        Type: AWS::Serverless::Api
        Properties:
            StageName: dev
            Cors: "'*'"
            Auth:
                DefaultAuthorizer: MyCognitoAuthorizer
                Authorizers:
                    MyCognitoAuthorizer:
                        UserPoolArn: arn:aws:cognito-idp:{}:userpool/{poolid}
                        Identity:
                            Header: Authorization 
```
And the request contains a valid token, I can access the claim via the `$event`, so if I change the `PhpFpm::eventToFastCgiRequest` to include some code like this:
```php 
if (isset($event['requestContext']['authorizer']['claims']['sub'])) {
  $request->setCustomVar('REMOTE_USER', $event['requestContext']['authorizer']['claims']['sub']);
}
```
Does this even make sense? Are there better ways to let apigateway/congnito authorize the incoming requests, and also have the user available in the php request?

Would it be better to just decode the Authorization header in php and use the data from the JWT?
