### ISSUE TITLE
403 Forbidden

### ISSUE THREAD

**Issue by alcinovanrooyen** [brefphp/bref#385]
Hi,

I've deployed successfully.

Testing in Lambda Console works as well, but invoke from API Gateway causes this error:
```Fatal error: Uncaught Exception: Error while calling the Lambda runtime API: The requested URL returned error: 403 Forbidden in /var/task/vendor/bref/bref/src/Runtime/LambdaRuntime.php:268```

**Comment by mnapoli** [comment]
Hi, this error message is very surprising.

Is it just happening once or still happening? And just to be sure:

> Testing in Lambda Console works as well, but invoke from API Gateway causes this error:

Did you create 2 different lambdas (one for HTTP and one for console)?

**Comment by alcinovanrooyen** [comment]
Hi,

It's the same lambda, just added API Gateway trigger to it.

I've also noticed that the function does execute as Hello World gets echo'd in the logs, but with this error preceding it. 

Do you perhaps think this is a permission error - 403 Forbidden, perhaps IAM policy needed for API Gateway ?

**Comment by mnapoli** [comment]
OK this is not how things are supposed to run.

You need to have 2 different lambdas: one for HTTP, one for the console. Have a look here to create a HTTP lambda: https://bref.sh/docs/runtimes/http.html Make sure to have a separate lambda in `serverless.yml` with the correct configuration.

Let me know if you still have questions.

**Comment by leroy** [comment]
Hi,

I'm having the same issue, having followed the documentation on hosting a website.

Here's my configuration:

```yaml
service: app

provider:
  stage: staging
  name: aws
  region: eu-central-1
  runtime: provided
  environment:
    WP_ENV: ''
    WP_HOME: ''
    DB_HOST: ${ssm:/app/database/host}
    DB_NAME: ''
    DB_USER: ${ssm:/app/database/username}
    DB_PASSWORD: ${ssm:/app/database/password}
    S3_UPLOADS_KEY: ${ssm:/app/s3/key}
    S3_UPLOADS_SECRET: ${ssm:/app/s3/secret}
    S3_UPLOADS_BUCKET: '<bucket>'

plugins:
  - ./vendor/bref/bref

functions:
  wordpress:
    handler: index.php
    description: ''
    timeout: 28 # in seconds (API Gateway has a timeout of 29 seconds)
    layers:
      - ${bref:layer.php-73-fpm}
    events:
      - http: 'ANY /'
      - http: 'ANY /{proxy+}'
    vpc:
      securityGroupIds:
        - <security-group>
      subnetIds:
        - <subnet>
        - <subnet>
        - <subnet>

resources:
  Resources:
    # The S3 bucket that stores the assets
    Assets:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: <bucket>
    # The policy that makes the bucket publicly readable
    AssetsBucketPolicy:
      Type: AWS::S3::BucketPolicy
      Properties:
        Bucket: !Ref Assets # References the bucket we defined above
        PolicyDocument:
          Statement:
            - Effect: Allow
              Principal: '*' # everyone
              Action: 's3:GetObject' # to read
              Resource: 'arn:aws:s3:::<bucket>/*' # things in the bucket
```
