### ISSUE TITLE
Exception thrown unless Symfony cache directory is also changed to `/tmp/...`

### ISSUE THREAD

**Issue by nealio82** [brefphp/bref#39]
Following the example code for Symfony and deploying, the request fails with the response `{"message": "Internal server error"}`.

Checking CloudWatch logs shows 2 relevant entries:

```
Fatal error: Allowed memory size of 134217728 bytes exhausted (tried to allocate 20480 bytes) in /var/task/vendor/monolog/monolog/src/Monolog/Handler/StreamHandler.php on line 171
```

and

```
Fatal error: Allowed memory size of 134217728 bytes exhausted (tried to allocate 73728 bytes) in /var/task/vendor/symfony/debug/DebugClassLoader.php on line 145
```

Altering `Kernel.php` to include the following makes the problem go away

```
    public function getCacheDir()
    {
        // When on the lambda only /tmp is writable
        if (getenv('LAMBDA_TASK_ROOT') !== false) {
            return '/tmp/cache/'.$this->environment;
        }

        return $this->getProjectDir().'/var/cache/'.$this->environment;
    }
```

However...

Presumably setting the cache dir to Lambda's local `/tmp` kind-of defeats the point pre-warming the cache with the hooks in the `.bref.yml` file? The object is to avoid launching the application without the cache already in place, right?

`.bref.yml`:

```
hooks:
    build:
        - 'APP_ENV=prod php bin/console cache:clear --no-debug --no-warmup'
        - 'APP_ENV=prod php bin/console cache:warmup'
```

`serverless.yml`:

```
service: test

provider:
  name: aws
  runtime: nodejs6.10

package:
  exclude:
    - '*'
    - '**'
  include:
    - bref.php
    - 'src/**'
    - 'vendor/**'
    - composer.json # Symfony uses it to figure out the root directory
    - 'bin/**'
    - 'config/**'
    - 'var/cache/prod/**' # We want to deploy the production caches

functions:
  # By default we create one "main" function
  main:
    handler: handler.handle
    timeout: 20 # Timeout in seconds, the default is 6 seconds
    # The function will match all HTTP URLs
    events:
      - http: 'ANY /'
      - http: 'ANY {proxy+}'
    environment:
      APP_ENV: 'prod'
      APP_DEBUG: '0'
```

`bref.php`:

```
<?php

use App\Kernel;
use Bref\Bridge\Symfony\SymfonyAdapter;
use Symfony\Component\Debug\Debug;
use Symfony\Component\Dotenv\Dotenv;

require __DIR__.'/vendor/autoload.php';

Debug::enable();

// The check is to ensure we don't use .env in production
if (!isset($_SERVER['APP_ENV'])) {
    (new Dotenv)->load(__DIR__.'/.env');
}
if ($_SERVER['APP_DEBUG'] ?? ('prod' !== ($_SERVER['APP_ENV'] ?? 'dev'))) {
    umask(0000);
}
$kernel = new Kernel($_SERVER['APP_ENV'] ?? 'dev', (bool) ($_SERVER['APP_DEBUG'] ?? ('prod' !== ($_SERVER['APP_ENV'] ?? 'dev'))));

$app = new \Bref\Application;
$app->httpHandler(new SymfonyAdapter($kernel));
$app->cliHandler(new \Symfony\Bundle\FrameworkBundle\Console\Application($kernel));
$app->run();
```

I get the same behaviour with cloning the `mnapoli/bref-symfony-demo` repo and running `bref deploy`, and also with adding bref to a `symfony/website-skeleton` project.

**Comment by mnapoli** [comment]
Regarding the memory size problem, you could try increasing the memory limit of PHP by customizing the `php.ini` config, see https://github.com/mnapoli/bref#php-configuration to see how to set `php.ini` flags. However 128Mb seems already quite much, I'm surprised Symfony would consume that much.

> Presumably setting the cache dir to Lambda's local /tmp kind-of defeats the point pre-warming the cache with the hooks in the .bref.yml file? The object is to avoid launching the application without the cache already in place, right?

Agreed, this is not really efficient in production.

> I get the same behaviour with cloning the mnapoli/bref-symfony-demo repo and running bref deploy

This is surprising, but since I wrote (and tested) bref-symfony-demo we have added some extensions to PHP (mainly opcache, the other extensions are disabled by default), maybe that could be it? I don't really know much more right now I'll try to dig in.

**Comment by nealio82** [comment]
The first thing I tried was to increase the `memory_limit` (I should have mentioned that above, sorry!)

I think the cache is not being pre-warmed during the deploy process, because presumably it should exist and be readable if it has been!?

**Comment by mnapoli** [comment]
OK, I'll try to reproduce that tonight and see how it goes. Thanks for opening the issue!

**Comment by t-geindre** [comment]
We use our own kernel here, but since we also use `symfony/dependency-injection` we had to find a solution to pre-warm the cache, which essentially means to build and dump the container.

The only way we found to do so is to use relative paths.

For instance, we have a parameter `%cache_dir%`. Its value is always `./var/cache`. This allows us to dump the container before uploading it on lambda.

Our kernel always check that the current working directory is `$_ENV['LAMBDA_TASK_ROOT']`.

This works and we don't build the container on each execution. I think you could do something similar with  the Symfony kernel.

That beeing said, if you have a better solution, I would be very interested.

**Comment by mnapoli** [comment]
@nealio82 I've updated (`composer update`) everything to the latest versions on the symfony-demo project and redeployed, it still works: https://7oaryq3rzl.execute-api.eu-west-3.amazonaws.com/dev I don't understand what breaks for you 🤔 

@t-geindre Yes! I had issues with absolute/relative paths when deploying the API platform demo for my benchmarks. In the end I gave up and stored the cache in `/tmp` because I was not measuring the cold starts, so I just had to warmup the application and that's it. But this is not ideal at all.

**Comment by nealio82** [comment]
I probably won’t have time tonight, but i’ll create a version which breaks
/ screengrab reproduction steps

**Comment by nealio82** [comment]
Interestingly, if I clone the `mnapoli/bref-symfony-demo` repo, I get a different (and nicer) exception message about the cache.

The `symfony/website-skeleton` still gives me out of memory, but the SF demo now specifically mentions the cache.

I made a screencast here: https://youtu.be/Ar3USl8h8Ug

**Comment by mnapoli** [comment]
Thanks for the screencast! Could you try one last time `mnapoli/bref-symfony-demo` by running `composer update` before `bref deploy` to install the last version of Bref?

**Comment by nealio82** [comment]
FTR:
```
➜  bref-symfony-demo git:(master) ✗ composer update mnapoli/bref
Loading composer repositories with package information
Updating dependencies (including require-dev)
Nothing to install or update
Generating autoload files
Executing script cache:clear [OK]
```

**Comment by nealio82** [comment]
If I add the `cache` param to `config/packages/twig.yml` with the value of either `/tmp/...` or `false`, then everything works again.

```
twig:
    paths: ['%kernel.project_dir%/templates']
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    cache: '/tmp/twig'
```

see https://twig.symfony.com/doc/2.x/api.html#environment-options and http://symfony.com/doc/current/reference/configuration/twig.html#cache

However, I don't like setting `/tmp/...` in the twig config (I'll try to see if there's a Symfony parameter which allows us to reference it in the `'%parameter_name%'` style), and I don't know enough about Twig to tell if disabling the cache is a bad idea.

**Comment by mnapoli** [comment]
OK I think I remember now where the problem came from (when I tried deploying the API platform demo).

Some things in the Symfony cache are using absolute paths, as @t-geindre mentioned. You need to tweak Symfony and its config to force it to use relative paths (because the paths on your machine and on AWS lambda are different).

That works, except for Twig that IIRC uses `realpath()` as some point in the code (I think it's [here](https://github.com/twigphp/Twig/blob/84b2eb541026dbd39590ba80269ae7676b1bfc46/lib/Twig/Loader/Filesystem.php#L212)). Because of that call, a relative path is turned into an absolute path and it breaks things. I don't remember the details anymore though.

---

Also it is important to note that not all the Symfony cache is pregenerated, for example you have to put Doctrine's cache (which is not pregenerated) in `/tmp` manually.

Here is an example of what I did for Doctrine in `config/packages/doctrine.yaml`:

```yaml
parameters:
    writable_cache_dir: '/tmp/cache'

[…]

doctrine:
    orm:
        […]
        metadata_cache_driver:
            cache_provider: metadata_cache
        result_cache_driver:
            cache_provider: result_cache
        query_cache_driver:
            cache_provider: query_cache

[…]

doctrine_cache:
    providers:
        metadata_cache:
            aliases: [doctrine.orm.default_metadata_cache]
            file_system:
                directory: "%writable_cache_dir%/doctrine/metadata"
        result_cache:
            aliases: [doctrine.orm.default_result_cache]
            file_system:
                directory: "%writable_cache_dir%/doctrine/result"
        query_cache:
            aliases: [doctrine.orm.default_query_cache]
            file_system:
                directory: "%writable_cache_dir%/doctrine/query"
```

**Comment by nealio82** [comment]
Ok, so I assume that means at some point we _have_ to have a writeable filesystem in order for Twig to work properly?

However, that raises 2 questions:

1. Should the `Kernel.php` in the documentation be updated to change the cache dir to `/tmp` to make sure Twig can always write to it?
1. Why does your example work for you and not for me? You saw in the screencast that I made no adjustments to the example repo's code!

**Comment by nealio82** [comment]
Ok, I can make a PR for this tomorrow :)

**Comment by nealio82** [comment]
Workaround documentation added in #42

**Comment by mnapoli** [comment]
Does anyone here has a public repository to reproduce this?

**Comment by nealio82** [comment]
I can make one early next week (probably Monday)

**Comment by mnapoli** [comment]
For those reading this issue, I reproduced it when writing a simple Symfony 4 application, starting with Flex. I just have a base template (the layout) and a few pages that extend from that. I don't have time right now to create a whole repository to reproduce that but that can maybe be a starting point for others.

**Comment by nealio82** [comment]
Weirdly I tried yesterday; starting with Symfony 4 & extending a base template, then passing in some variables to render. I didn’t see the issue at all. (And i’m pretty sure the first time I saw the issue I didn’t even need to extend a base template)

**Comment by thibaudlemaire** [comment]
Hi!
[I personally chose to redirect Twig's cache](https://blog.theodo.com/2019/05/serverless-symfony-on-aws-lambda-with-bref/#edit-symfony-config)  to `config/packages/prod/twig.yaml` to be able to warm up other bundles.
```yaml
# config/packages/prod/twig.yaml
twig:
    cache: '/tmp/cache/twig'
```
 I know it's a temporary solution but I preferer doing this because making `/tmp` the default Symfony cache directory increases the cold start from 500ms to 2 seconds.  
I hope Twig's team will work on this problem to comply with the [Symfony4 best practices](http://fabien.potencier.org/symfony4-directory-structure.html#temporary-files-under-var) (var/cache should be read-only and warmable).
