### ISSUE TITLE
FPM docker issue

### ISSUE THREAD

**Issue by tiagobrito** [brefphp/bref#404]
Using a Symfony application (4.3) the only route that i'm able to match is `/`, besides this I only get:

` 2019/08/09 17:06:01 [error] 9#9: *6 open() "/var/task/public/ping" failed (2: No such file or directory), client: 172.24.0.1, server: php-docker.local, request: "GET /ping HTTP/1.1", host: "localhost:8000"`

my docker-compose.yml configuration is:

```yaml
version: "3.5"

services:
  web:
    image: bref/fpm-dev-gateway
    ports:
      - '8000:80'
    volumes:
      - .:/var/task
    depends_on:
      - php
    environment:
      HANDLER: public/index.php
      DOCUMENT_ROOT: public
  php:
    image: bref/php-73-fpm-dev
    volumes:
      - .:/var/task:ro

```
