### ISSUE TITLE
opcache_get_status() returns opcache_enabled = false

### ISSUE THREAD

**Issue by christoph-kluge** [brefphp/bref#439]
Hello everybody. I'm trying to measure and debug some performance issues and found out that opcache_enabled does return false. I'm kinda puzzled why this happens. Does someone have some hints for me?

My serverless.yml
```
functions:
    http:
        handler: public/lambda.php
        description: ''
        layers:
            - ${bref:layer.php-73}
        timeout: 3
        memorySize: 1024 # Overwrite the default memory size. Default is 1024
```

A simple handler which I'm using inside my app
```
class GetOpcacheHandler
{

    public function __invoke(Request $request)
    {
        $config = opcache_get_configuration();
        $status = opcache_get_status();

        return new JsonResponse([
            'is_cached' => opcache_is_script_cached(__FILE__),
            'config' => $config,
            'status' => $status,
        ]);
    }
}
```

And this is the response which I'm receiving:
```
{
	"is_cached": false,
	"config": {
		"directives": {
			"opcache.enable": true,
			"opcache.enable_cli": true,
			"opcache.use_cwd": true,
			"opcache.validate_timestamps": false,
			"opcache.validate_permission": false,
			"opcache.validate_root": false,
			"opcache.dups_fix": false,
			"opcache.revalidate_path": false,
			"opcache.log_verbosity_level": 1,
			"opcache.memory_consumption": 134217728,
			"opcache.interned_strings_buffer": 8,
			"opcache.max_accelerated_files": 10000,
			"opcache.max_wasted_percentage": 0.05,
			"opcache.consistency_checks": 0,
			"opcache.force_restart_timeout": 180,
			"opcache.revalidate_freq": 2,
			"opcache.preferred_memory_model": "",
			"opcache.blacklist_filename": "",
			"opcache.max_file_size": 0,
			"opcache.error_log": "",
			"opcache.protect_memory": false,
			"opcache.save_comments": true,
			"opcache.enable_file_override": false,
			"opcache.optimization_level": 2147401727,
			"opcache.lockfile_path": "\/tmp",
			"opcache.file_cache": "\/tmp",
			"opcache.file_cache_only": true,
			"opcache.file_cache_consistency_checks": true
		},
		"version": {
			"version": "7.3.7",
			"opcache_product_name": "Zend OPcache"
		},
		"blacklist": []
	},
	"status": {
		"opcache_enabled": false,
		"file_cache": "\/tmp",
		"file_cache_only": true
	}
}
```
