### ISSUE TITLE
Serverless plugin "./vendor/bref/bref" not found

### ISSUE THREAD

**Issue by claudiunicolaa** [brefphp/bref#453]
Hi,

I made the following steps:

1. Installed Symfony app using flex (`composer create-project symfony/skeleton xapp-api`)
2. Installed Serverless Framework (`npm install -g serverless`) and setup the credentials
3. Installed Bref into my project (`composer require bref/bref`)
4. Optimized the dependencies (`APP_ENV=prod composer install --no-dev --optimize-autoloader`)

When running the deploy process (`serverless deploy`), I'm getting the following error

```
Serverless Error ---------------------------------------

  Serverless plugin "./vendor/bref/bref" not found. Make sure it's installed and listed in the "plugins" section of your serverless config file.

  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Issues:        forum.serverless.com

  Your Environment Information -----------------------------
     OS:                     darwin
     Node Version:           8.16.0
     Serverless Version:     1.36.3
```

`serverless.yml` :

```
service: xapp-api

provider:
    name: aws
    region: us-east-1
    runtime: provided
    environment:
        # Symfony environment variables
        APP_ENV: prod

plugins:
    - ./vendor/bref/bref

functions:
    website:
        handler: public/index.php
        timeout: 28 # in seconds (API Gateway has a timeout of 29 seconds)
        layers:
            - ${bref:layer.php-73-fpm}
        events:
            -   http: 'ANY /'
            -   http: 'ANY /{proxy+}'
    console:
        handler: bin/console
        timeout: 120 # in seconds
        layers:
            - ${bref:layer.php-73} # PHP
            - ${bref:layer.console} # The "console" layer

```

`composer.json` snnipet:
```
...
"bref/bref": "^0.5.5",
...
```

vendor directory 
<img width="292" alt="Screenshot 2019-09-14 at 13 21 08" src="https://user-images.githubusercontent.com/15197275/64906728-aa5a8700-d6f2-11e9-88fe-e7e2d7c2a66e.png">
