### ISSUE TITLE
Laravel does not work when creating a local development environment with docker-compose

### ISSUE THREAD

**Issue by YuK1Game** [brefphp/bref#470]
Hi.

I succeeded in running Laravel with Lambda.
However, running in a local development environment has not been successful.

An error is displayed.
```
file_put_contents(/var/task/storage/framework/cache/data/4f/fd/4ffd260b4993822a126394e6169ea67cd63b2c86): failed to open stream: No such file or directory
```

I have set up referring to the following,
```
$app->useStoragePath($_ENV['APP_STORAGE'] ?? $app->storagePath());
```
is described in `bootstrap/app.php`.

https://bref.sh/docs/frameworks/laravel.html

I deployed `$_ENV`
```
array(0) {}
```

How do I get an ENV?

docker-compose.yml
```
version: "3.5"

services:
    web:
        image: bref/fpm-dev-gateway
        ports:
            - '8192:80'
        volumes:
            - .:/var/task
        depends_on:
            - php
        environment:
            HANDLER: public/index.php
            DOCUMENT_ROOT: public

    php:
        image: bref/php-73-fpm-dev
        volumes:
            - .:/var/task:ro
```

Thanks.

**Comment by YuK1Game** [comment]
Temporary solution.

docker-compose.yml

```
php:
    image: bref/php-73-fpm-dev
    volumes:
        - .:/var/task:ro
```
to
```
php:
    image: bref/php-73-fpm-dev
    volumes:
        - .:/var/task
```

Is it impossible to set the temporary directory to `/tmp`?
