### ISSUE TITLE
[SOLVED] Deploy with Bitbucket Pipeline

### ISSUE THREAD

**Issue by robersonfaria** [brefphp/bref#523]
It took me a while to understand what was happening so I decided to share here.
To deploy with bitbucket pipeline it is necessary to split the deploy into 2 steps:
1) download composer dependencies
2) run serverless deploy

Because the steps are performed separately, you must share the _vendor_ and _bootstrap/cache_ artifacts.

So the bitbucket-pipelines.yml file looks like this:

```
pipelines:
  branches:
    master:
      - step:
          name: Composer install
          image: php:7.3
          caches:
            - composer
          script:
            - apt-get update && apt-get install -y unzip
            - curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
            - composer install --prefer-dist --optimize-autoloader --no-dev
          artifacts:
            - vendor/**
            - bootstrap/cache/*.php
      - step:
          name: Deploy Lambda
          deployment: production
          image: node:11.13.0-alpine
          trigger: manual
          caches:
            - node
          script:
            - apk add python3
            - npm install -g serverless
            - serverless config credentials --stage prod --provider aws --key ${AWS_DEV_LAMBDA_KEY} --secret ${AWS_DEV_LAMBDA_SECRET}
            - serverless deploy --stage prod
```

I always deploy bitbucket, but it's the first time with serverless. The difference is that on a normal server (write permission) if not send the _bootstrap/cache_ files laravel generates in the first run, as in lambda does not have permission in this folder happens the following error:

`"[2019-12-24 10:50:21] production.ERROR: The /var/task/bootstrap/cache directory must be present and writable. {"exception":"[object] (Exception(code: 0): The /var/task/bootstrap/cache directory must be present and writable. at /var/task/vendor/laravel/framework/src/Illuminate/Foundation/PackageManifest.php:168)"`

I  hope this helps others with the same problem save time.

Thanks.
