### ISSUE TITLE
Url broken when using cloudfront in front of lambda

### ISSUE THREAD

**Issue by jmolinap** [brefphp/bref#535]
Hi, great package.

Currently i am testing an app built with symfony but redirections/url generation are broken.

Redirecting to a non absolute url within the app, generates a url of the type

somerandom-url.execute.aws-region.com

#67  seems to be related.

Any pointers on how to fix?

Thanks.

**Comment by mnapoli** [comment]
Hi, this is a limitation of CloudFront: the host header is not forwarded by CloudFront.

That means that the HTTP request landing in API Gateway does not contain the host from CloudFront, but instead contains the API Gateway URL.

Possible solutions:

- force the HTTP header `Host` to a specific value (your domain name) in your CloudFront configuration
- force your app/framework to use a specific domain name

**Comment by jmolinap** [comment]
Thanks for the proposed solutions.

Any doc that i can check to achieve properly?, i have tried to set up a lambda function to modify the header but it messes up the app, after setting up it returns a 403 forbidden, disabling it makes it work again - page loads (with broken urls)

Thanks.

**Comment by mnapoli** [comment]
Right, sorry I wasn't a little more explicit.

Here is a solution to configure the CloudFront CDN in serverless.yml:

```yaml
Origins:
  # The website (AWS Lambda)
  - Id: Website
    DomainName: '#{ApiGatewayRestApi}.execute-api.#{AWS::Region}.amazonaws.com'
    OriginPath: '/dev'
    CustomOriginConfig:
      OriginProtocolPolicy: 'https-only' # API Gateway only supports HTTPS
    OriginCustomHeaders:
      - HeaderName: 'X-Forwarded-Host'
        HeaderValue: 'your-domain-here.com'
```

Then you need to configure your framework to take the `X-Forwarded-Host` header into account.

For Symfony, have a look at https://symfony.com/doc/current/deployment/proxies.html#but-what-if-the-ip-of-my-reverse-proxy-changes-constantly
Though it's interesting to see that Symfony mentions CloudFront, so maybe you can skip the configuration above and try this directly: https://symfony.com/doc/current/deployment/proxies.html#custom-headers-when-using-a-reverse-proxy (please report if it works)

For Laravel it seems that [this package](https://github.com/fideloper/TrustedProxy) is now installed by default. You can configure it: https://github.com/fideloper/TrustedProxy#configure-trusted-proxies

In case you wonder if the CloudFront proxy has an IP address: no. This is why in those docs above you often need to use `*`.

Hope that helps, sorry I don't have more time at the moment, but please report whatever works or breaks.
