### ISSUE TITLE
Update the documentation regarding HTTPS redirections with API Gateway

### ISSUE THREAD

**Issue by Nemo64** [brefphp/bref#546]
In the documentation it says that a disadvantage of using the api gateway directly is that there is no https redirect. Ref: https://bref.sh/docs/websites.html#architectures

I'm new to aws but I basically used the api gateway and configured a custom domain and I noticed that there is a https redirect. Try: `curl -v 'http://symfony-bootstrap.marco.zone'`

Now I'm questioning: is that new and not documented? It even works when i'm accessing it without the custom domain: `curl -v 'http://v6xdpof3f5.execute-api.eu-central-1.amazonaws.com/dev/'`

The http response say's it uses CloudFront but I haven't configured anything in that sense (yet). Here is my serverless file:
```
service: symfony-bootstrap

provider:
    name: aws
    region: eu-central-1
    runtime: provided
    # https://serverless.com/framework/docs/providers/aws/events/apigateway/#share-api-gateway-and-api-resources
    apiGateway:
        # https://docs.aws.amazon.com/apigateway/latest/developerguide/api-gateway-gzip-compression-decompression.html
        minimumCompressionSize: 1024
    environment:
        # Symfony environment variables
        APP_ENV: prod
        DATABASE_URL: '[removed]'
        MAILER_DSN: 'null://null'

plugins:
    - ./vendor/bref/bref

package:
    exclude:
        - bin/.phpunit/**
        - node_modules/**
        - public/build/**
        - '!public/build/manifest.json'
        - tests/**

functions:
    website:
        handler: public/index.php
        timeout: 28 # in seconds (API Gateway has a timeout of 29 seconds, so 28 is the maximum that makes sense)
        layers:
            - ${bref:layer.php-73-fpm}
        events:
            -   http: 'ANY /'
            -   http: 'ANY /{proxy+}'
    console:
        handler: bin/console
        timeout: 120 # in seconds
        layers:
            - ${bref:layer.php-73} # PHP
            - ${bref:layer.console} # The "console" layer

resources:
    Resources:
        # The S3 bucket that stores the assets
        # https://symfony-bootstrap-assets.s3.amazonaws.com/
        Assets:
            Type: AWS::S3::Bucket
            Properties:
                BucketName: symfony-bootstrap-assets
        # The policy that makes the bucket publicly readable
        AssetsBucketPolicy:
            Type: AWS::S3::BucketPolicy
            Properties:
                Bucket: !Ref Assets # References the bucket we defined above
                PolicyDocument:
                    Statement:
                        -   Effect: Allow
                            Principal: '*' # everyone
                            Action: 's3:GetObject' # to read
                            Resource: 'arn:aws:s3:::symfony-bootstrap-assets/*' # things in the bucket
```
