### ISSUE TITLE
Internal Server Error when pthreads is enabled

### ISSUE THREAD

**Issue by AVONnadozie** [brefphp/bref#547]
While trying to enable some extentions for a Lumen project, I created a .ini file in `deploy/php/conf.d` with reference to the [docs](https://bref.sh/docs/environment/php.html#extensions).
Content as follows:
```
extension=intl
;extension=apcu
extension=redis
;extension=pdo_pgsql
extension=pdo_mysql
;extension=mongodb
extension=pthreads
extension=imagick
```
and updated the provider section in `serverless.yml` to this
```
provider:
  name: aws
  region: eu-west-1
  runtime: provided
  # The stage of the application, e.g. dev, prod, staging… ('dev' by default)
  stage: prod
  environment:
    # Laravel environment variables
    APP_STORAGE: '/tmp'
    PHP_INI_SCAN_DIR: '/var/task/deploy/php/conf.d'
```

I got an Internal Server Error with this log on CloudWatch
```
PHP Fatal error:  The fpm-fcgi SAPI is not supported by pthreads in Unknown on line 0
```

Commented out the `extension=pthreads` line and everything works fine.

The app was deployed using bref/dev-env image on Gitlab CI, and a php-73-fpm runtime.
