### ISSUE TITLE
`PHP Fatal error:  Uncaught TypeError: Argument 1 passed to Bref\Runtime\LambdaRuntime::processNextEvent() must be callable, int given

### ISSUE THREAD

**Issue by pc-magas** [brefphp/bref#553]
I made a simple bref application:

```
<?php declare(strict_types=1);

require __DIR__.'/vendor/autoload.php';

lambda(function ($event) {
    return 'Hello ' . ($event['name'] ?? 'world');
});
```

And I use the following `serverless.yml` configuration:

```
service: app

provider:
    name: aws
    region: eu-central-1
    runtime: provided
    stage: ${opt:stage,'local'}

custom: 
    stages:
    - local
    - staging
    - prod

deploymentBucket:
    name: php-lambdas.etable.gr
    serverSideEncryption: AES256


package:
    exclude:
        - '.gitignore'

plugins:
    - ./vendor/bref/bref
    - /usr/lib/node_modules/serverless-stage-manager

functions:
    dummy:
        handler: index.php
        name: Dummy-${self:provider.stage}
        description: 'Dummy Lambda'
        layers:
            - 'arn:aws:lambda:eu-central-1:209497400698:layer:php-73:16'

```

But the lambda fails to run locally using the command:

```
serverless invoke local -f dummy -s local --data '{}'
```

Because it shows the following error:

```
PHP Fatal error:  Uncaught TypeError: Argument 1 passed to Bref\Runtime\LambdaRuntime::processNextEvent() must be callable, int given, called in /opt/bref/bootstrap.php on line 33 and defined in /var/task/vendor/bref/bref/src/Runtime/LambdaRuntime.php:86
Stack trace:
#0 /opt/bref/bootstrap.php(33): Bref\Runtime\LambdaRuntime->processNextEvent(1)
#1 {main}
  thrown in /var/task/vendor/bref/bref/src/Runtime/LambdaRuntime.php on line 86

Fatal error: Uncaught TypeError: Argument 1 passed to Bref\Runtime\LambdaRuntime::processNextEvent() must be callable, int given, called in /opt/bref/bootstrap.php on line 33 and defined in /var/task/vendor/bref/bref/src/Runtime/LambdaRuntime.php:86
Stack trace:
#0 /opt/bref/bootstrap.php(33): Bref\Runtime\LambdaRuntime->processNextEvent(1)
#1 {main}
  thrown in /var/task/vendor/bref/bref/src/Runtime/LambdaRuntime.php on line 86
```

Do you have any idea why that happens?
