### ISSUE TITLE
Error: Couldn't find valid bootstrap(s): [/var/task/bootstrap /opt/bootstrap] using bref 5.13.0

### ISSUE THREAD

**Issue by pc-magas** [brefphp/bref#554]
I have made the following lambda:

```
declare(strict_types=1);

require __DIR__.'/vendor/autoload.php';

lambda(function ($event) {
    return 'Hello ' . ($event['name'] ?? 'world');
});
```
And I use the following serverless.yml config:

```
service: app

provider:
    name: aws
    region: eu-central-1
    runtime: provided
    stage: ${opt:stage,'local'}

custom: 
    stages:
    - local
    - staging
    - prod

deploymentBucket:
    name: php-lambdas.etable.gr
    serverSideEncryption: AES256


package:
    exclude:
        - '.gitignore'

plugins:
    - ./vendor/bref/bref
    - /usr/lib/node_modules/serverless-stage-manager

functions:
    dummy:
        handler: index.php
        name: Dummy-${self:provider.stage}
        description: 'Dummy Lambda'
        layers:
            - 'arn:aws:lambda:eu-central-1:209497400698:layer:php-73:15'
```

And I try to invoke it localy via:

```
serverless invoke local -f dummy -s local --data '{}'
```

But I get the following error:

```
{"errorType":"exitError","errorMessage":"RequestId: 99d036d8-3548-178d-9cb6-bff901256d21 Error: Couldn't find valid bootstrap(s): [/var/task/bootstrap /opt/bootstrap]"}
```
As you can see I use the `arn:aws:lambda:eu-central-1:209497400698:layer:php-73:15` which is the latest stable according to https://runtimes.bref.sh/?region=eu-central-1&version=0.5.13

So do you have any idea about the cause of this problem?
