### ISSUE TITLE
schedule rate(1 minutes) error.

### ISSUE THREAD

**Issue by YuK1Game** [brefphp/bref#570]
Hi.

function event schedule settings.
`rate(1 minutes)` is errors.

```
An error occurred: ArtisanLambdaFunction - 1 validation error detected: Value 'artisan schedule:run' at 'handler' failed to satisfy constraint: Member must satisfy regular expression pattern: [^\s]+ (Service: AWSLambdaInternal; Status Code: 400; Error Code: ValidationException;
```

OK patterns.
```
  artisan:
    handler: "schedule"
    timeout: 120
    layers:
      - ${bref:layer.php-73}
      - ${bref:layer.console}
    events:
      - schedule: rate(5 minutes)
```

```
  artisan:
    handler: "schedule"
    timeout: 120
    layers:
      - ${bref:layer.php-73}
      - ${bref:layer.console}
    events:
      - schedule: rate(10 minutes)
```

NG pattern.

```
  artisan:
    handler: "schedule"
    timeout: 120
    layers:
      - ${bref:layer.php-73}
      - ${bref:layer.console}
    events:
      - schedule: rate(1 minutes)
```
AWS supports one minute intervals.

bref ver: 0.5.15

thanks.
