### ISSUE TITLE
bref's PHP FInfo detects picture as application/octet-stream

### ISSUE THREAD

**Issue by patrickbussmann** [brefphp/bref#581]
I have a interesting behaviour.

On my linux and windows development machines the picture is detected as "image/jpeg".
And when I upload the same file to my Lambda Serverless bref environment it is detected as "application/octet-stream".

I found out that the problem is this small line of code.

```
if (false === $finfo = new \finfo(FILEINFO_MIME_TYPE)) {
    return null;
}

return $finfo->path($path);
```

Linux & Windows returning: image/jpeg
bref PHP7.3-FPM returning: image/jpeg

```yaml
functions:
    website:
        handler: public/index.php
        memorySize: 1024
        timeout: 28 # in seconds (API Gateway has a timeout of 29 seconds)
        layers:
            - ${bref:layer.php-73-fpm}
        events:
            -   http: 'ANY /'
            -   http: 'ANY /{proxy+}'
```

Attached you can find the example file.
![a](https://user-images.githubusercontent.com/15617021/76164432-22a87f00-614f-11ea-8d79-7802d7916750.jpg)
