### ISSUE TITLE
headers key is missing in API-Gateway proxy response

### ISSUE THREAD

**Issue by roenschg** [brefphp/bref#587]
I created the following lambda with serverless:

```
api_upload:
    handler: src/api_upload/index.php
    layers:
      - ${bref:layer.php-73-fpm}
    events:
      - http:
          path: /upload
          method: get
          authorizer:
            name: authorizer
            type: request
            authorizerResultTtlInSeconds: 0
          cors: true
```

While testing it I get the following error:
```
Execution failed due to configuration error: Malformed Lambda proxy response
```

The return json looks like this:
```
{
   "isBase64Encoded":false,
   "statusCode":200,
   "multiValueHeaders":{
      "x-powered-by":"PHP\/7.3.7",
      "content-type":"text\/html; charset=UTF-8"
   },
   "body":"..."
}
```
As noted in the AWS documentation, the headers key is required but missing:
https://aws.amazon.com/premiumsupport/knowledge-center/malformed-502-api-gateway/

The correct json is also described here:
https://docs.aws.amazon.com/apigateway/latest/developerguide/set-up-lambda-proxy-integrations.html#api-gateway-simple-proxy-for-lambda-output-format

I don't have that error in my other lambdas, and was not able to undestand why it is using multiValueHeaders but all others use the headers key.

Can someone give me a clue on that?
