### ISSUE TITLE
document CloudWatch alarms

### ISSUE THREAD

**Issue by Nemo64** [brefphp/bref#607]
I'd like documentation about CloudWatch alarms.

I'm not fluent in that topic yet but i'll have to experiment with it in the future so I can add something in the coming weeks.

I mean something like this CloudFormation template:
```yaml
        EmailTopic:
            Type: AWS::SNS::Topic
            Properties:
                Subscription:
                    -   Endpoint: name@example.com
                        Protocol: "email"
        Alarm:
            Type: AWS::CloudWatch::Alarm
            Properties:
                ActionsEnabled: true
                AlarmActions:
                    - !Ref EmailTopic
                AlarmDescription: HTTP 4xx
                AlarmName: HTTP 4xx
                ComparisonOperator: GreaterThanThreshold
                DatapointsToAlarm: 1
                EvaluationPeriods: 1
                Dimensions:
                    - Name: ApiName
                      Value: ${self:provider.stage}-${self:service}
                MetricName: 4XXError
                Namespace: AWS/ApiGateway
                Period: 60
                Statistic: Sum
                Threshold: 1
                TreatMissingData: notBreaching
```
