### ISSUE TITLE
Laravel artisan command for migration not working

### ISSUE THREAD

**Issue by mantey-github** [brefphp/bref#622]
Hi.

I want to run the laravel artisan command for migration. Tried several times it does not work. However, just running the artisan command with no option works.

Eg:
This works:-  `vendor/bin/bref cli creditlocus-blog-dev-artisan`
This does not work:-  `vendor/bin/bref cli creditlocus-blog-dev-artisan migrate`

The settings for `serverless.yml` 
```
service: creditlocus-blog

provider:
  name: aws
  region: us-east-1
  runtime: provided
  environment:
    APP_ENV: production
    APP_DEBUG: true # set to false when moving to production
    LOG_CHANNEL: stderr # this will send logs to CloudWatch automatically
    SESSION_DRIVER: cookie # to avoid writing sessions to disk
    VIEW_COMPILED_PATH: /tmp/storage/framework/views
    DB_CONNECTION: mysql
    DB_HOST: xxxxxxx
    DB_PORT: xxxxxxx
    DB_DATABASE: xxxxxxx
    DB_USERNAME: xxxxxxx
    DB_PASSWORD: xxxxxxx
  vpc:
    securityGroupIds:
    - sg-xxxxxxx
    subnetIds:
    - subnet-xxxxxxx
    - subnet-xxxxxxx
    - subnet-xxxxxxx
    - subnet-xxxxxxx
    - subnet-xxxxxxx
    - subnet-xxxxxxx

plugins:
- ./vendor/bref/bref

package:
  exclude:
  - node_modules/**
  - public/storage
  - storage/**
  - tests/**

functions:
  website:
    handler: public/index.php
    timeout: 28 # in seconds (API Gateway has a timeout of 29 seconds)
    layers:
    - ${bref:layer.php-73-fpm}
    events:
    -   http: 'ANY /'
    -   http: 'ANY /{proxy+}'
  artisan:
    handler: artisan
    timeout: 120 # in seconds
    layers:
    - ${bref:layer.php-73} # PHP
    - ${bref:layer.console} # The "console" layer
```

Snapshot of the error:

<img width="1362" alt="Screen Shot 2020-04-16 at 5 53 44 AM" src="https://user-images.githubusercontent.com/39991756/79419605-abb0a280-7fa6-11ea-8341-132a9178b7cc.png">

Thanks
