### ISSUE TITLE
Internal server error after download on s3 bucket from aws lambda , PHP

### ISSUE THREAD

**Issue by juanfrag** [brefphp/bref#624]
I created aws lambda function based on laravel framework using bref. Link: https://bref.sh

this is my code to download using media library spartie

`$mediaItem = Media::where('model_id',$id)->where('model_type','App\MODEL')->first();`

`return $mediaItem;`

My configuration is

```
AWS_ACCESS_KEY_ID=XXXXXXXXXXXXXXXXXX
AWS_SECRET_ACCESS_KEY=XXXXX+XXXXXXXX
AWS_DEFAULT_REGION=us-east-1
AWS_BUCKET=my-bucket
```

When I download file locally all work perfectly, but when I try to download on s3 in lambda function I got error:

{ "message" : "Internal server error" }

I use this package aws:

league/flysystem-aws-s3-v3 ~1.0

my serverless.yaml
```

service: serverless-api

provider:
    name: aws
    region: eu-central-1
    runtime: provided
    environment:
        APP_ENV: production
    iamRoleStatements:
      - Effect: Allow
        Action: 
          - s3:*
        Resource: 'arn:aws:s3:::bucket/*'       

plugins:
    - ./vendor/bref/bref

package:
  exclude:
    - node_modules/**
    - public/storage
    - storage/**
    - tests/**
    - .env
 functions:
    website:
        handler: public/index.php
        timeout: 28 # in seconds (API Gateway has a timeout of 29 seconds)
        layers:
            - arn:aws:lambda:eu-central-1:209497400698:layer:php-72-fpm:23
        events:
            -   http: 'ANY /'
            -   http: 'ANY /{proxy+}'
    artisan:
        handler: artisan
        timeout: 120 # in seconds
        layers:
            - arn:aws:lambda:eu-central-1:209497400698:layer:php-72:22
            - arn:aws:lambda:eu-central-1:209497400698:layer:console:22
```
also i assign role for s3 , But I have no idea how it's the problem .

thank you .

**Comment by pmayet** [comment]
Hi Juan,

I use Spatie MediaLibrary with no problem with on AWS Lambda.

Can you change the var APP_DEBUG to true in your environment or not ?

Patrice

**Comment by juanfrag** [comment]
Hi Patrice 
yes , my var APP_DEBUG is true , but not showing any log o any detail error , only the message internal error server  , i think the problem is permission maybe

**Comment by pmayet** [comment]
Juan,

Do you have follow this : https://bref.sh/docs/frameworks/laravel.html ?

**Comment by juanfrag** [comment]
Patrice , 

yes i'm following this tutorial , the others endpoints works perfectly , my only problem is download a single file in my s3 bucket . locally works but  not in lambda

**Comment by pmayet** [comment]
Juan,

I think the problem is due to the description rights of the logs. Can you
just test Log::info on a script that is currently running?

**Comment by juanfrag** [comment]
Patrice , 

just right now i comment this line 
```
   $mediaItem = Media::where('model_id',$id)->where('model_type','App\QuoteV2')->first();
      return response()->json($mediaItem);
    //return $mediaItem; // comment this line

```
and the output is my register of table media , the filesystem disk is : 

```
    's3' => [
      'driver' => 's3',
      'key' => 'AKIAXXXXXXXXXXXXX',
      'root' => '/pdf_api/',
      'secret' => '+xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx',
      'region' => 'eu-central-1',
      'bucket' => 'name-bucket',
    ],  
```

**Comment by pmayet** [comment]
What is your LOG_CHANNEL ?

**Comment by juanfrag** [comment]
Patrice , 

 LOG_CHANNEL = stderr

**Comment by mnapoli** [comment]
> but not showing any log o any detail error

Are you looking into the Lambda logs? (i.e. CloudWatch) Because when you get `internal server errors`, the logs are displayed in CloudWatch, not in the web page.

Try running `vendor/bin/bref dashboard`, it will help you see the logs (you need to be on the latest Bref version).

**Comment by mantey-github** [comment]
@juanfrag @mnapoli currently facing the same issue when sending am email with the Amazon SES driver from the Amazon AWS SDK for PHP in laravel. Its timeout and then I get `{"message": "Internal server error"}`. But It works perfectly and I get the email when running the app locally

From CloudWatch;

```
(745214a4-1617-4a5d-bccd-520ca262253c) Endpoint response body before transformations: [Binary Data]
(745214a4-1617-4a5d-bccd-520ca262253c) Lambda execution failed with status 200 due to customer function error: 2020-04-17T12:34:58.704Z f995c2c0-e6d3-4d66-b045-736dc1b13759 Task timed out after 28.03 seconds. Lambda request id: f995c2c0-e6d3-4d66-b045-736dc1b13759
(745214a4-1617-4a5d-bccd-520ca262253c) Method completed with status: 502

```

**Comment by mnapoli** [comment]
@mantey-github this is not the same problem, please open a separate issue or try to get community support in the Slack channel.

**Comment by juanfrag** [comment]
Hi Matthieu thanks for asking , 

From CloudWatch , 
```

20:47:29
START RequestId: ad938623-c6e8-45c6-8673-a6cbd2d447e0 Version: $LATEST

20:47:57
END RequestId: ad938623-c6e8-45c6-8673-a6cbd2d447e0

20:47:57
REPORT RequestId: ad938623-c6e8-45c6-8673-a6cbd2d447e0 Duration: 28028.19 ms Billed Duration: 28400 ms Memory Size: 1024 MB Max Memory Used: 106 MB Init Duration: 344.08 ms

20:47:57
2020-04-16T20:47:57.210Z ad938623-c6e8-45c6-8673-a6cbd2d447e0 Task timed out after 28.03 seconds

20:47:57
[16-Apr-2020 20:47:57] NOTICE: fpm is running, pid 9

20:47:57
[16-Apr-2020 20:47:57] NOTICE: ready to handle connections
```

**Comment by juanfrag** [comment]
I think we are having a time out connecting to S3, I believe it could be related to permission
So ,  I'm trying t to run this command ` vendor/bin/bref dashboard`    and update bref if necessary

**Comment by victormacko** [comment]
Have you tried downloading a smaller file? ... or at least eliminated the chance it is in-fact a permission problem?
I'm guessing you're using dummy data in the config you've included, but make sure "Resource: 'arn:aws:s3:::bucket/*'" has your bucket-name in there instead of "bucket"

**Comment by juanfrag** [comment]
Hi victor , 

yes i'm using dummy data in Resource: 'arn:aws:s3:::my-name-bucket/*'" , and the size file is 565 kb , locally works , i'm using laravel

**Comment by juanfrag** [comment]
Hi everybody  , first of all  thanks for your time for helping me .
Finally I've found the solution , I am  running the function lambda in a vpc , but the vpc does not  have permission to access the s3 service so I followed this guide.

https://aws.amazon.com/es/blogs/aws/new-vpc-endpoint-for-amazon-s3/

and I ran into another error , By default API Gateway does not support binary HTTP requests or responses like images, PDF, binary files .

so I changed the serverless.yml like the documentation of bref
```
    apiGateway:
        binaryMediaTypes:
            - '*/*'
    environment:
        BREF_BINARY_RESPONSES: 1
```
and now it works perfectly . 

Thanks so much
