### ISSUE TITLE
Internal server error response sending mail with SES Driver from AWS Lambda, Laravel

### ISSUE THREAD

**Issue by mantey-github** [brefphp/bref#625]
Hi,

Working with Laravel framework using bref. Link: https://bref.sh to send an email. I'm using `AWS SES` as my mail driver. 

Summary;
When a user login with an email I send the user a signed URL to their email. This feature works locally with mail `MAIL_DRIVER=ses.`

But testing the application on AWS Lambda I get the error;
`{ "message" : "Internal server error" }`

Error from Cloudwatch;
```
Invoke Error	
{
    "errorType": "Bref\\Event\\Http\\FastCgi\\FastCgiCommunicationFailed",
    "errorMessage": "Error communicating with PHP-FPM to read the HTTP response. A root cause of this can be that the Lambda (or PHP) timed out, for example when trying to connect to a remote API or database, if this happens continuously check for those! Original exception message: hollodotme\\FastCGI\\Exceptions\\TimedoutException Read timed out",
    "stack": [
        "#0 /var/task/vendor/bref/bref/src/Event/Http/HttpHandler.php(22): Bref\\Event\\Http\\FpmHandler->handleRequest(Object(Bref\\Event\\Http\\HttpRequestEvent), Object(Bref\\Context\\Context))",
        "#1 /var/task/vendor/bref/bref/src/Runtime/LambdaRuntime.php(104): Bref\\Event\\Http\\HttpHandler->handle(Array, Object(Bref\\Context\\Context))",
        "#2 /opt/bootstrap(35): Bref\\Runtime\\LambdaRuntime->processNextEvent(Object(Bref\\Event\\Http\\FpmHandler))",
        "#3 {main}"
    ]
}
```

I use this package was:
` "aws/aws-sdk-php": "~3.0",`

serverles.yml;
```
org: xxxxxxxxxx
app: xxxxxxxxxx
service:xxxxxxxxxx

provider:
  name: aws
  region: us-east-1
  runtime: provided
  environment:
    APP_NAME: xxxxxxxxxx
    APP_ENV: production
    APP_KEY: xxxxxxxxxx
    APP_DEBUG: true # set to false when moving to production
    ASSET_URL: xxxxxxxxxx
    LOG_CHANNEL: stderr
    SESSION_DRIVER: cookie
    VIEW_COMPILED_PATH: /tmp/storage/framework/views
    DB_CONNECTION: mysql
    DB_HOST: xxxxxxxxxx
    DB_PORT: 3306
    DB_DATABASE: xxxxxxxxxx
    DB_USERNAME: xxxxxxxxxx
    DB_PASSWORD: xxxxxxxxxx
    BLOG_AWS_ACCESS_KEY_ID: xxxxxxxxxx
    BLOG_AWS_SECRET_ACCESS_KEY: xxxxxxxxxx
    BLOG_AWS_DEFAULT_REGION: us-east-1
    BLOG_AWS_DEFAULT_S3_REGION: us-east-2
    BLOG_AWS_BUCKET: xxxxxxxxxx
    MAIL_DRIVER: ses
    MAIL_FROM_ADDRESS: xxxxxxxxxx
    MAIL_FROM_NAME: xxxxxxxxxx
    FILESYSTEM_DRIVER: s3
    FILESYSTEM_CLOUD: s3
  vpc:
    securityGroupIds:
    - sg-xxxxxxxxxx
    subnetIds:
    - subnet-xxxxxxxxxx
    - subnet-xxxxxxxxxx
    - subnet-xxxxxxxxxx
    - subnet-xxxxxxxxxx
    - subnet-xxxxxxxxxx
    - subnet-xxxxxxxxxx
  apiGateway:
    binaryMediaTypes:
    - '*/*'
    environment:
      BREF_BINARY_RESPONSES: 1

plugins:
- ./vendor/bref/bref

package:
  exclude:
  - node_modules/**
  - public/storage
  - storage/**
  - tests/**

functions:
  website:
    handler: public/index.php
    timeout: 300 # in seconds (API Gateway has a timeout of 29 seconds)
    layers:
    - ${bref:layer.php-73-fpm}
    events:
    -   http: 'ANY /'
    -   http: 'ANY /{proxy+}'
  artisan:
    handler: artisan
    timeout: 120 # in seconds
    layers:
    - ${bref:layer.php-73} # PHP
    - ${bref:layer.console} # The "console" layer

```
I increased the function `website` timeout to 300 seconds but still does not work.
Thank You .
