### ISSUE TITLE
Bug: Propagate the tracing header correctly 

### ISSUE THREAD

**Issue by viezel** [brefphp/bref#632]
I believe that I found a bug in the custom runtime. When using the AWS X-Ray features of Lambda, we need certain headers to know when the X-Ray tracing is activated. These headers are not added to. the Bref runtime. 

The AWS tracing header `X-Amzn-Trace-Id` is not correctly propagated. 
See https://docs.aws.amazon.com/lambda/latest/dg/runtimes-custom.html under **Processing Tasks**

Today we get:

```
X-AMZN-TRACE-ID: Root=1-5e724476-c67b46bf2d130f10d11a427d
```

But should get:

```
X-AMZN-TRACE-ID: Root=1-5e724476-c67b46bf2d130f10d11a427d;Parent=2981f7c8188419dc;Sampled=0
```

We are missing the `Parent=` and `Sampled=`.

Secondly, we are missing the `_X_AMZN_TRACE_ID` environment variable - that according to the AWS docs should be the same value as the header.

**Comment by viezel** [comment]
I should say that if I create a `nodejs` runtime it works fine. Its just the custom runtime that misses these headers. 
I created a package that support XRay tracing in PHP. And the official X-Ray SDK from AWS uses those `Parent` and `Sampled` information to collect samplings of the requests.

**Comment by mnapoli** [comment]
Thanks, could it be that the `;` makes that header split in multiple values and we don't support it correctly? 🤔 

Also could you specify which runtime you are using?

**Comment by deleugpn** [comment]
I have used the XRay Daemon with PHP and I did not face the issue reported here. Have you checked that you enabled XRay Tracing on your Lambda?

Here's my SAM Template

```
AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31
Description: AWS Lambda with X-Ray

Resources:
  TestLambda:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: testing-x-ray
      Handler: ./handler.php
      Runtime: provided
      Layers:
        - !Sub "arn:aws:lambda:${AWS::Region}:209497400698:layer:php-74:8"
      CodeUri: .
      Tracing: Active
      MemorySize: 512
      Timeout: 10
      Policies:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
        - arn:aws:iam::aws:policy/AWSLambdaExecute
```

and here's my code

```
<?php

require __DIR__ . '/vendor/autoload.php';

require_once 'Daemon.php';
require_once 'Trace.php';

$xray = Daemon::fromEnvironmentVariable();

return function ($event, \Bref\Context\Context $context) use ($xray) {

    $trace = Trace::fromContext($context);

    $xray->initialize($trace);

    $xray->testing('1');
    sleep(1);
    $xray->testing('2');
    $xray->testing('3');
    $xray->testing('4');
    $xray->testing('5');
    sleep(1);
    $xray->testing('6');
    $xray->testing('7');
};
```

```
<?php

class Daemon
{
    const MAX_SEGMENT_SIZE = 64000;

    const HEADER = [
        'format' => 'json',
        'version' => 1
    ];

    private $host;

    private $port;

    private $socket;

    private $trace;

    public function __construct(string $host = '127.0.0.1', int $port = 2000)
    {
        $this->host = $host;
        $this->port = $port;
        $this->socket = socket_create(AF_INET, SOCK_DGRAM, SOL_UDP);
    }

    public static function fromEnvironmentVariable(): self
    {
        $address = explode(':', getenv('AWS_XRAY_DAEMON_ADDRESS'));

        return new self($address[0], $address[1]);
    }

    public function __destruct()
    {
        socket_close($this->socket);
    }

    public function initialize(Trace $trace): void
    {
        $this->trace = $trace;
    }

    public function testing(string $i)
    {
        //{"trace_id": "%s", "id": "defdfd9912dc5a56", "start_time": 1461096053.37518, "end_time": 1461096053.4042, "name": "test.elasticbeanstalk.com"}
        $traceAsJson = json_encode([
            'name' => 'testing',
            'trace_id' => $this->trace->id(),
            'id' => '000000000000000' . $i,
            'start_time' => microtime(true),
            'end_time' => microtime(true),
            'type' => 'subsegment',
            'parent_id' => $this->trace->parent(),
        ]);

        $this->sendPacket('{"format": "json", "version": 1}'.PHP_EOL . $traceAsJson);
    }

    private function sendPacket(string $packet)
    {
        socket_sendto($this->socket, $packet, strlen($packet), 0, $this->host, $this->port);
    }
}
```

```
<?php declare(strict_types=1);

final class Trace
{
    private $id;

    private $parent;

    public function __construct(string  $id, string $parent)
    {
        $this->id = $id;
        $this->parent = $parent;
    }

    public function id(): string
    {
        return $this->id;
    }

    public function parent(): string
    {
        return $this->parent;
    }

    public static function fromContext(\Bref\Context\Context $context): self
    {
        //Root=1-5e94b5fd-9559209b71bdcf3d6d2067a3;
        //Parent=f4af593caaca5260;
        //Sampled=1
        $data = explode(';', $context->getTraceId());

        $trace = explode('=', $data[0]);

        $parent = explode('=', $data[1]);


        return new self($trace[1], $parent[1]);
    }
}
```

I get the data correctly populated on XRay using the code above.

**Comment by viezel** [comment]
So the X-ray works fine. But the idea is not to collect any samples if sampled=0. 
The daemon will always be there though

**Comment by viezel** [comment]
@deleugpn I see your point. let me test with your example.

**Comment by deleugpn** [comment]
@mnapol got a point there. Which layer are you using? Could this be something that is fully working on plain PHP layer, but doesn't work on PHP-FPM?

**Comment by viezel** [comment]
I used PHP-FPM, that did not work. 

Now I just created a simple PHP function, seen below:

```php
<?php
require __DIR__ . '/vendor/autoload.php';

return function ($event, \Bref\Context\Context $context)
{
    echo $context->getTraceId();
};
```

```yml
service: app

provider:
    name: aws
    region: eu-west-1
    runtime: provided

plugins:
    - ./vendor/bref/bref

functions:
    function:
        handler: index.php
        description: ''
        layers:
            - ${bref:layer.php-74}
```

This works fine.

**Comment by viezel** [comment]
So the FPM app is the following:

```php
<?php
echo $_SERVER['HTTP_X_AMZN_TRACE_ID'];
?>

```


serverless.yml:

```yml
service: app

provider:
    name: aws
    region: eu-west-1
    runtime: provided

plugins:
    - ./vendor/bref/bref

functions:
    xray-test:
        handler: index.php
        description: 'X-Ray test'
        timeout: 28 # in seconds (API Gateway has a timeout of 29 seconds)
        layers:
            - ${bref:layer.php-74-fpm}
        events:
            -   http: 'ANY /'
            -   http: 'ANY /{proxy+}'
```

This outputs: `Root=1-5ea1a363-d671fdce836a4b301012f125`

**Comment by mnapoli** [comment]
It seems you are comparing 2 things that are different:

```php
echo $_SERVER['HTTP_X_AMZN_TRACE_ID'];
```

This dumps the `HTTP_X_AMZN_TRACE_ID` HTTP header.

```php
return function ($event, \Bref\Context\Context $context)
{
    echo $context->getTraceId();
};
```

This is not the HTTP header (it is taken from the context).

Maybe try `var_dump($event)` and see if the `X-Amzn-Trace-Id` header contains the full trace there?

I understand that `$context->getTraceId()` works fine, and you could access that variable from FPM. But rather than looking for a workaround, I would love to find the root issue.

Maybe the problem comes from the fact that API Gateway doesn't support multi-value headers out of the box… And because of that, when it splits the `X-Amzn-Trace-Id` it drops everything except the first value?

So what I am suspecting is that this might be a problem with API Gateway?

**Comment by viezel** [comment]
@mnapoli If you read the custom runtime specs from AWS, those should be identical. 

> Get the X-Ray tracing header from the Lambda-Runtime-Trace-Id header in the API response. Set the _X_AMZN_TRACE_ID environment variable locally with the same value. The X-Ray SDK uses this value to connect trace data between services.
https://docs.aws.amazon.com/lambda/latest/dg/runtimes-custom.html

Seems like you are right regarding the API gateway issue. I did a small node function:

```js
exports.handler = async (event) => {
    return {
        statusCode: 200,
        body: JSON.stringify(event.headers),
    };
};
```

and the results are:

```json
{
    "x-amzn-trace-id": "Root=1-5ea2de27-19d753dab29260bc55a2c898",
}
```

**Comment by mnapoli** [comment]
OK thank you for investigating. So API Gateway only passes the first value in the header.

I see 2 possible root causes:

1. API Gateway passes only the first value because it doesn't support multi-value headers by default: could you try enabling multi-value headers and see if you get all values?
2. API Gateway just passes the first value, that's it.

**Comment by viezel** [comment]
@mnapoli how do I enable multi-value headers? and do those automatically get ingested in PHP?

**Comment by mnapoli** [comment]
I think these are enabled by default (https://docs.aws.amazon.com/apigateway/latest/developerguide/set-up-lambda-proxy-integrations.html#api-gateway-simple-proxy-for-lambda-input-format).

What I mean is try this:

```js
exports.handler = async (event) => {
    return {
        statusCode: 200,
        body: JSON.stringify({headers: event.headers, multiValueHeaders: event.multiValueHeaders),
    };
};
```

Then check out `x-amzn-trace-id` in both to see if the value is always the same?

**Comment by viezel** [comment]
the `multiValueHeaders` is not present in that output, meaning its undefined.

**Comment by mnapoli** [comment]
Maybe I did a typo, or maybe that field is not set all the time. Sorry, I don't know more, I can only redirect you to the documentation: https://docs.aws.amazon.com/apigateway/latest/developerguide/set-up-lambda-proxy-integrations.html#apigateway-multivalue-headers-and-parameters

I will be closing this since Bref seems to forward the headers from API Gateway correctly.

If you identify something specific let us know, we can reopen at any time if we identify something to fix or improve inside Bref.

**Comment by i906** [comment]
I am trying out on X-Ray as well. The package [Napp/xray-laravel](https://github.com/Napp/xray-laravel) is also used.

Somehow the `$_SERVER['HTTP_X_AMZN_TRACE_ID']` header is not present. But the traceId can be retrieved in `$_SERVER['LAMBDA_INVOCATION_CONTEXT']`. As a workaround, I get that value and manually put it in `HTTP_X_AMZN_TRACE_ID` so that the package can initialise properly.

**Output**
```json
{
  "invocation_context": {
    "awsRequestId": "...",
    "deadlineMs": 1588756065012,
    "invokedFunctionArn": "...",
    "traceId": "Root=1-5eb27e42-bf172c30135584b2508d0147;Parent=1fc9f3b7c2c0bad4;Sampled=1"
  },
  "_SERVER": {
    "...": "...",
    "AWS_XRAY_DAEMON_ADDRESS": "169.254.79.2:2000",
    "_AWS_XRAY_DAEMON_ADDRESS": "169.254.79.2",
    "_AWS_XRAY_DAEMON_PORT": "2000",
    "AWS_XRAY_CONTEXT_MISSING": "LOG_ERROR",
    "SERVER_SOFTWARE": "bref",
    "HTTP_X_AMZN_VPCE_ID": "...",
    "HTTP_X_AMZN_VPCE_CONFIG": "1",
    "HTTP_X_AMZN_VPC_ID": "...",
    "LAMBDA_CONTEXT": "...",
    "LAMBDA_REQUEST_CONTEXT": "...",
    "LAMBDA_INVOCATION_CONTEXT": "..."
  },
}
```

**IndexController.php**
```php
<?php

namespace App\Http\Controllers;

class IndexController extends Controller
{
    public function index()
    {
        return [
            'invocation_context' => json_decode($_SERVER['LAMBDA_INVOCATION_CONTEXT'], true),
            '_SERVER' => $_SERVER,
        ];
    }
}

```

**serverless.yml**
```yml
service: laravel-serverless-test

provider:
  name: aws
  runtime: provided
  region: ap-southeast-1
  endpointType: PRIVATE
  vpc: ''

  tracing:
    apiGateway: true
    lambda: true

plugins:
  - ./vendor/bref/bref

functions:
  api:
    handler: public/index.php
    timeout: 30
    layers:
      - ${bref:layer.php-74-fpm}
    events:
      - http:
          cors: true
          path: '/'
          method: any

      - http:
          cors: true
          path: '/{proxy+}'
          method: any
```
