### ISSUE TITLE
Internal server error (FastCgiCommunicationFailed) with Lambda + AWS - Lumen (Laravel)

### ISSUE THREAD

**Issue by javila3090** [brefphp/bref#650]
Hi, 

I have an AWS Lambda function based on Lumen micro-framework using bref. The problem is that I occasionally get a 502 Bad Gateway error when I run a database query and CloudWatch shows:

`"errorType": "Bref\\Event\\Http\\FastCgi\\FastCgiCommunicationFailed",`

`Original exception message: hollodotme\\FastCGI\\Exceptions\\ReadFailedException Stream got blocked, or terminated`

`Notice: fwrite(): send of 3412 bytes failed with errno=32 Broken pipe in /var/task/vendor/hollodotme/fast-cgi-client/src/Sockets/Socket.php on line 385`

CloudWatch report 
`Duration: 69.21 ms Billed Duration: 100 ms Memory Size: 1024 MB Max Memory Used: 100 MB`

My serverless.yml

```
service: serverless-api

provider:
    name: aws
    region: eu-central-1
    vpc:
      securityGroupIds:
        - sg-xxxxxxxx
      subnetIds:
        - subnet-xxxxxxx
    runtime: provided
    apiGateway:
        binaryMediaTypes:
            - '*/*'
    environment:
        APP_ENV: production
    iamRoleStatements:
      - Effect: Allow
        Action:
          - s3:*
        Resource: 'arn:aws:s3:::xxxxxxx/*'

plugins:
    - ./vendor/bref/bref

package:
  exclude:
    - node_modules/**
    - public/storage
    - storage/**
    - tests/**
    - .env
    - .git/**
    - .gitignore
  include:
    - storage/oauth-public.key
    - storage/oauth-private.key

functions:
    website:
        handler: public/index.php
        timeout: 28 # in seconds (API Gateway has a timeout of 29 seconds)
        layers:
            - arn:aws:lambda:eu-central-1:209497400698:layer:php-72-fpm:24
        events:
            -   http: 'ANY /'
            -   http: 'ANY /{proxy+}'
    artisan:
        handler: artisan
        timeout: 120 # in seconds
        layers:
            - arn:aws:lambda:eu-central-1:209497400698:layer:php-72:23
            - arn:aws:lambda:eu-central-1:209497400698:layer:console:23
```

The problem is recurring but it does not happen with all requests. The VPC has the NAT Gateway configured.

I tried to find a solution for this, updating layers and php-fpm, but unfortunately the issue persists. I would appreciate if anyone can give me any idea what is going on.

Thank you.
