### ISSUE TITLE
Redirecting `www.example.com` to `example.com` or vice versa

### ISSUE THREAD

**Issue by Chtiadrien** [brefphp/bref#656]
Hello,

I've been using Bref to deploy Slim Framework in a lambda function for a while now. It's been working great! Thank a lot for your work @mnapoli.

But today I stumbled upon a problem. I have a domain, let's say `example.com`, with a website deployed on it using Bref. I'm using Cloudfront + API Gateway + Lambda to handle PHP and (the same) Cloudfront + S3 to handle assets (img/css/js for the website).

Everything worked great until the client typed `www.example.com`. A beautiful DNS error showed up. So I added a CNAME entry for the subdomain `www` to Route53, I generated the correct SSL Certificate (with the naked domain and the www domain) and I updated my CloudFront.

Now I have "two websites". Both `example.com` and `www.example.com` work. Which is a problem from a SEO point of view.

My issue is: how can I redirect the `www` domain to the naked domain? (or the other way around)

I tried to redirect from the lambda, but I cannot have access to the current domain. Is there a way to know which domain is called?

Here's a big chunk of my `serverless.yml` file:

```yml
functions:
  api:
    handler: public/index.php
    description: 'my description'
    timeout: 10
    memorySize: ${self:custom.resources.FunctionMemorySize.${self:provider.stage}}
    layers:
      - ${bref:layer.php-74-fpm}
    events:
      - http: 'ANY /'
      - http: 'ANY /{proxy+}'
    vpc:
      securityGroupIds:
        - sg-aaaaaaa
      subnetIds:
        - subnet-aaaaaaaaaaaaaaa
    role: arn:aws:iam::aaaa
    environment:
      APP_NAME:   ${self:custom.env.APP_NAME.${self:provider.stage}}
      APP_ENV:    ${self:provider.stage}
[way more variable]

resources:
  Resources:
    Assets:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: ${self:custom.resources.S3BucketName.${self:provider.stage}}
        CorsConfiguration:
          CorsRules:
            - AllowedHeaders: ["*"]
              AllowedMethods: [GET]
              AllowedOrigins: ["*"]
    AssetsBucketPolicy:
      Type: AWS::S3::BucketPolicy
      Properties:
        Bucket: !Ref Assets
        PolicyDocument:
          Statement:
            - Effect: Allow
              Principal: '*'
              Action: 's3:GetObject'
              Resource: ${self:custom.resources.S3BucketArn.${self:provider.stage}}
    WebsiteCDN:
      Type: AWS::CloudFront::Distribution
      Properties:
        DistributionConfig:
          Enabled: true
          PriceClass: PriceClass_100
          HttpVersion: http2
          Origins:
            - Id: Website
              DomainName: '#{ApiGatewayRestApi}.execute-api.#{AWS::Region}.amazonaws.com'
              OriginPath: ${self:custom.resources.OriginPath.${self:provider.stage}}
              CustomOriginConfig:
                OriginProtocolPolicy: 'https-only'
            - Id: Assets
              DomainName: '#{Assets}.s3.amazonaws.com'
              CustomOriginConfig:
                OriginProtocolPolicy: 'http-only'
          DefaultCacheBehavior:
            AllowedMethods: [GET, HEAD, OPTIONS, PUT, POST, PATCH, DELETE]
            TargetOriginId: Website
            DefaultTTL: 0
            MinTTL: 0
            MaxTTL: 0
            ForwardedValues:
              QueryString: true
              Cookies:
                Forward: all
              Headers: # I've tried many headers
                - 'Accept'
                - 'Accept-Language'
                - 'Referer'
                - 'User-Agent'
                - 'Set-Cookie'
                - 'From'
                - 'Via'
            ViewerProtocolPolicy: redirect-to-https
          CacheBehaviors:
            - PathPattern: 'assets/*'
              TargetOriginId: Assets
              AllowedMethods: [GET, HEAD]
              ForwardedValues:
                QueryString: 'false'
                Cookies:
                  Forward: none
              ViewerProtocolPolicy: redirect-to-https
              Compress: true
          CustomErrorResponses:
            - ErrorCode: 500
              ErrorCachingMinTTL: 0
            - ErrorCode: 504
              ErrorCachingMinTTL: 0
          Aliases:
            - ${self:custom.resources.DomainName.${self:provider.stage}} # naked domain
            - www.${self:custom.resources.DomainName.${self:provider.stage}} # www domain
          ViewerCertificate:
            AcmCertificateArn: ${self:custom.resources.CertificateArn.${self:provider.stage}}
            SslSupportMethod: 'sni-only'
            MinimumProtocolVersion: TLSv1.1_2016
```

Any help would be greatly appreciated!
