### ISSUE TITLE
Imagick and GD Error

### ISSUE THREAD

**Issue by gustavo9810** [brefphp/bref#721]
According to the [documentation](https://bref.sh/docs/frameworks/laravel.html#file-storage-on-s3), I should be able to make laravel filesystem to work with s3.
The problem is, besides following all the instructions at the docs, whenever I send  a simple request to create a file at the s3 bucket:

```php
use Illuminate\Support\Facades\Storage;

Route::get('filetest', function () {
    Storage::put('myfile.txt', 'This is my file text content');
});
```

The request times out after impressive 28 seconds:

```php
2020-08-18T02:11:22.688-03:00
REPORT RequestId: ff554ec3-de65-406f-8da2-302a1a966586 Duration: 28028.14 ms Billed Duration: 28000 ms Memory Size: 1024 MB Max Memory Used: 134 MB
@billedDuration
28000.0
@duration
28028.14
@ingestionTime
1597727482774
@log
008023226859:/aws/lambda/laravel-dev-web
@logStream
2020/08/18/[$LATEST]aaf098ee14f64d20bd49a3a8f8ffcb1d
@maxMemoryUsed
1.34E8
@memorySize
1.024E9
@message
REPORT RequestId: ff554ec3-de65-406f-8da2-302a1a966586 Duration: 28028.14 ms Billed Duration: 28000 ms Memory Size: 1024 MB Max Memory Used: 134 MB
@requestId
ff554ec3-de65-406f-8da2-302a1a966586
@timestamp
1597727482688
@type
REPORT
11
2020-08-18T02:11:22.688-03:00
2020-08-18T05:11:22.688Z ff554ec3-de65-406f-8da2-302a1a966586 Task timed out after 28.03 seconds
@ingestionTime
1597727482774
@log
008023226859:/aws/lambda/laravel-dev-web
@logStream
2020/08/18/[$LATEST]aaf098ee14f64d20bd49a3a8f8ffcb1d
@message
2020-08-18T05:11:22.688Z ff554ec3-de65-406f-8da2-302a1a966586 Task timed out after 28.03 seconds
@requestId
ff554ec3-de65-406f-8da2-302a1a966586
@timestamp
1597727482688
```

with the following message at the browser page:

```{"message": "Endpoint request timed out"}```

I use exactly the same configs recommend at the docs:
```yaml
provider:
    ...
    environment:
        AWS_BUCKET: # environment variable for Laravel
            Ref: Storage
        FILESYSTEM_DRIVER: s3
    iamRoleStatements:
        # Allow Lambda to read and write files in the S3 buckets
        -   Effect: Allow
            Action: s3:*
            Resource:
                - Fn::GetAtt: Storage.Arn # the storage bucket
                - Fn::Join: ['', [Fn::GetAtt: Storage.Arn, '/*']] # everything in the storage bucket

resources:
    Resources:
        Storage:
            Type: AWS::S3::Bucket
```

Also I've added the ```'token' => env('AWS_SESSION_TOKEN'),``` line at s3 disk configs at ```config/filesystems.php```. I've Tried instead of using ```env()``` put the respective values directly there, tried creating a separated IAM user with full access to s3, but nothing worked.

The weird thing is that my assets (static files) s3 bucket is working just fine, which I was able to set up according to [these docs](https://bref.sh/docs/websites.html#hosting-static-files-with-s3).
Also I made sure to test the request within the url that aws provides ```https://xxxxx.execute-api.us-east-1.amazonaws.com/dev/filetest/```, so there ins't any interference of a custom domain, which I got the above browser message. But, also testing with a custom domain (with https), after a while  loading I get a 502 bad gateway error. 
So, as I've apparently followed all the steps at the documentation and it did not worked, I am opening this issue to check what could be wrong.
