### ISSUE TITLE
Imagick migrated to an external layer

### ISSUE THREAD

**Issue by pleizi** [brefphp/bref#743]
From today it has stopped working Imagick, I have updated my php.ini file but it hasn't worked. Then install bref/extra-php-extensions, following the documentation steps but it still doesn't work. Yesterday it worked without a problem, I don't know what happened.

---

**Edit by @mnapoli**:

Here is the official workaround: use the [Bref extra imagick layer](https://github.com/brefphp/extra-php-extensions):

```
composer require bref/extra-php-extensions
```

Edit `serverless.yml`:

```yaml
plugins:
    - ./vendor/bref/bref
    - ./vendor/bref/extra-php-extensions # <----- Add the extra Serverless plugin

functions:
    foo:
        # ...
        layers:
            - # ... existing layer
            - ${bref:extra.imagick-php-74} # <----- Include the imagick layer
```

Create a `php/conf.d/php.ini` file in your project:

```ini
extension=/opt/bref-extra/imagick.so
```

**Comment by mnapoli** [comment]
Hi, did you do something between yesterday and today? For example did you update Bref?

Could you detail what you mean by "it doesn't work"?

**Comment by pleizi** [comment]
No, I dont update bref, when I detected that Imagick Class stop working, I decided update Bref and install the new extra-php-extension, with the extra-bref-extension the Class work but it always throws me an error.

**Comment by pleizi** [comment]
I create the layer with your zip file but I continue with problems, the Imagick Class work, but when I run my code I get an error. "insufficient image data in file `/tmp/magick-107D8EiVwQQJvw' @ error/jpeg.c/ReadJPEGImage/1156" or "improper image header `/tmp/magick-1037Qq7TcwBDPL' @ error/png.c/ReadPNGImage/"

**Comment by atrope** [comment]
@pleizi  maybe try with another image? Reading the error it looks like Maybe it's the image problem now?

**Comment by pleizi** [comment]
> @pleizi  maybe try with another image? Reading the error it looks like Maybe it's the image problem now? 
> 

I try with 10 images, the image is not the problem, 
I used the same images before the problem and they worked.

**Comment by BenjaminRouge923** [comment]
Hi we have also the problem, any updates ? 
thanks

**Comment by mnapoli** [comment]
Hey thanks everyone for your comments, and thanks @atrope for the insight.

Could you all try out the extension in the https://github.com/brefphp/extra-php-extensions repository? In future Bref versions we will be extracting Imagick 100% in that repository, as a separate extension.

If that separate extension also fails, it should be easier to fix (I think). Here is the script that compiles the extension and extracts all the files needed by it: https://github.com/brefphp/extra-php-extensions/blob/master/layers/imagick/Dockerfile Maybe we should extract more files following the removal by AWS?

**Comment by atrope** [comment]
@mnapoli  in my case those files were enough :)

**Comment by mnapoli** [comment]
OK that's good to know, thanks!

So here is the official workaround: use the [Bref extra imagick layer](https://github.com/brefphp/extra-php-extensions):

```
composer require bref/extra-php-extensions
```

Edit `serverless.yml`:

```yaml
plugins:
    - ./vendor/bref/bref
    - ./vendor/bref/extra-php-extensions # <----- Add the extra Serverless plugin

functions:
    foo:
        # ...
        layers:
            - # ... existing layer
            - ${bref:extra.imagick-php-74} # <----- Include the imagick layer
```

Create a `php/conf.d/php.ini` file in your project:

```ini
extension=/opt/bref-extra/imagick.so
```

---

**Why not fix this in Bref?**

At the moment, I think this might be best not to fix it in Bref. The reason is that it would mean adding extra system files in Bref, thus making the Bref layers heavier. That could make cold starts slower for existing projects, as well as possibly break deployment because they could hit the Lambda size limit.

I understand that this is trouble for some people, but considering that Imagick will not be included by default in Bref 1.0 (it will be available through the Bref Extra extension, as shown above), it doesn't sound too unreasonable to avoid that risk. Even though it means a bit of trouble for some users (sorry about that!), it's a change that was going to happen in 1.0 (coming soon).

Let's keep this issue open to gather feedback, but hopefully you understand the current stance.
