### ISSUE TITLE
Trying out PSR-11 containers for handlers

### ISSUE THREAD

**Issue by Chtiadrien** [brefphp/bref#776]
Hello,

I'm would like to try out the work done in the PR #694, but I'm having some troubles. I'm willing to right some documentations on bref.sh website if I can make this work correctly. If the PSR-11 feature is not complete, I'm OK to make a PR to make it work like it was describe in the original PR.

I've created a new project from scratch. I used PHP 8.0 (I can do more testing on 7.4 if needed). I followed the example in the PR (I'm not sure about everything I wrote 😳 😅). When I deployed the stack, the API Gateway just return a `Internal Server Error`. From the logs in CloudWatch, I have the following error : 

```
Handler `/var/task/App\Controllers\HomeController` doesn't exist
```

This is the state of my project:

serverless.yml:
```yaml
service: psr11-container

provider:
  name: aws
  region: eu-west-3
  runtime: provided
  stage: ${opt:stage, 'preprod'}

plugins:
  - ./vendor/bref/bref

functions:
  home:
    handler: App\Controllers\HomeController
    timeout: 28 # in seconds (API Gateway has a timeout of 29 seconds)
    layers:
      - ${bref:layer.php-80-fpm}
    events:
      -   httpApi: 'GET /'

# Exclude files from deployment
package:
  exclude:
    - 'node_modules/**'
    - 'tests/**'
```

src/Controllers/HomeController.php:
```php
<?php

namespace App\Controllers;

use Bref\Context\Context;
use Bref\Event\Http\HttpHandler;
use Bref\Event\Http\HttpRequestEvent;
use Bref\Event\Http\HttpResponse;

class HomeController extends HttpHandler
{
    public function handleRequest(HttpRequestEvent $event, Context $context): HttpResponse
    {
        return new HttpResponse(json_encode(["hello" => "world"]), ["Content-Type" => "application/json"]);
    }
}
```

bootstrap.php
```php
<?php

Bref\Bref::setContainer(
    function () {
        $builder = new DI\ContainerBuilder;
        return $builder->build();
    }
);
```

composer.json
```json
{
  "name": "edited",
  "description": "edited",
  "type": "project",
  "authors": [
    {
      "name": "Adrien Furnari",
      "email": "edited"
    }
  ],
  "autoload": {
    "psr-4": {
      "App\\": "src/"
    },
    "files": [
      "bootstrap.php"
    ]
  },
  "config": {
    "sort-package": true
  },
  "require": {
    "php": "^8.0",
    "ext-json": "^8.0",
    "bref/bref": "^0.5.31",
    "bref/logger": "^1.0",
    "php-di/php-di": "^6.3"
  }
}
```

I know this is purely a support issue and I'm sorry for that, if this is not the place, I'm willing to discuss about that via another way.
