### ISSUE TITLE
[1.0] Error while loading shared libraries: libncurses.so.6

### ISSUE THREAD

**Issue by reganjohnson** [brefphp/bref#803]
Recently upgraded to `bref-1.0` and seeing the following error on CloudWatch on deploy.

```
/opt/bin/php: error while loading shared libraries: libncurses.so.6: cannot open shared object file: No such file or directory
```
Relevant configuration:
```
service: web-app

provider:
  name: aws
  region: us-east-1
  stage: dev
  runtime: provided.al2

plugins:
  - ./vendor/bref/bref
  - ./vendor/bref/extra-php-extensions
  - serverless-domain-manager

functions:
  web:
    handler: public/index.php
    timeout: 10
    memorySize: 1024
    layers:
      - ${bref:layer.php-74-fpm}
      - ${bref:extra.redis-php-74}
    events:
      - httpApi: '*'
```

**Comment by mnapoli** [comment]
Thanks for the report. There have been new releases in https://github.com/brefphp/extra-php-extensions, could you update to v0.7.0 of this repository and check again if you see the same problem?

**Comment by reganjohnson** [comment]
> Thanks for the report. There have been new releases in https://github.com/brefphp/extra-php-extensions, could you update to v0.7.0 of this repository and check again if you see the same problem?

I have upgraded to the latest, and am still seeing the same error message. I also tried to remove the `serverless.yml` config for `./vendor/bref/extra-php-extensions` and `${bref:extra.redis-php-74}` and the issue still persists.

**Comment by reganjohnson** [comment]
I originally, I was only updating the function after the upgrade (`sls deploy function -f web --stage dev`). On a full serverless stack deploy and rebuild (`sls deploy --stage dev`), I am no longer receiving this error.

I think it is generally understood that changes to `serverless.yml` outside of the function configuration would need a full redeploy, so a documentation change may not be required.

None the less, this incident now exists for others search for a similar issue. Thanks for your excellent work pushing serverless and PHP forward. 🙏

**Comment by mnapoli** [comment]
Thanks a lot for the update and the feedback!

**Comment by corsair** [comment]
@mnapoli 
Hello there, I am also experiencing this exact error when trying to deploy a fresh serverless instance with bref on the latest versions.

> /opt/bin/php: error while loading shared libraries: libncurses.so.6: cannot open shared object file: No such file or directory

Versions I am using:
bref/bref: 1.0.0
bref/extra-php-extensions: 0.7.2
bref/laravel-bridge: 1.0.0
laravel/framework: 8.16.1 

Here are the same portions of my serverless.yml.
```
functions:
  worker:
    handler: worker.php
    layers:
      - ${bref:layer.php-80}
    events:
      -   sqs:
            arn:
              Fn::GetAtt: [ VehicleUpdateQueue, Arn ]
            # Only 1 item at a time to simplify error handling
            batchSize: 1

package:
  exclude:
    - .env
    - node_modules/**
    - public/storage
    - resources/assets/**
    - storage/**
    - tests/**

plugins:
  - ./vendor/bref/bref
  - ./vendor/bref/extra-php-extensions
```
