### ISSUE TITLE
Cannot find module 'undefined/../node_modules/chalk'

### ISSUE THREAD

**Issue by codybolinger** [brefphp/bref#837]
I am trying to deploy with the serverless framework v2.19.0 and seeing this error:

(Rolled back to Bref v1.0.2 and it works fine)

```
serverless deploy

 Error: Cannot find module 'undefined/../node_modules/chalk'
      at Function.Module._resolveFilename (internal/modules/cjs/loader.js:655:15)
      at Function.Module._load (internal/modules/cjs/loader.js:580:25)
      at Module.require (internal/modules/cjs/loader.js:711:19)
      at require (internal/modules/cjs/helpers.js:14:16)
      at new ServerlessPlugin (/opt/atlassian/pipelines/agent/build/vendor/bref/bref/index.js:14:22)
      at PluginManager.addPlugin (/usr/local/lib/node_modules/serverless/lib/classes/PluginManager.js:95:28)
      at resolveServicePlugins.filter.forEach (/usr/local/lib/node_modules/serverless/lib/classes/PluginManager.js:138:33)
      at Array.forEach (<anonymous>)
      at PluginManager.loadAllPlugins (/usr/local/lib/node_modules/serverless/lib/classes/PluginManager.js:138:8)
      at loadEnvVariables.then.then (/usr/local/lib/node_modules/serverless/lib/Serverless.js:91:39)
```

Error appears to occur with Bref versions 1.1.0 and 1.1.1 

Serverless File: 
```
plugins:
  - ./vendor/bref/bref
  - ./vendor/bref/extra-php-extensions
  - serverless-stage-manager
functions:
  index:
    handler: index.php
    layers:
      - ${bref:layer.php-73-fpm}
      - ${bref:extra.memcached-php-73}
    events: ${file(./serverless_config/routes.yml):events}
    environment: ${file(./serverless_config/environment_variables.yml):environment}
```
