### ISSUE TITLE
is not authorized to perform: lambda:GetLayerVersion on resource

### ISSUE THREAD

**Issue by RobinHoutevelts** [brefphp/bref#840]
For some time now we cannot deploy when using more than one bref layer. As soon as we add the Redis layer we get the following error:

> User: arn:aws:iam::xxxxxxxxxxxx:user/apptourmanagementcom-serverlessdeploy-general-DeployUser is not authorized to perform: lambda:GetLayerVersion on resource: arn:aws:lambda:eu-central-1:403367587399:layer:redis-php-80:8 (Service: AWSLambdaInternal; Status Code: 403; Error Code: AccessDeniedException; Request ID: df6f9596-e8a2-4a22-b50a-586d2b94316c; Proxy: null)

`bref/bref` (`1.1.2`) and `bref/extra-php-extensions` (`0.9.5`) are fully up-to-date.

This is our `serverless.yml` file:

```
service: apitourmanagementcom
frameworkVersion: ">=2.18.0"

provider:
    name: aws
    runtime: provided.al2
    region: eu-central-1
    profile: tourmanagement
    stage: ${opt:stage}
    logRetentionInDays: 30
    stackTags:
        environment: ${self:provider.stage}
        project: ${self:provider.profile}
    httpApi:
        cors: true
    useDotenv: false # Will become default in future versions, and the .env is meant for symfony, not serverless

plugins:
    - ./vendor/bref/bref
    - ./vendor/bref/extra-php-extensions
    - serverless-stage-manager

custom:
    # serverless-stage-manager
    stages:
        - development
        - staging
        - production

functions:
    api:
        handler: public/index.php
        description: ''
        timeout: 28 # in seconds (API Gateway has a timeout of 29 seconds)
        layers:
            - ${bref:layer.php-80-fpm}
            # - ${bref:extra.redis-php-80} <--- Once this is uncommented, we cannot deploy
        events:
            -   httpApi: '*'


# Exclude files from deployment
package:
    exclude:
        - 'node_modules/**'
        - 'tests/**'
```

<details>
<summary>Click to see package.json</summary>

```
{
  "name": "api.tourmanagement.com",
  "version": "1.0.0",
  "description": "### Setup",
  "main": "index.js",
  "dependencies": {},
  "devDependencies": {
    "serverless": "^2.18.0",
    "serverless-stage-manager": "^1.0.5"
  },
  "scripts": {
    "serverless": "serverless"
  },
  "author": "",
  "license": "ISC"
}
```
</details>

Deploy logs:

```
$ npm run serverless -- -s $ENVIRONMENT deploy
> api.tourmanagement.com@1.0.0 serverless /builds/tourmanagement/app.tourmanagement.com/backend
> serverless "-s" "development" "deploy"
Serverless: Deprecation warning: Detected ".env" files. Note that Framework now supports loading variables from those files when "useDotenv: true" is set (and that will be the default from next major release)
            More Info: https://www.serverless.com/framework/docs/deprecations/#LOAD_VARIABLES_FROM_ENV_FILES
Serverless: Deprecation warning: Starting with next major version, default value of provider.lambdaHashingVersion will be equal to "20201221"
            More Info: https://www.serverless.com/framework/docs/deprecations/#LAMBDA_HASHING_VERSION_V2
Serverless: Packaging service...
Serverless: Excluding development dependencies...
Serverless: Creating Stack...
Serverless: Checking Stack create progress...
........
Serverless: Stack create finished...
Serverless: Uploading CloudFormation file to S3...
Serverless: Uploading artifacts...
Serverless: Uploading service apitourmanagementcom.zip file to S3 (16.2 MB)...
Serverless: Validating template...
Serverless: Updating Stack...
Serverless: Checking Stack update progress...
............
Serverless: Operation failed!
Serverless: View the full error output: https://eu-central-1.console.aws.amazon.com/cloudformation/home?region=eu-central-1#/stack/detail?stackId=arn%3Aaws%3Acloudformation%3Aeu-central-1%3A499262277468%3Astack%2Fapitourmanagementcom-development%2F864cb9f0-58f1-11eb-b78e-02b488480b0c

  Serverless Error ---------------------------------------

  An error occurred: HttpApi - User: arn:aws:iam::xxxxxxxxxxxx:user/apptourmanagementcom-serverlessdeploy-general-DeployUser is not authorized to perform: apigateway:POST on resource: arn:aws:apigateway:eu-central-1::/apis (Service: AmazonApiGatewayV2; Status Code: 403; Error Code: AccessDeniedException; Request ID: 6768527c-e8a4-4b9c-98da-d5599cb7f38c; Proxy: null).

  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Issues:        forum.serverless.com

  Your Environment Information ---------------------------
     Operating System:          linux
     Node Version:              12.20.1
     Framework Version:         2.18.0 (local)
     Plugin Version:            4.4.2
     SDK Version:               2.3.2
     Components Version:        3.4.7
```

By commenting out the Redis layer, everything does work. And I get an endpoint I can visit ( that works ).

```
$ npm run serverless -- -s $ENVIRONMENT deploy
> api.tourmanagement.com@1.0.0 serverless /builds/tourmanagement/app.tourmanagement.com/backend
> serverless "-s" "development" "deploy"
Serverless: Deprecation warning: Detected ".env" files. Note that Framework now supports loading variables from those files when "useDotenv: true" is set (and that will be the default from next major release)
            More Info: https://www.serverless.com/framework/docs/deprecations/#LOAD_VARIABLES_FROM_ENV_FILES
Serverless: Configuration warning at 'provider': unrecognized property 'useDotenv'
Serverless:
Serverless: Learn more about configuration validation here: http://slss.io/configuration-validation
Serverless:
Serverless: Deprecation warning: Starting with next major version, default value of provider.lambdaHashingVersion will be equal to "20201221"
            More Info: https://www.serverless.com/framework/docs/deprecations/#LAMBDA_HASHING_VERSION_V2
Serverless: Packaging service...
Serverless: Excluding development dependencies...
Serverless: Uploading CloudFormation file to S3...
Serverless: Uploading artifacts...
Serverless: Uploading service apitourmanagementcom.zip file to S3 (17.58 MB)...
Serverless: Validating template...
Serverless: Updating Stack...
Serverless: Checking Stack update progress...
.........
Serverless: Stack update finished...
Service Information
service: apitourmanagementcom
stage: development
region: eu-central-1
stack: apitourmanagementcom-development
resources: 11
api keys:
  None
endpoints:
  ANY - https://xxxxxxxxxx.execute-api.eu-central-1.amazonaws.com
functions:
  api: apitourmanagementcom-development-api
layers:
  None
```
