### ISSUE TITLE
Test symfony serverless. Error.

### ISSUE THREAD

**Issue by stloc** [brefphp/bref#856]
Hi,

after below instructions https://bref.sh/docs/frameworks/symfony.html#setup, I have this error on deploy : 

```
 Serverless Error ---------------------------------------

  Invalid variable reference syntax for variable bref:layer.php-74-fpm. You can only reference env vars, options, & files. You can check our docs for more info.

  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Issues:        forum.serverless.com

  Your Environment Information ---------------------------
     Operating System:          linux
     Node Version:              12.18.4
     Framework Version:         2.22.0
     Plugin Version:            4.4.2
     SDK Version:               2.3.2
     Components Version:        3.6.2

```

**Comment by mnapoli** [comment]
Hi, could you please share your `serverless.yml`?

**Comment by stloc** [comment]
```
service: bref-demo-symfony

provider:
  name: aws
  region: eu-west-3
  runtime: provided.al2
  environment:
    # Symfony environment variables
    APP_ENV: prod

  plugins:
    - ./vendor/bref/bref

  package:
    exclude:
      - node_modules/**
      - tests/**
      - var/**

  functions:
    website:
      handler: public/index.php
      timeout: 28 # in seconds (API Gateway has a timeout of 29 seconds)
      layers:
        - ${bref:layer.php-74-fpm}
      events:
        - httpApi: '*'
    console:
      handler: bin/console
      timeout: 120 # in seconds
      layers:
        - ${bref:layer.php-74} # PHP
        - ${bref:layer.console} # The "console" layer
```
