### ISSUE TITLE
HttpApiRouteDefault Internal Failure

### ISSUE THREAD

**Issue by RTC1** [brefphp/bref#868]
During deployment of a new bref/serverless environment I get this:

" An error occurred: HttpApiRouteDefault - Internal Failure.'

If I setup with http/v1 or remove the httpApi event it completes but fails if the httpApi is re-added. I have also been able to setup the API Gateway manually. 

The Cloudtrail API for the CreateRoute Operation shows the following error message: "Unable to complete operation due to concurrent modification. Please try again later."

AWS support have suggested:

"I don't see any simultaneous API calls being made in Cloudtrail, but I believe this could be because of the Route being created right after the Integration being created with a 2 second delay."

Bref: 1.2.0
Serverless: 2.26.0

```

service: some-package

provider:
  name: aws
  region: eu-west-2
  runtime: provided.al2

plugins:
  - ./vendor/bref/bref

functions:
  app:
    handler: public/index.php
    timeout: 29
    layers:
      - ${bref:layer.php-80-fpm}
    events:
      - httpApi: '*'
```

Has anyone experienced this before, and is there a way I can get more debug info?
