### ISSUE TITLE
Unable to use variables from external file reference

### ISSUE THREAD

**Issue by Blacksmoke16** [brefphp/bref#888]
**Description:**

This is similar to https://github.com/brefphp/bref/issues/372, but related to the ability to reference an [external file](https://www.serverless.com/framework/docs/providers/aws/guide/variables#reference-variables-in-other-files) as an object.  I'm pretty sure this is a `bref` issue as our serverless version hasn't changed and this error did not reproduce when using `bref` `0.5.10`. 

**How to reproduce:**

Do something like:

`serverless-variables.yml`
```yaml
region: us-east-1
```

`serverless.yml`
```yaml
variables: ${file(./serverless-variables.yml)}

provider:
  name: aws
  runtime: provided.al2
  region: ${self:variables.region}

plugins:
  - ./vendor/bref/bref

functions:
  console:
    handler: app/console
    layers:
      - ${bref:layer.php-74}
      - ${bref:layer.console}
```

Then when running `sls info` for example:

```sh
 Serverless Warning --------------------------------------

  A valid service attribute to satisfy the declaration 'self:variables.region' could not be found.


 Exception -----------------------------------------------

  'There is no Bref layer named "php-74" in region "[object Object]"'

  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Issues:        forum.serverless.com

  Your Environment Information ---------------------------
     Operating System:          darwin
     Node Version:              12.16.3
     Framework Version:         1.55.1
     Plugin Version:            3.2.0
     SDK Version:               2.1.2
     Components Core Version:   1.1.2
     Components CLI Version:    1.4.0
```

It seems the `.region` is not being resolved to the underlying value correctly.  Accessing a specific property in the file works as expected, e.g. `region: ${file(./serverless-variables.yml):region}`.
