### ISSUE TITLE
artisan migrate error with MYSQL_ATTR_SSL_CA

### ISSUE THREAD

**Issue by davefv** [brefphp/bref#904]
**Description:**

When I deploy my laravel app I can't execute artisan migrate if I have defined MYSQL_ATTR_SSL_CA in .env production file. The web funcion works well with this config, but the artisan command fails. If I comment this line, the artisan command works well. 

Maybe any difference between php-74-fpm and php-74 on pdo_mysql library or openssl?

**How to reproduce:**

- PHP: 7.4
- Bref: v1.2.3
- Serverless:
Framework Core: 2.32.1
Plugin: 4.5.3
SDK: 4.2.2
Components: 3.8.1
- Laravel: v8.35.1
- Laravel bridge: v1.0.0

```
$ vendor/bin/bref cli app-prod-artisan --region=eu-west-3 -- migrate --force
rc/Illuminate/Database/Migrations/Migrator.php(608): Illuminate\\Database\\Migrations\\DatabaseMigrationRepository->repositoryExists()
#15 /var/task/vendor/laravel/framework/src/Illuminate/Database/Console/Migrations/MigrateCommand.php(106): Illuminate\\Database\\Migrations\\Migrator->repositoryExists()
#16 /var/task/vendor/laravel/framework/src/Illuminate/Database/Console/Migrations/MigrateCommand.php(77): Illuminate\\Database\\Console\\Migrations\\MigrateCommand->prepareDatabase()
#17 /var/task/vendor/laravel/framework/src/Illuminate/Database/Migrations/Migrator.php(541): Illuminate\\Database\\Console\\Migrations\\MigrateCommand->Illuminate\\Database\\Console\\Migrations\\{closure}()
#18 /var/task/vendor/laravel/framework/src/Illuminate/Database/Console/Migrations/MigrateCommand.php(94): Illuminate\\Database\\Migrations\\Migrator->usingConnection()
#19 /var/task/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(36): Illuminate\\Database\\Console\\Migrations\\MigrateCommand->handle()
#20 /var/task/vendor/laravel/framework/src/Illuminate/Container/Util.php(40): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#21 /var/task/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(93): Illuminate\\Container\\Util::unwrapIfClosure()
#22 /var/task/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(37): Illuminate\\Container\\BoundMethod::callBoundMethod()
#23 /var/task/vendor/laravel/framework/src/Illuminate/Container/Container.php(611): Illuminate\\Container\\BoundMethod::call()
#24 /var/task/vendor/laravel/framework/src/Illuminate/Console/Command.php(136): Illuminate\\Container\\Container->call()
#25 /var/task/vendor/symfony/console/Command/Command.php(256): Illuminate\\Console\\Command->execute()
#26 /var/task/vendor/laravel/framework/src/Illuminate/Console/Command.php(121): Symfony\\Component\\Console\\Command\\Command->run()
#27 /var/task/vendor/symfony/console/Application.php(971): Illuminate\\Console\\Command->run()
#28 /var/task/vendor/symfony/console/Application.php(290): Symfony\\Component\\Console\\Application->doRunCommand()
#29 /var/task/vendor/symfony/console/Application.php(166): Symfony\\Component\\Console\\Application->doRun()
#30 /var/task/vendor/laravel/framework/src/Illuminate/Console/Application.php(92): Symfony\\Component\\Console\\Application->run()
#31 /var/task/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(129): Illuminate\\Console\\Application->run()
#32 /var/task/artisan(37): Illuminate\\Foundation\\Console\\Kernel->handle()
#33 {main}
"}

   Illuminate\Database\QueryException

  SQLSTATE[HY000] [2002]  (SQL: select * from information_schema.tables where table_schema = app and table_name = migrations and table_type = 'BASE TABLE')

  at vendor/laravel/framework/src/Illuminate/Database/Connection.php:678
    674▕         // If an exception occurs when attempting to run a query, we'll format the error
    675▕         // message to include the bindings with SQL, which will make this exception a
    676▕         // lot more helpful to the developer instead of just the database's errors.
    677▕         catch (Exception $e) {
  ➜ 678▕             throw new QueryException(
    679▕                 $query, $this->prepareBindings($bindings), $e
    680▕             );
    681▕         }
    682▕

      +33 vendor frames 
  34  artisan:37
      Illuminate\Foundation\Console\Kernel::handle()71adc299-08eb-41a2-81b0-6bbdc44b48dd        Invoke Error    {"errorType":"Exception","errorMessage":"The command exited with a non-zero status code: 1","stack":["#0 \/var\/task\/vendor\/bref\/bref\/src\/Runtime\/Invoker.php(34): {closure}()","#1 \/var\/task\/vendor\/bref\/bref\/src\/Runtime\/LambdaRuntime.php(102): Bref\\Runtime\\Invoker->invoke()","#2 \/opt\/bootstrap(69): Bref\\Runtime\\LambdaRuntime->processNextEvent()","#3 {main}"]}
END RequestId: 71adc299-08eb-41a2-81b0-6bbdc44b48dd
REPORT RequestId: 71adc299-08eb-41a2-81b0-6bbdc44b48dd  Duration: 114.94 ms     Billed Duration: 115 ms Memory Size: 1024 MB    Max Memory Used: 126 MB
```

serverless.yaml

```yaml
service: app
provider:
    name: aws
    # The AWS region in which to deploy (us-east-1 is the default)
    region: eu-west-3
    # The stage of the application, e.g. dev, production, staging… ('dev' is the default)
    stage: prod
    runtime: provided.al2
   environment:
        BREF_BINARY_RESPONSES: 1       
    apiGateway:
        binaryMediaTypes:
            - '*/*'
functions:
    # This function runs the Laravel website/API
    web:
        handler: public/index.php
        timeout: 28 # in seconds (API Gateway has a timeout of 29 seconds)
        layers:
            - ${bref:layer.php-74-fpm}
        events:
            -   httpApi: '*'
    # This function lets us run artisan commands in Lambda
    artisan:
        handler: artisan
        timeout: 599 # in seconds
        layers:
            - ${bref:layer.php-74} # PHP
            - ${bref:layer.console} # The "console" layer


plugins:
    # We need to include the Bref plugin
    - ./vendor/bref/bref
```

.env

```
MYSQL_ATTR_SSL_CA=./rds-combined-ca-bundle.pem
```
Thank you very much for this amazing project!
