### ISSUE TITLE
Enabling variablesResolutionMode: 20210326

### ISSUE THREAD

**Issue by timrspratt** [brefphp/bref#908]
Adding the advised deprecation flag `variablesResolutionMode: 20210326` (NEW_VARIABLES_RESOLVER) results in the bref layer variable failing:

```yml
variablesResolutionMode: 20210326

functions:
  web:
    layers:
      - ${bref:layer.php-80-fpm}

plugins:
  - ./vendor/bref/bref
```

Output

```
Serverless Error ----------------------------------------
 
  Approached unrecognized configuration variable sources: "bref"

Your Environment Information ---------------------------
     Operating System:          darwin
     Node Version:              14.16.0
     Framework Version:         2.33.1
     Plugin Version:            4.5.3
     SDK Version:               4.2.2
     Components Version:        3.8.1
```
