### ISSUE TITLE
Serverless deprecation warning for bref layers with new variable resolution mode

### ISSUE THREAD

**Issue by andrea-cristaudo** [brefphp/bref#913]
**Description:**

With the new serverless variable resolution mode (https://www.serverless.com/framework/docs/deprecations/#NEW_VARIABLES_RESOLVER) there's a deprecation warning on bref layer references (eg. ${bref:layer.php-74-fpm}).

> Serverless: Deprecation warning: Approached unrecognized configuration variable sources: "bref".
>            From a next major this will be communicated with a thrown error.
>            Set "variablesResolutionMode: 20210326" in your service config, to adapt to new behavior now
>            More Info: https://www.serverless.com/framework/docs/deprecations/#NEW_VARIABLES_RESOLVER

**How to reproduce:**

```yaml
service: servicename

provider:
  [...]

plugins:
  - ./vendor/bref/bref

functions:
  api:
    handler: public/index.php
    timeout: 28 # in seconds (API Gateway has a timeout of 29 seconds)
    layers:
      - ${bref:layer.php-74-fpm}
    events:
      - httpApi: '*'
```
