### ISSUE TITLE
Handle patterns instead of exclude in serverless.yml when using separate vendor option

### ISSUE THREAD

**Issue by svnldwg** [brefphp/bref#925]
**Description:**

When using the separate vendor option, the vendor directory is added to the package.exclude array in the serverless.yml, if it's not there yet. package.exclude is deprecated and it is now recommended to use package.patterns. Not defining the package.exclude key will result in an error.

This bug can easily be fixed, I will open a pull request shortly.

**How to reproduce:**

```
custom:
    bref:
        separateVendor: true

package:
    patterns:
        - '!node_modules/**'
```
