### ISSUE TITLE
First Steps: Internal Server Error 500

### ISSUE THREAD

**Issue by kavatari** [brefphp/bref#932]
**Description:**

Following this guide: https://bref.sh/docs/first-steps.html 
I want to run the simple "Hello World" example. After deploying the app to AWS Lambda and calling the url, I receive the error 500 with the message:  `{"message":"Internal Server Error"}`

**How to reproduce:**
Installed bref version (using composer): 1.2.6
```
composer require bref/bref
vendor/bin/bref init
serverless deploy
``` 
**serverless.yml**
```
service: app
provider:
  name: aws
  region: us-east-1
  runtime: provided.al2
plugins:
  - ./vendor/bref/bref
functions:
  api:
    handler: index.php
    description: ''
    timeout: 28 # in seconds (API Gateway has a timeout of 29 seconds)
    layers:
      - ${bref:layer.php-74-fpm}
    events:
      - httpApi: '*'
# Exclude files from deployment
package:
  exclude:
    - 'node_modules/**'
    - 'tests/**'
 ```
Saw this closed issue: https://github.com/brefphp/bref/issues/390 but it doesn't help.
