### ISSUE TITLE
error running a console command

### ISSUE THREAD

**Issue by stloc** [brefphp/bref#964]
**Description:**

 application deployed OK
![image](https://user-images.githubusercontent.com/4832070/124133065-bf4c0a00-da81-11eb-89a5-5360486bdb88.png)

 but running console failed :

```
In Response.php line 402:

  HTTP 404 returned for "https://lambda.us-east-1.amazonaws.com/2015-03-31/functions/console-prod/invocations".

  Code:    ResourceNotFoundException
  Message: Function not found: arn:aws:lambda:us-east-1:389937582648:function:console-prod
  Type:    user
  Detail:
```

**How to reproduce:**

`vendor/bin/bref cli console-prod -- list`

**Comment by t-richard** [comment]
Hi @stloc :wave: 

Could you try `vendor/bin/bref cli symfony-prod-console -- list` ?

**Comment by stloc** [comment]
```
endpoints:
  ANY - https://hgi575qok9.execute-api.eu-west-3.amazonaws.com
functions:
  web: symfony-prod-web
  console: symfony-prod-console
layers:
  None
```

` Function not found: arn:aws:lambda:us-east-1:389937582648:function:symfony-prod-console`
why us-east ? instead my config region: eu-west-3 ?
