### ISSUE TITLE
Console layer: `bref.separateVendor: true` doesn't work

### ISSUE THREAD

**Issue by mnapoli** [brefphp/bref#975]
### Discussed in https://github.com/brefphp/bref/discussions/974

```
require_once(/opt/breftoolbox.php): Failed to open stream: No such file or directory in /opt/bootstrap on line 15
```

<div type='discussions-op-text'>

<sup>Originally posted by **semsphy** July 21, 2021</sup>
Hello There,

I configured to use the `separateVendor` and ran below command, I got an error `Failed to open stream: No such file or directory in /opt/bootstrap on line 15`.

`vendor/bin/bref cli function-prod-artisan --profile=xzy --region ap-southeast-1 -- route:list`

Any suggestions, pls.

### serverless.yml
```yml
service: xzy-services
useDotenv: true

custom:
  bref:
    separateVendor: true

provider:
  name: aws
  region: ap-southeast-1
  runtime: provided.al2

  environment:
    BREF_BINARY_RESPONSES: '1'
    BREF_AUTOLOAD_PATH: '/tmp/vendor/autoload.php'

artisan:
    handler: artisan
    timeout: 120 # in seconds
    layers:
      - ${bref:layer.php-80} # PHP
      - ${bref:layer.console} # The "console" layer
```

### public/index.php

```php
//...

if(isset($_SERVER['LAMBDA_TASK_ROOT'])){
    require '/tmp/vendor/autoload.php';
}
else{
    require __DIR__.'/../vendor/autoload.php';
}

//...
```</div>
